### ISSUE TITLE
Website uses 50% CPU and steals memory in Pale Moon

### ISSUE THREAD

**Issue by chylex** [chrippa/livestreamer#1001]
Hello, I was sent a link to this website and as soon as I opened it, the browser pretty much gave up... I checked the task manager and saw that Pale Moon was constantly using 50-55% CPU and went from ~500 MB to 1 GB of RAM usage.

Using latest Pale Moon (25.5.0 x64) which is a Firefox based browser. The system itself isn't too great (2 core CPU with 1.2 GHz per core, 4 GB RAM, integrated graphics, Win7 x64) but this certainly doesn't happen with any other website. The issue is reliably replicated even in Safe Mode with addons and plugins disabled.

I also checked Firebug and saw that the website was constantly creating AJAX requests to api.grokthedocs.com, which throws 502 error. Saw like, 6 requests starting all at the same time, failing, then starting a bunch again, which is a bit suspicious... could not do any actual profiling because the browser was unusable.

Any idea what's going on? :/

**Comment by chrippa** [comment]
The site we host the docs on (readthedocs.org) inserts some javascript which is out our of control, however it does not seem to be behaving the way you describe it for me. I also get a AJAX request to grokthedocs.com, but only once and CPU usage is normal using Firefox 38.

**Comment by chylex** [comment]
I did some testing, it looks like only Pale Moon and older versions of Firefox have the issue. Normally I'd ignore it as an outdated browser problem, but Pale Moon is up to date and actively developed, so there might have been some old bug in FF that was not fixed in the PM fork. Can't imagine what it could be though.
