### ISSUE TITLE
Can't connect to specific twitch stream

### ISSUE THREAD

**Issue by disco0** [chrippa/livestreamer#1002]
C:\Windows\System32>livestreamer twitch.tv/faceittv  source
[cli][info] Found matching plugin twitch for URL twitch.tv/faceittv
error: No streams found on this URL: twitch.tv/faceittv

I can't seem to connect to this twitch stream, and I'm currently watching it live via browser.  I've tested other streams through liverstreamer (in fact this stream was working earlier) and they work fine atm, does anyone have any suggestions to coaxing the stream out?

**Comment by skulblakka** [comment]
There is currently no stream on faceittv. They are currently hosting another stream (dreamhackcs).

**Comment by disco0** [comment]
Ah, thanks didn't realize I had to input that one.  Thanks!
