### ISSUE TITLE
Can't pass custom window title via -a and VLCRC file

### ISSUE THREAD

**Issue by MacKirby** [chrippa/livestreamer#1003]
I've had a look at [Issue 218](https://github.com/chrippa/livestreamer/issues/218) and unfortunately I've not gotten any further.  I'm unsure of the relationship between "input-title-format=" in the VLCRC file I have, and how to actually use this to rename the window.  I've tried different arguments such as meta arguments e.g. $u, $p but to no avail, and also I've tried just having a string like "Test" (with and without quotes" after the = sign.  I'm also unsure of {filename} and if/what that should be changed to?  I tried putting VLCRC in there and it wouldn't work.

**vlcrc file:** 
#Change title according to current media (string)
input-title-format=Option

Plays but title stays as "fd://0"- livestreamer twitch.tv/channelname best -a "--config vlcrc {filename}"

Throws a KeyError - livestreamer twitch.tv/channelname best -a "--config vlcrc {vlcrc}"

The VLCRC file is located in the root of the Livestreamer folder, and is called "vlcrc".  Any guidance would be very much appreciated.

**Comment by 0880** [comment]
Example command line:

````
livestreamer "http://www.twitch.tv/[...]" best --player-args "--config C:\Users\[...]\AppData\Roaming\vlc\vlcrc {filename}"
````

VLCRC file:

````
# Change title according to current media
input-title-format=TITLE
````

**Comment by MacKirby** [comment]
Thank you SO much!  I've been pulling my hair out about this.
