### ISSUE TITLE
Support for YouTube Live stream countdown

### ISSUE THREAD

**Issue by InfernoZeus** [chrippa/livestreamer#1014]
I'm not sure how feasible this is, but it would be great if livestreamer could monitor a YouTube Live stream URL, and only connect when it goes live.

At the moment, I get this behaviour when trying to connect to the URL before it's live:
```
livestreamer --loglevel debug https://www.youtube.com/watch?v=a0N6cHJ-o4w
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=a0N6cHJ-o4w
error: No streams found on this URL: https://www.youtube.com/watch?v=a0N6cHJ-o4w
```

**Comment by hannespetur** [comment]
The `--retry-streams` parameter ought to do it.

http://docs.livestreamer.io/cli.html#cmdoption--retry-streams

E.g.
`livestreamer --retry-streams 10 https://www.youtube.com/watch?v=a0N6cHJ-o4w best`
will retry every 10 seconds.

**Comment by InfernoZeus** [comment]
Perfect, missed that option! Thanks :)
