### ISSUE TITLE
Vlc doesn't show stream link

### ISSUE THREAD

**Issue by bzsat** [chrippa/livestreamer#1015]
Hi
I want to extract the stream link from this address: "ustream.tv/channel/live-iss-stream" by using livestreamer, but vlc player always shows "fd://0" as the url and doesn't show the stream link. I use this command:
"livestreamer ustream.tv/channel/live-iss-stream worst" 
vlc player opens and plays the stream but doesn't give stream link url and just shows fd://0.
How could i find the stream link such as rtmp or anyother stream type of that?
My system is windows and player is vlc.
Thank you

**Comment by skulblakka** [comment]
If you just want livestreamer to return the URL of the stream use the [stream-url parameter](http://docs.livestreamer.io/cli.html#cmdoption--stream-url)

**Comment by bzsat** [comment]
i tried that but gives this error:
"D:\Documents and Settings\BZ>livestreamer ustream.tv/channel/live-iss-stream worst --stream-url
error: The stream specified cannot be translated to a URL"

please say me how could i find the rtmp, rtsp, or anyother stream type of ustream.tv/channel/live-iss-stream.

i want to use the stream link such as rtmp,rtsp in my cellphone's player (e.g. mx player, vlc.)

**Comment by hannespetur** [comment]
The livestreamer command you posted works on my end. Which version of livestreamer are you using?

**Comment by 0880** [comment]
The lowest available quality (240p) on this channel is an UHS stream:

````
livestreamer "http://ustream.tv/channel/live-iss-stream" worst
[cli][info] Found matching plugin ustreamtv for URL http://ustream.tv/channel/live-iss-stream
[cli][info] Available streams: 240p (worst), 240p_alt_akamai, 480p+ (best), 480p+_alt_akamai, mobile_284p
[cli][info] Opening stream: 240p (uhs)
````
This streaming protocol is a combination of two different streaming protocols (RTMP and HTTP). It simply can not be translated into one URL. It should work properly with other streaming protocols such as HTTP Live Streaming (e.g. mobile_284p):

````
livestreamer "http://ustream.tv/channel/live-iss-stream" mobile_284p --stream-url
http://sjc-uhls-proxy02.ustream.tv/watch/playlist.m3u8?appType=103&appVersion=3&conn=wifi&cid=9408562&stream=viewer_240p&connectionId=oldurl-638c3c9b9b9eb71a4588295a98404624c9c87ddf&group=iphone
````

**Comment by bzsat** [comment]
Thanks a lot 0880.
could you say please if someone needs 240p (uhs stream) how should he do to access to the uhs stream link? with what command he can access to that?

**Comment by 0880** [comment]
Ustreams own streaming protocol is way more complex than you think. The whole stream is splitted into a huge amount of chunks. They do their best to prevent access to their streams. You will have to use the Livestreamer application to access the 240p UHS stream. There is currently no other way around it.

**Comment by chrippa** [comment]
`livestreamer --stream-types hls --stream-url "http://ustream.tv/channel/live-iss-stream" best` will return a HLS stream URL if it's available.
