### ISSUE TITLE
timeout when writing to file is not being followed

### ISSUE THREAD

**Issue by alexdale** [chrippa/livestreamer#1020]
Hi , not sure if anyone else has encountered this issue, but if I try to set a timeout while writing audio to a file, it seems like the timeout is not enforced and it continues recording well past. For example:

`livestreamer --hls-timeout 15.0 twitch.tv/kolento audio -fo test.mp3`

Will not get cut off at 15 seconds like I want but will continue recording until I force stop it. Weirdly, if I change the timeout to something very small (like 3.0 seconds) it seems to get cut off sometimes properly. 

Am I missing something? Is there another way to enforce a time limit on recording to file? Or even limit the file size or something?

Thanks

**Comment by chrippa** [comment]
This is not what timeout means in this case. Timeout here means the time to wait without any data being received before aborting. There is currently no functionality for what you're asking, however you can use an external program such as [`timeout`](https://www.gnu.org/software/coreutils/manual/html_node/timeout-invocation.html) to accomplish this.
