### ISSUE TITLE
Install on raspberry pi 2 and update livestreamer

### ISSUE THREAD

**Issue by jesuisbaatman** [chrippa/livestreamer#1022]
hello
it is possible to install livestreamer on a raspberry pi 2 with Raspbian ? 

you can tell me how to do ?

and final question I install livestreamer on debian and I do not know how to do the update ?

sorry for my english im french
thank you

**Comment by hannespetur** [comment]
Yes, I believe there is a package you can install on the raspberry. Try:

```
sudo apt-get install livestreamer
```
If that doesn't work you can always use pip instead
```
sudo apt-get install python-pip
```
then
```
sudo pip install -U livestreamer
```
You can also use those very same commands to update livestreamer on your Debian system.

**Comment by jesuisbaatman** [comment]
thank you its working perfectly
