### ISSUE TITLE
error: The default player (VLC) does not seem to be installed.  You must specify your path to a player executable with --player

### ISSUE THREAD

**Issue by fr3dw0rd** [chrippa/livestreamer#1025]
Hey, 
I'm quite new to this and I'm already a bit confused :D
It says I don't have VLC installed, even though I have it.
I've installed it at C/Programs/VLC.
If someone could help me, I would be very thankful :D

Freddy

**Comment by skulblakka** [comment]
Like it says you can use the --player command to specify the location of the player.

You can do this either in the command itself. For example:
```
livestreamer twitch.tv/twitch best --player="C:\Program Files\VideoLAN\VLC\vlc.exe"
```

Or you can change the value inside the [livestreamerrc](http://docs.livestreamer.io/cli.html#configuration-file) file.

**Comment by fr3dw0rd** [comment]
Thank you very much :)

**Comment by dmenace65** [comment]
Hello every one!
I try this and no result for me why is VLC not responding? I even try removing the # in front of all VLC at the player list. can some one directer me to another solution please.

Thanks
Dennis
