### ISSUE TITLE
how to move cache file to ramdisk?

### ISSUE THREAD

**Issue by holdonL** [chrippa/livestreamer#1033]
Sorry guys, but Ive read all the stuff, cant find where the livestreamer or vlc store cache so i could move and symlink it from my ramdisk. Help me out pls!

**Comment by chrippa** [comment]
Livestreamer does not write the stream buffer to disk, it's kept in memory.

**Comment by holdonL** [comment]
oh gosh thanks a lot! i love your app, many thanks!
