### ISSUE TITLE
Youtube fallback seems not working

### ISSUE THREAD

**Issue by todostreaming** [chrippa/livestreamer#1034]
I'm using '720p,480p,360p,240p' for a Youtube video, and starts with 720p but when there are download fails, does not seem to fall down to 480p or below. 
Does this feature work as is expected to ?
I'm using the latest stable 1.12.2 version

Thanks, great tool !!!
/ts

**Comment by chrippa** [comment]
The fallback is only used when deciding on what stream to attempt to open, for example if 720p is not available it will open 480p and so on. It does not however move to the next one if there is an error after that.
