### ISSUE TITLE
Azubu broken, playerKey missing

### ISSUE THREAD

**Issue by hayksaakian** [chrippa/livestreamer#1040]
azubu changed their frontend so azubu.py is broken right now

this new endpoint contains the list of sources. you don't need playerKey any more

https://edge.api.brightcove.com/playback/v1/accounts/3361910549001/videos/ref:video61298CHhungryapptv

**Comment by hayksaakian** [comment]
You need a special header to actually get this information.

It's a pretty involved process, but some of the data could probably be cached


Example, load this stream: hungryapptv

1) get the config.js url (this probably doesn't change too often)
Extract the config URL from the html at this URL

---> http://www.azubu.tv/hungryapptv

2) get a player id from config js file
Extract it from a line that looks like this:
'home': '497f3c86-b138-45f9-80fc-f7f3c9dc1afa'

---> http://www.azubu.tv/config/config.c908c9fe.js

you might want to grab the account id, but it's never changed 
3361910549001

3) get a policy key
Extract it from a line that looks like this 
'policyKey': "BCpkADawqM0ffxZ5Sw3K_ie5A53lt3wJo2CaNQhHXLgQMbZba37vFf1-457BJmLUYcWFeidH2WWmL4lU4raGWa1p5NIO7pkX5c8p9tI09nySGao9X0XYPLdhhVbRirHzZ1vkStvGlfa6b0O0"

---> http://players.brightcove.net/3361910549001/497f3c86-b138-45f9-80fc-f7f3c9dc1afa_default/index.js

4) send the policy key with your header

BCOV-Policy:BCpkADawqM0ffxZ5Sw3K_ie5A53lt3wJo2CaNQhHXLgQMbZba37vFf1-457BJmLUYcWFeidH2WWmL4lU4raGWa1p5NIO7pkX5c8p9tI09nySGao9X0XYPLdhhVbRirHzZ1vkStvGlfa6b0O0

---> https://edge.api.brightcove.com/playback/v1/accounts/3361910549001/videos/ref:video61298CHhungryapptv

5) now you have a json object with a list of sources including one m3u8 playlist

**Comment by wolftankk** [comment]
please try the nightly build

**Comment by hayksaakian** [comment]
my mistake, seems like the develop branch works, and in a much simpler way than i found.

thanks @wolftankk
