### ISSUE TITLE
MPC-HC stream delay

### ISSUE THREAD

**Issue by ragemuffin** [chrippa/livestreamer#1047]
Is there a way to reduce the delay or is it a problem on the player itself?
When I compare the delay on a Twitch.tv page compared to using Livestreamer with MPC-HC, the delay seems to be quite long (30 seconds).

**Comment by Paynmayn** [comment]
I get max 2 seconds delay when using livestreamer in MPC-HC compared to the player on twitch.tv, and sometimes 2 seconds ahead.

**Comment by skulblakka** [comment]
You can try changing the [--hls-live-edge](http://docs.livestreamer.io/cli.html#cmdoption--hls-live-edge) parameter.
