### ISSUE TITLE
Periscope Fail?

### ISSUE THREAD

**Issue by cathalgarvey** [chrippa/livestreamer#1049]
Hi all,

Just tried livestreamer for the first time, using the below command and with exactly the below output:

    livestreamer 'https://www.periscope.tv/w/aK1_UTI2OTA5NzZ8MXluSk9MVlZMbXd4UiW3ZHaL_-fkEfyZRkwy1Q_hJDrE6gaQcs3RFyEv3MF5' -o Some_Periscope
    [cli][info] Found matching plugin periscope for URL https://www.periscope.tv/w/aK1_UTI2OTA5NzZ8MXluSk9MVlZMbXd4UiW3ZHaL_-fkEfyZRkwy1Q_hJDrE6gaQcs3RFyEv3MF5
    error: Unable to validate JSON: Key 'hls_url' not found in {'participant_index': 0, 'should_log': False, 'type': 'StreamTypeReplay', 'subscriber': 'sub-c-642f220c-d70e-11e3-93e0-02ee2ddab7fe', 'cookies': [{'Unparsed': None, 'Raw': '', 'Value': 'eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9yZXBsYXkucGVyaXNjb3BlLnR2L0hGaEhfdjN4TU0yN1NpM3Jadm5yejREVFdQNW1HVTlYaTItbnVUQ1R6N3pSUDJUUjl4OGpYRGJCMm9FYW9tV0pMZXlYUzVXYnBNTGs3QVZRRUtjMEVRPT0qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDQwNjc0NDQyfX19XX0_', 'Name': 'CloudFront-Policy', 'Secure': False, 'Domain': '.periscope.tv', 'Expires': '0001-01-01T00:00:00Z', 'HttpOnly': False, 'MaxAge': 0, 'Path': '/', 'RawExpires': ''}, {'Unparsed': None, 'Raw': '', 'Value': 'gWHbl1oLg5Z-q42mAHk8aUrDjFOGojN0r806HYhXz6~2l5XaB3fZcIFz8E-JYqbGrAMkino-nl8d17-kd~EE5gRqkiUD2r-b2uLnOZVjRjNXcvHB~1e-QMjk98vjOAJJ7pibeXqkuxbQSelvEv8~eKRcM7kEQd2vIJ7oS38BrHvYx9-KoCL3qIp4k2wiw5eIesZ1KRBdrBdxfiyryfrL7L8eD4xnGEZT0fWoNmkH5wHifUXDWFljzo~U29ezKkj4jJ9G4BFF4XpLXxAdRQl6DYVSUca4i2KDnmuTmL4FDfiTDH5jw6E4wZ~bPARN7qxCtpxgdRbIdW0t9dF0CCoIFA__', 'Name': 'CloudFront-Signature', 'Secure': False, 'Domain': '.periscope.tv', 'Expires': '0001-01-01T00:00:00Z', 'HttpOnly': False, 'MaxAge': 0, 'Path': '/', 'RawExpires': ''}, {'Unparsed': None, 'Raw': '', 'Value': 'APKAIHCXHHQVRTVSFRWQ', 'Name': 'CloudFront-Key-Pair-Id', 'Secure': False, 'Domain': '.periscope.tv', 'Expires': '0001-01-01T00:00:00Z', 'HttpOnly': False, 'MaxAge': 0, 'Path': '/', 'RawExpires': ''}], 'signer_token': '', 'publisher': '', 'channel': 'HFhH_v3xMM27Si3rZvnrz4DTWP5mGU9Xi2-nuTCTz7zRP2TR9x8jXDbB2oEaomWJLeyXS5WbpMLk7AVQEKc0EQ==', 'read_only': True, 'session': '1440588042126077108', 'auth_token': 'NxpipQVyZ4hZNMp5tPh8n4IZf4qBLqHJag9_MiV7i5A=', 'endpoint': '', 'access_token': '', 'signer_key': 'MIIBUjCB+qADAgECAhEAoANGtFcLbiucQcYbdcih5TAKBggqhkjOPQQDAjAXMRUwEwYDVQQKEwxQZXJpc2NvcGUgQ28wHhcNMTUwODI1MjM1MTM5WhcNMTUwODI2MjM1MTM5WjAXMRUwEwYDVQQKEwxQZXJpc2NvcGUgQ28wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASrGRcprIkjzgQIMDsDueXo8ZMP9U9eF+5E8vO7f6mJGIbBJK19WOBKqUsLNx9ndJyRbAKsBLV56zbTXxgj9QkUoycwJTAOBgNVHQ8BAf8EBAMCAKQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwCgYIKoZIzj0EAwIDRwAwRAIgP1WbPekQxbEZlO+QARmdfSRFkdL9nK4c4zvcIwCBvHACIHmZWX2r9CaivxpenZSqW1MNOJ6QxY3XVGXX6w0QFGOW', 'should_verify_signature': True, 'replay_url': 'https://replay.periscope.tv/HFhH_v3xMM27Si3rZvnrz4DTWP5mGU9Xi2-nuTCTz7zRP2TR9x8jXDbB2oEaomWJLeyXS5WbpMLk7AVQEKc0EQ==/playlist.m3u8'}

**Comment by 0880** [comment]
It's working for me. No error message is shown.

````
livestreamer "https://www.periscope.tv/w/aK1_UTI2OTA5NzZ8MXluSk9MVlZMbXd4UiW3ZHaL_-fkEfyZRkwy1Q_hJDrE6gaQcs3RFyEv3MF5" best -o 01.ts
[cli][info] Found matching plugin periscope for URL https://www.periscope.tv/w/aK1_UTI2OTA5NzZ8MXluSk9MVlZMbXd4UiW3ZHaL_-fkEfyZRkwy1Q_hJDrE6gaQcs3RFyEv3MF5
[plugin.periscope][info] Live Stream ended, using replay instead
[cli][info] Available streams: replay (worst, best)
[cli][info] Opening stream: replay (hls)
````

**Comment by cathalgarvey** [comment]
Hmm! I `git clone`'d the repository and `python3.4 setup.py develop`'d it, and now it works. The version I was using was from the Arch repos and had the same version number as the PyPI version, so if it's possible that a fix has been made to the git repo that isn't yet on PyPI, it might be worth posting a new version.

Thank you!
