### ISSUE TITLE
--player-external-http-port not working.

### ISSUE THREAD

**Issue by SeNeO** [chrippa/livestreamer#1051]
I can't manage to make this work (whatever stream I'm trying with)
`livestreamer http://www.twitch.tv/kolento best --player-external-http-port 8081`
It's open the stream in VLC.

`livestreamer http://www.twitch.tv/kolento best --player-external-http` works correctly but as soon as I try to specify a port it open the stream in VLC.

I don't know if it's an issue or I'm doing something wrong... I'm on OSX 10.10.5 if it helps.

**Comment by skulblakka** [comment]
The documentation for [--player-external-http-port](http://docs.livestreamer.io/cli.html#cmdoption--player-external-http-port) says "A fixed port to use for the external HTTP server if that mode is enabled.".

Try using both --player-external-http-port and --player-external-http.

**Comment by SeNeO** [comment]
Oh thanks!!! I didn't think that both argument were needed...
