### ISSUE TITLE
Request for help/plugin

### ISSUE THREAD

**Issue by roshavagarga** [chrippa/livestreamer#1060]
The specific websites I'm interested in are these:

http://btv.bg/live
http://novatv.bg/live
http://tv.bnt.bg/bnthd

Second and third require you to be within Bulgaria. When trying to load their true streams which are hosted via http://cdn.bg/ provider, I get 403 Domain Locked or no data (domainlocked when using httpstream ... and no data for rtmpe). 

I am pretty sure I can use the last two if there is a way to tell the stream provider I am viewing it through its original url, because it obviously checks. 

First one requires a free account to be made, and then I could not find its stream url by looking at the page source.

**Comment by 10mins** [comment]
Novatv.bg with rtmpdump+vlc: 
>rtmpdump -r "rtmp://e1.cdn.bg:2060/fls" -T "N0v4TV6#2" -a "fls" -f "WIN 18,0,0,232" -W "http://i.cdn.bg/eflash/jwNTV/player.swf" -p "http://i.cdn.bg/live/0OmMKJ4SgY" -y "ntv_1.stream" | vlc -

**Comment by roshavagarga** [comment]
@10mins can you run me through how you got to that command (In case they change something and I need to do it on my own) and how I actually use it? I have rtmpdump, but cmd doesn't recognize what you posted as a command line.

**Comment by biezom** [comment]
<pre>rtmpdump -r "rtmp://e1.cdn.bg:2060/fls" -T "N0v4TV6#2" -a "fls" -f "WIN 18,0,0,232" -W "http://i.cdn.bg/eflash/jwNTV/player.swf" -p "http://i.cdn.bg/live/0OmMKJ4SgY" -y "ntv_1.stream" | "C:\Program Files\VideoLAN\VLC\vlc.exe" -</pre>

**Comment by roshavagarga** [comment]
@biezom Yeah, I'm trying this on my Windows PC, and it's tellming me "rtmpdump" isn't recognized as a command. The only instance I have of rtmpdump comes preinstalled with livestreamer.

Can you tell me how that command works and how you built it, so I can do so on my own and not waste your time :)

**Comment by skulblakka** [comment]
>I'm trying this on my Windows PC, and it's tellming me "rtmpdump" isn't recognized as a command

You either need to change to the directory in which the rtmpdump.exe is located or you simply add it to your path variable.

**Comment by roshavagarga** [comment]
@skulblakka hm, Netstream.play.failed when I open a command prompt in the rtmpdump folder and run the last command from biezom

**Comment by biezom** [comment]
rtmp://e1.cdn.bg:2060/fls >> rtmp://lb.cdn.bg:2010/fls

<pre>rtmpdump -r "rtmp://lb.cdn.bg:2010/fls" -T "N0v4TV6#2" -a "fls" -f "WIN 18,0,0,232" -W "http://i.cdn.bg/eflash/jwNTV/player.swf" -p "http://i.cdn.bg/live/0OmMKJ4SgY" -y "ntv_1.stream" | "C:\Program Files\VideoLAN\VLC\vlc.exe" -</pre>

**Comment by biezom** [comment]
if you download the source code you can find all info (except the token) about rtmp protocol
and you can find also the link of hls protocol
so download source code

<pre>livestreamer --http-header "Referer=http://novatv.bg/live/"  "httpstream://http://i.cdn.bg/live/0OmMKJ4SgY" best -o nova.txt</pre>
you can find this
<pre>http://ios.cdn.bg:2010/fls/ntv_1.stream/playlist.m3u8</pre>
and this
<pre>streamer: "rtmp://lb.cdn.bg:2010/fls",
	        provider: 'rtmp',
	                        levels: [
	                                        {
	                                                bitrate : "512",
	                                                width : "720",
	                                                file : "ntv_1.stream"
	                                        },
	                                        { 
	                                        bitrate : "1024",
	                                        width : "720",
	                                        file : "ntv_2.stream"
	                                        }
	                                ],
	         title: 'NovaTV Live Stream',
	
	         flashplayer: "http://i.cdn.bg/eflash/jwNTV/player-at.swf"</pre>

so with hls protocol with a good user agent
<pre>livestreamer --http-header "User-Agent=Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_1_2 like Mac OS X; ko-kr) AppleWebKit/528.18 (KHTML,like Gecko) Version/4.0 Mobile/7D11 Safari/528.16"  "hlsvariant://http://ios.cdn.bg:2010/fls/ntv_2.stream/playlist.m3u8" best</pre>

and with rtmp protocol
<pre>rtmpdump -r "rtmp://lb.cdn.bg:2010/fls" -T "N0v4TV6#2" -p "http://i.cdn.bg/live/0OmMKJ4SgY" -y "ntv_2.stream" | "C:\Program Files\VideoLAN\VLC\vlc.exe" -</pre>

**Comment by biezom** [comment]
http://novatv.bg/live
source code
<pre>livestreamer --http-header "Referer=http://tv.bnt.bg/bnthd/"  "httpstream://http://i.cdn.bg/live/OQ70Ds9Lcp" best -o bnthd.txt</pre>

<pre>http://ios.cdn.bg:2020/fls/bntHDt.stream/playlist.m3u8?at=a66f96f60c2f74e03daa1ae01c3020cf</pre>
with at=a66f96f60c2f74e03daa1ae01c3020cf dynamic value so you can't use it
<pre>flashplayer: "http://i.cdn.bg/eflash/jwplayer510/player.swf",

        "file": "bntHDt.stream?at=a66f96f60c2f74e03daa1ae01c3020cf",
        "streamer": "rtmp://lb.cdn.bg:2020/fls",
        "provider": "rtmp",
        "rtmp.tunneling": false,
        "stretching": "exactfit</pre>

<pre>livestreamer "hlsvariant://http://ios.cdn.bg:2020/fls/bntHDt.stream/playlist.m3u8?at=a66f96f60c2f74e03daa1ae01c3020cf" best</pre>

<pre>rtmpdump -r "rtmp://lb.cdn.bg:2020/fls" -T 'B@1R1st1077'  -p "http://i.cdn.bg/live/OQ70Ds9Lcp"  -y "bntHDt.stream?at=a66f96f60c2f74e03daa1ae01c3020cf" | "C:\Program Files\VideoLAN\VLC\vlc.exe" -</pre>

**Comment by roshavagarga** [comment]
@biezom The novatv hlsvariant one works perfectly. Since I have no idea how to turn that into a plugin, I'll just save it online and copy it when needed

The BNT one seems to be faltering. I'm getting this message:
"Unable to open URL ... <No connection adapters were found for 'rtsp://127.0.0.1/access.denied'>

The BNT ones might be trickier somehow, there are 4 channels (I gave you the HD one) that are positioned at http://tv.bnt.bg/, and 3 of them are as I previously said hardcoded to Bulgarian IPs. Might that be the problem?

**Comment by biezom** [comment]
yes for http://tv.bnt.bg/bnthd you need Bulgarian IP

**Comment by roshavagarga** [comment]
@Biezom I do have one, as I'm currently in Bulgaria, but I still can't connect. I'm missing something I guess o_o

**Comment by biezom** [comment]
did you use 

<pre>livestreamer --http-header "Referer=http://tv.bnt.bg/bnthd/"  "httpstream://http://i.cdn.bg/live/OQ70Ds9Lcp" best -o bnthd.txt</pre>

to find your own value playlist.m3u8?at=....................
or did you use the same code i posted?

**Comment by roshavagarga** [comment]
@biezom Okay, now it works. I'm guessing I have to do this every time I want to livestream it. 

http://tv.bnt.bg/ - The same method should work for BNT2 and BNT1, since they're hardcoded to Bulgarian IPs. 

Also, if I'm outside of Bulgaria, I should add a proxy to the livestreamer command, so that it looks as if I'm within Bulgaria, correct?

**Comment by biezom** [comment]
<pre>livestreamer --http-header "Referer=http://tv.bnt.bg/bnt1/16x9/"  "httpstream://http://cdn.bg/live/4eViE8vGzI" best -o bnt1.txt</pre>


<pre>livestreamer --http-header "User-Agent=Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_1_2 like Mac OS X; ko-kr) AppleWebKit/528.18 (KHTML,like Gecko) Version/4.0 Mobile/7D11 Safari/528.16" "hlsvariant://http://ios.cdn.bg:2020/fls/bnt.stream/playlist.m3u8?at=YOUR-OWN-VALUE-FOUND-IN-bnt1.txt" best</pre>


<pre>livestreamer --http-header "Referer=http://tv.bnt.bg/bnt2/16x9/"  "httpstream://http://cdn.bg/live/ZBPbdxDHm7" best -o bnt2.txt</pre>


<pre>livestreamer --http-header "User-Agent=Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_1_2 like Mac OS X; ko-kr) AppleWebKit/528.18 (KHTML,like Gecko) Version/4.0 Mobile/7D11 Safari/528.16"  "hlsvariant://http://ios.cdn.bg:2020/fls/bnt2.stream/playlist.m3u8?at=YOUR-OWN-VALUE-FOUND-IN-bnt2.txt" best</pre>

**Comment by roshavagarga** [comment]
Thank you, all of these work perfectly. 

Where does the --http(s)-proxy go in the command?

**Comment by biezom** [comment]
you need use the same proxy to get source and stream
you need a good proxy (often pays), without good proxy not enough bandwidth to get the stream 

<pre>livestreamer --http-proxy "http://hostname:port/"  --http-header "Referer=http://tv.bnt.bg/bnt2/16x9/"  "httpstream://http://cdn.bg/live/ZBPbdxDHm7" best -o bnt2.txt</pre>

<pre>livestreamer --http-proxy "http://hostname:port/"  --http-header "User-Agent=Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_1_2 like Mac OS X; ko-kr) AppleWebKit/528.18 (KHTML,like Gecko) Version/4.0 Mobile/7D11 Safari/528.16"  "hlsvariant://http://ios.cdn.bg:2020/fls/bnt2.stream/playlist.m3u8?at=YOUR-OWN-VALUE-FOUND-IN-bnt2.txt" best</pre>
