### ISSUE TITLE
Can't open streams from dailymotion games

### ISSUE THREAD

**Issue by ishbutz** [chrippa/livestreamer#1069]
When I try to read a stream on dailymotion games with livestreamer and VLC, I always get this error (in french):

'utm_medium' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
'utm_campaign' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

This could be translated as :
'utm_medium' is not recognized as an internal or external command, a executable software or a command file.
Same error for 'utm_campaign'.

When I try this on dailymotion it works fine.
And I know that the dailymotion plugin should work with dailymotion games (previous issue).
I'm not an expert with livestreamer but I tried many options and none of them worked.

Does anybody know this issue and the way to fix it ?

Thanks.

**Comment by StarWolf3000** [comment]
utm_medium and utm_campaign are parameters which are required for Google's Analytics program.

Looks like they are not filtered by the plugin and let the command interpreter throw errors.

**Comment by ishbutz** [comment]
ok thanks for the answer.
I don't really understand why there is the Google's Analytics program in the dailymotion website but I hope that the next version of livestreamer (or the dailymotion plugin) will fix this bug.

Livestreamer is a great software, the streams quality on VLC is a lot better than flash (with twitch among others) especially with old PC's. I will recommend it for sure.

**Comment by intact** [comment]
Dailymotion plugin works for me.

Btw. you need to quote url

**Comment by StarWolf3000** [comment]
But the Youtube URLs also use the question mark and there are no problems with them on cmd/shell.

Or has it to do with how many params are parsed by the plugin? Because these both are usually the last ones in URLs.

**Comment by ishbutz** [comment]
For dailymotion games, I found out that the url without quotes works with one of my PC on windows 8.1 and you need to add quotes with windows 10 (the version of windows seems to be the only difference between those 2 PC but I'm not sure...).
Now Livestreamer works fine.

Thanks for your answers !
