### ISSUE TITLE
Feature Request: Mobcrush

### ISSUE THREAD

**Issue by jeffblagg** [chrippa/livestreamer#1072]
Would love to have www.mobcrush.com included in livestreamer!

Thanks!

**Comment by tp0** [comment]
Actual live streams (not past and archived broardcasts, didn't figure those out) on that site seems to be just plain HLS. Until a plugin comes out you can play them via Livestreamer (or probably in a media player directly too):

Open browser developer tools (F12 in Chrome and Firefox), open the stream and look at the network tab and copy the .m3u8 url that comes up:

    livestreamer hls://http://live-us-east-1.mobcrush.com/hls/0/5606b26f29c72c1a1732f6ef_high.m3u8 best
