### ISSUE TITLE
Error in azubutv plugin when stream is offline

### ISSUE THREAD

**Issue by FichteFoll** [chrippa/livestreamer#1083]
The exception is pretty clear, but I don't know what value `video_player` is supposed to have when the stream is offline, so I'll just leave this here.

I was using `azubutv.py` from the development branch, since the stable has the problem with playerKey.

```
C:\Users\Fichte>livestreamer azubu.tv/riotgames
[cli][info] Found matching plugin azubutv for URL azubu.tv/riotgames
Traceback (most recent call last):
  File "C:\Python34\Scripts\livestreamer-script.py", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "C:\Python34\lib\site-packages\livestreamer_cli\main.py", line 886, in main
    handle_url()
  File "C:\Python34\lib\site-packages\livestreamer_cli\main.py", line 471, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Python34\lib\site-packages\livestreamer_cli\main.py", line 388, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Python34\lib\site-packages\livestreamer\plugin\plugin.py", line 313, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Python34\lib\site-packages\livestreamer\plugin\plugin.py", line 227, in streams
    ostreams = self._get_streams()
  File "C:\Python34\lib\site-packages\livestreamer\plugins\azubutv.py", line 168, in _get_streams
    key, video_player, player_id, is_live = self._get_player_params()
  File "C:\Python34\lib\site-packages\livestreamer\plugins\azubutv.py", line 152, in _get_player_params
    return key, video_player, player_id, is_live
UnboundLocalError: local variable 'video_player' referenced before assignment
```

**Comment by nCrazed** [comment]
Just ran into a somewhat related issue:

Embeded stream (http://www.azubu.tv/azubulink/embed=gameshow_csgoen) works by redirecting to http://players.brightcove.net/3361910549001/13b53caa-9aa1-48be-a9f2-657520f437af_default/index.html?playlistId=ref:gameshow_csgoenPlaylist&channel=gameshow_csgoen but accessing it via the main site (http://www.azubu.tv/gameshow_csgoen) comes up as offline.

Attempting to view either the normal or embed URLs via livestreamer will return the above stack trace.

**Comment by 0880** [comment]
@nCrazed

Referenced pull request from [sulami] (https://github.com/sulami) prevents this stack trace (https://github.com/chrippa/livestreamer/pull/1092).

````
livestreamer "http://www.azubu.tv/gameshow_csgoen" best
[cli][info] Found matching plugin azubutv for URL http://www.azubu.tv/gameshow_csgoen
error: No streams found on this URL: http://www.azubu.tv/gameshow_csgoen
````

There is currently no live stream on this channel. The embedded stream only shows a video and videos are currently not supported by Livestreamer. At least not directly by the plugin.

It's an video from an previously recorded live stream. 

http://oldschool.azubu.tv/gameshow_csgoen#!/play/112184/spacesoldiers-vs-onbots-@21cet---gameshow-global-esports-cup

http://azubuhd.brightcove.com.edgesuite.net/hd/3361910549001/201511/3361910549001_4638485104001_video112184CHgameshowcsgoen.mp4?pubId=3361910549001&videoId=4638399819001

````
livestreamer "httpstream://azubuhd.brightcove.com.edgesuite.net/hd/3361910549001/201511/3361910549001_4638485104001_video112184CHgameshowcsgoen.mp4?pubId=3361910549001&videoId=4638399819001" best
[cli][info] Found matching plugin stream for URL httpstream://azubuhd.brightcove.com.edgesuite.net/hd/3361910549001/201511/3361910549001_4638485104001_video112184CHgameshowcsgoen.mp4?pubId=3361910549001&videoId=4638399819001
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
````

**Comment by Shaaah** [comment]
>Referenced pull request from sulami prevents this stack trace (#1092).

Thanks! Helps quite a bit :)
