### ISSUE TITLE
Azubu.tv missing PlayerKey

### ISSUE THREAD

**Issue by jocelynthode** [chrippa/livestreamer#1091]
When I'm trying to watch a stream on Azubu, I get this error :
``` livestreamer http://www.azubu.tv/SouzaaPlays source```
```[cli][info] Found matching plugin azubutv for URL http://www.azubu.tv/SouzaaPlays```
 ```error: Missing key 'playerKey' in player params```

I'm using Archlinux with livestreamer 1.12.2

**Comment by sulami** [comment]
This is fixed in the development branch, you can get the new plugin [here](https://github.com/chrippa/livestreamer/blob/develop/src/livestreamer/plugins/azubutv.py).

**Comment by jocelynthode** [comment]
Thanks I'll close this issue then

**Comment by abjugard** [comment]
Is there a reason this fix has not been released yet? I mean current azubutv plugin doesn't work period, so there should at least be a bugfix release including this fixed plugin.

**Comment by fog1992** [comment]
@sulami thx

**Comment by DavidVentura** [comment]
Any update on why this is not released?

**Comment by ghost** [comment]
> Any update on why this is not released?

This commit was pushed into develop branch. [Nightly builds](http://livestreamer-builds.s3.amazonaws.com/livestreamer-latest-win32.zip) are available which contain the latest development code. Master branch was not updated, so there are currently no new releases.

**Comment by Hubro** [comment]
Just installed newest version available on pip, 1.12.2, and this error still occurs.

**Comment by skulblakka** [comment]
Like @0880 said. There is currently no new release of livestreamer. Use the [Nightly builds ](http://livestreamer-builds.s3.amazonaws.com/livestreamer-latest-win32.zip) on Windows or use `pip install -U git+https://github.com/chrippa/livestreamer.git` to get the latest development version via pip.

**Comment by igorprado** [comment]
If you are on MacOS El Captain, you need to run with the flag `--ignore-installed six`:

`(sudo) pip install -U git+https://github.com/chrippa/livestreamer.git --ignore-installed six`
