### ISSUE TITLE
Fail to obtain all available streams.

### ISSUE THREAD

**Issue by nxtreaming** [chrippa/livestreamer#1098]
https://www.youtube.com/watch?v=PiFv7cICWRU
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=PiFv7cICWRU
[cli][info] Available streams: 144p (worst), 240p, 360p (best), 360p_3d, audio_mp4, audio_webm
[cli][info] Opening stream: 360p (http)

But there is 480p stream if you watch the link by browser.

**Comment by 0880** [comment]
[MPEG-DASH] (https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) (e.g. 480p) is currently not supported (#439).

**Comment by nxtreaming** [comment]
Thanks, I will try to fix this issue.
