### ISSUE TITLE
How to parse json from html?

### ISSUE THREAD

**Issue by steven7851** [chrippa/livestreamer#1109]
Recently I try to make plugin for zhanqi.tv.
I try this to parse json but it can not work.

https://github.com/steven7851/livestreamer/blob/patch-3/src/livestreamer/plugins/zhanqi.py

**Comment by intact** [comment]
You can try somethink like this: https://gist.github.com/intact/21784f84566275d2bb53

**Comment by steven7851** [comment]
Thank for your advice.
I try to get roomID for api and it work well.
