### ISSUE TITLE
All Livestream.com links download not working

### ISSUE THREAD

**Issue by poochiteap** [chrippa/livestreamer#1110]
C:\Users\OWNER\Desktop>livestreamer http://livestream.com/accounts/10205943/events/3429501 best -v -o "ND-.mp4" -O --retry-streams 1 --retry-open 86400
[cli][info] Found matching plugin livestream for URL http://livestream.com/accounts/10205943/events/3429501
[cli][info] Available streams: 270p (worst), 270p_hls, 432p (best), 432p_hls
[cli][info] Opening stream: 432p (akamaihd)
[cli][error] Could not open stream: Unable to open URL: http://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf ((<requests.packages.urllib3.connectionpool.HTTPConnectionPool object at 0x0229DD70>, 'Connection to viewerplus.livestream.com timed out. (connect timeout=20.0)'))
[cli][error] Could not open stream: Unable to open URL: http://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf ((<requests.packages.urllib3.connectionpool.HTTPConnectionPool object at 0x0229DD70>, 'Connection to viewerplus.livestream.com timed out. (connect timeout=20.0)'))

It is the same for other Livestream links as well when i checked. When I tried again it was:

C:\Users\OWNER\Desktop>livestreamer http://livestream.com/accounts/10205943/events/3429501 best -v -o "ND - 2015-10-28- 3-37 - 46-15-.mp4" -O --retry-streams 1 --retry-open 86400
[cli][info] Found matching plugin livestream for URL http://livestream.com/accounts/10205943/events/3429501
[cli][info] Available streams: 270p (worst), 270p_hls, 432p (best), 432p_hls
[cli][info] Opening stream: 432p (akamaihd)
[cli][error] Could not open stream: onEdge error: Authentication failed
[cli][error] Could not open stream: onEdge error: Authentication failed
[cli][error] Could not open stream: onEdge error: Authentication failed
[cli][error] Could not open stream: onEdge error: Authentication failed
[cli][error] Could not open stream: onEdge error: Authentication failed
[cli][error] Could not open stream: Unable to open URL: http://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf ((<requests.packages.urllib3.connectionpool.HTTPConnectionPool object at 0x020EC170>, 'Connection to viewerplus.livestream.com timed out. (connect timeout=20.0)'))
[cli][error] Could not open stream: Unable to open URL: http://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf ((<requests.packages.urllib3.connectionpool.HTTPConnectionPool object at 0x020EC170>, 'Connection to viewerplus.livestream.com timed out. (connect timeout=20.0)'))

Any help?

**Comment by poochiteap** [comment]
Okay it started working again!

**Comment by lutoma** [comment]
Having the same issue sporadically. I think the livestreamer.com links only work if you've visited their homepage in the last few minutes.
