### ISSUE TITLE
10.11.2 beta OS X No video but has audio.

### ISSUE THREAD

**Issue by teaadmin** [chrippa/livestreamer#1132]
on latest nightly 1.12.2

Trying to pull any stream from twitch using any quality and getting zero video but still has audio.

Any possible work around on this? Willing to get any logs to help figure out why it's doing this.

**Comment by skulblakka** [comment]
What player are you using? And have you tried using a different one?

**Comment by teaadmin** [comment]
I'm on VLC 3.0 from nightlies.
