### ISSUE TITLE
streamupcom.py plugin no longer functioning

### ISSUE THREAD

**Issue by coburnsven** [chrippa/livestreamer#1138]
Can anyone validate?  I've never used streamup.com before.

livestreamer https://streamup.com/nbanhl1 best
[cli][info] Found matching plugin streamupcom for url https://streamup.comnbanhl1
error: Unable to validate response text: Unable to validate union 'vars': Key 'owner' not found in {}

**Comment by 0880** [comment]
You can use the updated plugin, which was provided by [intact](https://github.com/intact) some days ago ([#1124] (https://github.com/chrippa/livestreamer/pull/1124)).

````
livestreamer "https://streamup.com/southpark" best
[cli][info] Found matching plugin streamupcom for URL https://streamup.com/southpark
[cli][info] Available streams: 720p (worst, best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: "C:\Program Files (x86)\Video\MPC-HC\mpc-hc.exe"
````

**Comment by coburnsven** [comment]
You are correct - thank you for the assist.

**Comment by cmdub** [comment]
unless i'm mistaken but it would seem intact's current plugin no longer works

**Comment by tp0** [comment]
No solution right now?

**Comment by gverm** [comment]
@cmdub @tp0 You can find a new version of the streamup plugin here: https://github.com/chrippa/livestreamer/pull/1206
