### ISSUE TITLE
pyCrypto not installed -- but it is

### ISSUE THREAD

**Issue by chovy** [chrippa/livestreamer#1143]
I get this error when running livestreamer:

```
[cli][error] Could not open stream: Need pyCrypto installed to decrypt this stream
```

I installed pycrypto with no problems using `sudo -EH pip install pycrypto`

but livestreamer still can't find it.

on Mac/El capitan with python 2.7.1

**Comment by chovy** [comment]
fixed with this command:

`sudo easy_install -U livestreamer`

**Comment by khimbhai** [comment]
Thanks @chovy this helped me as well.
