### ISSUE TITLE
Livestreamer suddenly stopped working!

### ISSUE THREAD

**Issue by artalinus** [chrippa/livestreamer#1149]
Any link i try to open with livestreamer i get this error.
```
livestreamer http://www.twitch.tv/beyondthesummit high
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/beyondthesummit
error: Unable to open URL: http://usher.twitch.tv/api/channel/hls/beyondthesummit.m3u8?player=twitchweb&token=%7B%22user_id%22%3Anull%2C%22channel%22%3A%22beyondthesummit%22%2C%22expires%22%3A1449777245%2C%22chansub%22%3A%7B%22view_until%22%3A1924905600%2C%22restricted_bitrates%22%3A%5B%5D%7D%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22source_restricted%22%3Afalse%7D&sig=86a8d86ee98aedd71b7b218d36a0934a7279036c&allow_audio_only=true&allow_source=true&type=any&p=149938 (HTTPConnectionPool(host='          ', port=80): Max retries exceeded with url: http://usher.twitch.tv/api/channel/hls/beyondthesummit.m3u8?player=twitchweb&token=%7B%22user_id%22%3Anull%2C%22channel%22%3A%22beyondthesummit%22%2C%22expires%22%3A1449777245%2C%22chansub%22%3A%7B%22view_until%22%3A1924905600%2C%22restricted_bitrates%22%3A%5B%5D%7D%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22source_restricted%22%3Afalse%7D&sig=86a8d86ee98aedd71b7b218d36a0934a7279036c&allow_audio_only=true&allow_source=true&type=any&p=149938 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x103231690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))))
```

```
livestreamer https://www.youtube.com/watch?v=fd761JVBmv4 720p
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=fd761JVBmv4
error: Unable to open URL: http://youtube.com/get_video_info (HTTPConnectionPool(host='          ', port=80): Max retries exceeded with url: http://youtube.com/get_video_info?el=player_embedded&video_id=fd761JVBmv4 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x104268290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))))

```

```
livestreamer http://www.azubu.tv/paingaming
[cli][info] Found matching plugin azubutv for URL http://www.azubu.tv/paingaming
error: Unable to open URL: http://www.azubu.tv/paingaming (HTTPConnectionPool(host='          ', port=80): Max retries exceeded with url: http://www.azubu.tv/paingaming (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x104265290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))))

```
Using livestreamer on a Mac OS X 10.11.2 with livestreamer version 1.12.2

**Comment by StarWolf3000** [comment]
Are you behind a proxy?

Because all plugins report the same problem, there seems to be an issue with your internet connection.

**Comment by artalinus** [comment]
No proxy i checked, i restored the system to an earlier backup and it seems to be fine now. I think problem was caused after i updated all the gems, brew packages and cleanedup all the previous ones.

**Comment by cirrusUK** [comment]
I have similar issue in past few days on 3 fully updated archlinux boxes 
 cirrus@blade  ~  livestreamer -p mpv https://www.filmon.com/tv/cbs-reality1 low

Traceback (most recent call last):
  File "/usr/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/livestreamer_cli/main.py", line 3, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 60, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 14, in <module>
    from . import sessions
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 27, in <module>
    from .adapters import HTTPAdapter
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 28, in <module>
    from .packages.urllib3.exceptions import NewConnectionError
ImportError: cannot import name 'NewConnectionError'
