### ISSUE TITLE
.m3u8-tunneling stopped working.

### ISSUE THREAD

**Issue by Ordval** [chrippa/livestreamer#1152]
**Edit**
After putting up the streams yesterday (below) they're useless today 13 dec. 
Maybe there's a connection.  Let's see about tomorrow.

*Comment*
These:  [http://adryanlist.x10.mx/nescafe.php?cm=3704]
[http://adryanlist.x10.mx/nescafe.php?canal=HistoryLA&cm=3704]
[http://adryanlist.x10.mx/nescafe.php?cm=4043]
[http://adryanlist.x10.mx/nescafe.php?canal=News12Connecticut.stream&cm=4043] 
opens in in VLC, and if not; by being forced, but as they produce .m3u8-streams (as you will see   through URL Helper or the like) they would work better through Livestreamer (not as heavy). 

The result could look something like: [http://lb.iptvserver.tv:8080/redirect/LiveEdge/News12Connecticut.stream/playlist.m3u8?token=465f4cf7ec9f6a06f1b2fc3e65030cab].
I've tried the possible three (or two) ways and also con-jointed with 
--player-continuous- --retry-streams 1 –retry-open 86400, is there anything else ?

[cli][error] Unable to open URL: http://adryanlist.x10.mx/nescafe.php?canal=Hist
oryLA&cm=3704 (403 Client Error: Forbidden)

Similar MRL's like [http://www.jdmsociety.net/ST/4043.m3u8] has produced the wished for 
.m3u8-stream, -s  result earlier through Livestreamer.
 
Have also put this on the ”Testing of .m3u8 streams. #673”-thread

**Comment by sbernsteinHBO** [comment]
The 403 error usually means that you need to pass a cookie or other request header to make the server believe that you are requesting it through normal means (i.e. a web browser).

**Comment by scottbernstein** [comment]
The 403 error (Forbidden) is a "permission denied" error usually indicating that you need to pass some additional headers with your request -- possibly a cookie or other request headers.  You can find out exactly which ones if you use Chrome or Firefox F12 Developer tools and then watch the network traffic as the original page loads.  If you can find the m3u8 request in there, you'll also see the headers that are passed along with it -- including cookies.
