### ISSUE TITLE
Unable to record streams from twitch with bash script. "No such file or directory" [Solved]

### ISSUE THREAD

**Issue by bmattlife** [chrippa/livestreamer#1154]
Edit: Solved it below
  I wrote a script to run in the background and record streams for me.

```Shell
dateString=$(date "+%a-%b-%d %I%M%p %Z")
printf "Record who?\n"
read target
while true; do
mkdir -m 700 -p ~/Desktop/Streams/${target}
livestreamer --retry-streams 30 -o "~/Desktop/Streams/${target}/${dateString}.m2ts" twitch.tv/${target} best
done
```

  This lets me enter a twitch user and it will attempt to connect every 30 seconds. once connected, it will record to a folder on my desktop after creating it. when the stream ends, it will automatically loop and wait for the stream to start again.
  However, I've been getting this error when trying to record

```
MacBook-Pro-2:~ bmatt$ /Users/bmatt/Desktop/Record\ Stream ; exit;
Record who?
cxuotaku
[cli][info] Found matching plugin twitch for URL twitch.tv/cxuotaku
[cli][info] Available streams: audio, source (worst, best)
[cli][info] Opening stream: source (hls)
error: Failed to open output: ~/Desktop/Streams/cxuotaku/Sat-Dec-12 0619PM CST.m2ts ([Errno 2] No such file or directory: '~/Desktop/Streams/cxuotaku/Sat-Dec-12 0619PM CST.m2ts')
```

I was under the impression that livestreamer would create the dir and file on its own? I even added in the mkdir and set read/write perms just in case something weird was happening and i cannot figure it out. Any help at all is greatly appreciated. 

P.S. Shell is Bash but if you want to test this script, it should work on any OS

**Comment by bmattlife** [comment]
Sigh.. 
Fixed it myself. Apparently using ~/Desktop does not work and I had to change the script to write to /Users/bmatt/Desktop. Updated script is below if you want to use it. note: added -f flag to livestreamer so if a stream is opened twice in the same minute, it will overwrite the old 30s file without asking

```Shell
dateString=$(date "+%a-%b-%d %I%M%p %Z")
printf "Record who?\n"
read target
while true; do
#mkdir -m 700 -p ~/Desktop/Streams/${target}
livestreamer --retry-streams 30 -f -o "/Users/bmatt/Desktop/Streams/${target}/${dateString}.m2ts" twitch.tv/${target} best
done
```

**Comment by charmander** [comment]
`~` isn’t expanded when quoted. Compare

```bash
echo ~
echo "~"
```

Use

```bash
path=~"/Desktop/Streams"
```

You should also be able to close the issue, rather than editing it to add “[Solved]”.
