### ISSUE TITLE
goodgame.ru plugin stopped working

### ISSUE THREAD

**Issue by psihkakihmalo** [chrippa/livestreamer#1158]
goodgame.ru plugin stopped working. All streams is not working. Please fix it.

**Comment by typae** [comment]
I confirm, streams from a goodgame don't work. It would be great, if you could correct this issue, or would tell us that it is necessary to do.

**Comment by flijloku** [comment]
Need change this:
https://github.com/Feverqwe/livestreamer/commit/f064f835cd076803bbbf1fb785d8844596ce7059
and this
https://github.com/chrippa/livestreamer/issues/1079
https://github.com/chrippa/livestreamer/commit/7f73960b18720fcfec3a746c5bbd442a2a05cf75
and it will be work!

Can also create bat files that do not use this plugin:
![goodgame](https://cloud.githubusercontent.com/assets/14862821/11884352/508bc318-a52a-11e5-92bd-132e8fc13e9e.JPG)

**Comment by psihkakihmalo** [comment]
flijloku, thank you for the files.
Please tell me how to find the desired file name ***.m3u8 for using with bat file?

**Comment by flijloku** [comment]
If simplistically
![222](https://cloud.githubusercontent.com/assets/14862821/11894493/a2251c8e-a588-11e5-8ced-d816dfd48d69.JPG)
Also possible to to use Internet Download Manager or Wireshark with filter http.request.uri contains "m3u8" 
![333](https://cloud.githubusercontent.com/assets/14862821/11894708/059f851e-a58a-11e5-907e-5f376538035b.JPG)

For Russian speaking read this:
http://forum.sc2tv.ru/threads/46848-%D0%A1%D0%BA%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D1%80%D0%B8%D0%BC%D0%BE%D0%B2-%D1%81-twitch-tv-justin-tv?p=2347253&viewfull=1#post2347253

**Comment by psihkakihmalo** [comment]
Thanks bro. 
But I don't understand how to use Internet Download Manager. IDM just downloads a useless *.html file from the goodgame page.

**Comment by flijloku** [comment]
Now the m3u8 playlist is issued if you are not logged in!
![444](https://cloud.githubusercontent.com/assets/14862821/11895498/493370dc-a590-11e5-8e91-ee223d7b5f5a.JPG)
![555](https://cloud.githubusercontent.com/assets/14862821/11895502/4d66c0a0-a590-11e5-88ad-4150fbac7f47.JPG)
![777](https://cloud.githubusercontent.com/assets/14862821/11895504/51ce4564-a590-11e5-8dad-d9b0b95384d2.JPG)

**Comment by psihkakihmalo** [comment]
Thank you! Everything is working. I just forgot about the floating panel IDM (6.25 Build 1).
You helped me greatly.
One more question: does it make sense to use this option with VLC: --file-caching <ms> --network-caching <ms>? Will it some an advantage?

**Comment by flijloku** [comment]
I think is possible try to increase --file-caching  if strem is buffering but not sure. I do not use it. Still have the opportunity to use a proxy.

**Comment by psihkakihmalo** [comment]
ok
