### ISSUE TITLE
SSLContext problem

### ISSUE THREAD

**Issue by CliffM1967** [chrippa/livestreamer#1181]
I've been trying to install/run LS on both OSX and Ubuntu -- but I run into ssl related problems.

Using version 1.12.2

I've done the installation using python2.7 inside a virtual-env on Ubuntu below, but when I run I get the following.  Am I missing an extra pyssl library or something ?

(lstr)root@li298-198:~/lstr# livestreamer --yes-run-as-root twitch.tv/day9tv best
[cli][info] Found matching plugin twitch for URL twitch.tv/day9tv
/root/lstr/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/root/lstr/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
error: No streams found on this URL: twitch.tv/day9tv

**Comment by skulblakka** [comment]
Take a look at #819. Maybe one of the solutions there works for you.

**Comment by CliffM1967** [comment]
That's great -- it was python 2.7.7 , upgrading to python 2.7.11 sorted things.
