### ISSUE TITLE
Vaughnlive.tv plugin cannot work 

### ISSUE THREAD

**Issue by c769214** [chrippa/livestreamer#1202]
Hi, I have tried the latest livestreamer version and the problem still occurs:

userpc@userpc-Sys:/tmp$ livestreamer http://vaughnlive.tv/newzviewz best
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/newzviewz
error: Unable to validate response text: Minimum length is 2 but value is 1
userpc@userpc-Sys:/tmp$ 

Thank you.

**Comment by tboss** [comment]
Tested myself and this issue was resolved in #898 (slight change in API), see also #897. Note that you have to grab the new version of the plugin manually (and place it in custom plugin folder, see "sideloading plugins"), unless you want to wait for a new release.

**Comment by c769214** [comment]
ok thanks... 

Just write down how do I solve this issue (maybe some people may take a took to see if it helps)

maybe I'm wrong ... but it still works and see
1. cd ~
2. cd livestreamer/src/livestreamer/plugins
3. sudo gedit vaughnlive.py
4. make changes in stated in issue #898 , then save
5. when run using the following command 

livestreamer --plugin-dirs /home/username/livestreamer/src/livestreamer/plugins "http://vaughnlive.tv/sherming8888" best

see if it helps.
