### ISSUE TITLE
not working for douyutv

### ISSUE THREAD

**Issue by ghost** [chrippa/livestreamer#1213]
livestreamer http://www.douyutv.com/99039

[cli][info] Found matching plugin douyutv for URL http://www.douyutv.com/99039
error: Unable to validate JSON: Unable to validate key 'data': u'\u63a5\u53e3\u5df2\u5173\u95ed' does not equal None or Type of u'\u63a5\u53e3\u5df2\u5173\u95ed' should be 'dict' but is 'unicode

OS:win7 64bit ,livestreamer version:1.12.2

i try to livestreamer twitch, it works, but douyutv not working

**Comment by rbong** [comment]
Tried with that channel. Every channel is working on Linux. I don't have Windows to check, but it sounds like it could be an encoding error.

**Comment by 0834dfbd2b** [comment]
sounds strange I have no problems with it but I may be useing an old version, if you try to search on it you can see multiple people have had the same problem in the past. #886 #891 #925 #938

**Comment by ghost** [comment]
@rbong 
same issue on ubuntu 14.04

sudo pip install livestreamer
livestreamer http://www.douyutv.com/10 best

[cli][info] Found matching plugin douyutv for URL http://www.douyutv.com/10
error: Unable to validate JSON: Unable to validate key 'data': u'\u63a5\u53e3\u5df2\u5173\u95ed' does not equal None or Type of u'\u63a5\u53e3\u5df2\u5173\u95ed' should be 'dict' but is 'unicode'

**Comment by intact** [comment]
@myskn You need a newer version of livestreamer

**Comment by ghost** [comment]
@intact 
you are right!
i used development version it works now!
