### ISSUE TITLE
error while tryign to stream from vaughnlive

### ISSUE THREAD

**Issue by simbesh** [chrippa/livestreamer#1219]
CMD copy paste:

C:\Users\Simon>livestreamer http://vaughnlive.tv/mark
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/mark
error: Unable to validate response text: Minimum length is 2 but value is 1

Thanks

**Comment by intact** [comment]
Your livestreamer is too old #897

**Comment by simbesh** [comment]
ah yea thanks.
For anyone else using the windows installer, you need to download the latest files and unzip \livestreamer-develop\src\livestreamer\plugins into %appdata%\roaming\livestreamer
