### ISSUE TITLE
Livestreamer not working [AZUBU]

### ISSUE THREAD

**Issue by BremerDuarte** [chrippa/livestreamer#1222]
I have the the plugin "azubu.py" but, in most azubu channels the livestreamer is not working in windows 10 x64.

> error message: "error: No streams found on this URL: azubu.tv/silviosantosdocs", but the streamer is online.

Solution?

**Comment by ekisu** [comment]
Can confirm. I'm running Gentoo Linux, and trying to open any livestream returns:

> [cli][info] Found matching plugin azubutv for URL http://azubu.tv/Drezzy
> error: No streams found on this URL: http://azubu.tv/Drezzy

I'm using livestreamer 1.12.2

**Comment by ghost** [comment]
They have switched to HTTP Live Streaming (HLS). This is not implemented yet. In the meantime you can try to access this streaming protocol directly:

```
livestreamer "hlsvariant://http://azubuhlsliveva-i.akamaihd.net/hls/live/222927/3361910549001-va1/video194674CHsilviosantosdocs/master.m3u8" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://azubuhlsliveva-i.akamaihd.net/hls/live/222927/3361910549001-va1/video194674CHsilviosantosdocs/master.m3u8
[cli][info] Available streams: 270p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
```

**Comment by BremerDuarte** [comment]
How i get the streaming protocol?

**Comment by joseantonnio** [comment]
Same here.

W10 + Livestreamer 1.12.2
`C:\Users\Junny>livestreamer http://azubu.tv/silviosantosdocs 720p`
`[cli][info] Found matching plugin azubutv for URL http://azubu.tv/silviosantosdocs`
`error: No streams found on this URL: http://azubu.tv/silviosantosdocs`

How do we get the streaming protocol @0880?

**Comment by ekisu** [comment]
@BremerDuarte @junnykx Open the stream on a supported browser (I've tried with Firefox + Flash), and open the Developer Console, go on the Network tab and search for a URL or a file ended in master.m3u8. Then add hlsvariant:// at the start of that URL.

**Comment by joseantonnio** [comment]
Thanks @ElegantMonkey! I'll use it while doesn't comes out a fix for Livestreamer...

**Comment by gverm** [comment]
EDIT: can confirm it's not working on nightly build

**Comment by raulin0** [comment]
I tried using this method but I still can't watch live on Azubu.tv/peronio.

**Comment by ghost** [comment]
@mfelipe94 

```
livestreamer "hlsvariant://http://azubuhlslivesp5-i.akamaihd.net/hls/live/223585/hls-saopaulo-5_2/video199807CHperonio/master.m3u8" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://azubuhlslivesp5-i.akamaihd.net/hls/live/223585/hls-saopaulo-5_2/video199807CHperonio/master.m3u8
[cli][info] Available streams: 270p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
```

**Comment by raulin0** [comment]
@0880 thank you so much

**Comment by joseantonnio** [comment]
Any build working? Will you give us something @chrippa??

**Comment by NeoFahrenheit** [comment]
I tried to do this (went to the console e copy that link [put hlsvariant:// in front of it too] ), but I always get the error "No stream found" or something.

It's for this stream: http://azubu.uol.com.br/Fleeur

Thanks.
Is the fix coming soon? :D

**Comment by ignarteaga** [comment]
Hello guys, i followed the steps @ElegantMonkey mentioned, but i couldn´t find any master.m3u8 url´s, the only similar ones were the azevinho.m3u8, which i tried to use in cmd, but it triggered the same "no stream in this url".

Anyway, the stream i was trying to acces was azubu.tv/gamesacademy, if anyone already found the master url for that stream and can link it to me, i would really appreciate it.

Thank you :D

**Comment by RaulCorreia** [comment]
I tried to do what ElegantMonkey said, but does not work, goes on to say that not found stream.
might need to update the azubu plugin, someone has news when will this happen?

**Comment by skulblakka** [comment]
@ignarteaga Here you go http://azubuhlslivesp12-i.akamaihd.net/hls/live/223613/hls-saopaulo-12_2/video206512CHGamesAcademy/master.m3u8

**Comment by ignarteaga** [comment]
@skulblakka thank you soooo much :D how did you found it? did you found it in the console?

**Comment by RaulCorreia** [comment]
@ignarteaga I also wanted this link, but I can only the azevinho.m3u8, @skulblakka how did you get the master?

**Comment by skulblakka** [comment]
I used the "Network" tab in the developer tools of Google Chrome and searched for "master.m3u8"

**Comment by RaulCorreia** [comment]
@skulblakka to me it does not appear.

**Comment by skulblakka** [comment]
I simply opened the network tab and entered "master.m3u8" into the filter field (make sure to reload the page after you went to the tab as by default it will only record everything that happened after you opened it)

**Comment by ignarteaga** [comment]
@RaulCorreia just a guess, but maybe it has to do with where in the world we access the site, i suppose by your username you are south american aswell as me, hence we see the "azevinho" url

**Comment by skulblakka** [comment]
The azevinho files contain the current parts of the stream (it will constantly reload while the stream is running). The master file however contains links to the different azevinho files for the different qualities. This way you can choose the quality when using the master file (You should actually be able to play the stream with the azevinho file (it will however only contain a single qualitiy; also you may use hls:// in front of the URL instead of hlsvariant://)

**Comment by RaulCorreia** [comment]
I found a solution, take the link azevinho. EX hls-saopaulo-3_2/video199860CHkami/2400/azevinho.m3u8
and changing the master erasing the end
hls-saopaulo-3_2/video199860CHkami/master.m3u8
worked here

**Comment by ThomasReedt** [comment]
Here is quick fix for azubutv. [azubutv.py](https://gist.github.com/ThomasReedt/eb55780c1c3d66c61d5b/raw/e4f543d72e3e64ce4dd37e795d3e1dfd6809e720/azubutv.py)
Just replace original plugin in livestreamer directory.

**Comment by joseantonnio** [comment]
Thanks @ThomasReedt! Working great.

`[cli][info] Found matching plugin azubutv for URL http://azubu.tv/kaue`
`[cli][info] Available streams: 1080p (best), 270p (worst), 360p, 480p, 720p`
`[cli][info] Opening stream: 1080p (hls)`
`[cli][info] Starting player: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'`

**Comment by NeoFahrenheit** [comment]
I don't know if it's only my internet getting worse, but my files contains contant shutter/freezes in resolutions that were OK before.

My streams freezes constantly at 480p, but in the past I could record 720p at no problem.
Is this new method using this hlsvariant:// is "heavier"?

I'm recording a stream on Twitch right now (saving to a file) at high quality and 250KB/s medium speed download.
I tested recording an Azubu stream on 480p and was about 500~600KB/s (my maximum speed).

I remember in the old days my Azubu recording never passing this 250~300KB/s (at 720p) speed mark.

Sorry for my english.

Edit: Forget to mention, but when I watch 480p streams trough Azubu website, rarely freezes.

Edit 2: After I close the prompt and the video file ended, I didn't saw the freezes anymore.
I'll try to record and watch with VLC. I was using PotPlayer. New reports later.

Edi 3: It was really a problem with PotPlayer, who apparently coulnd't handly the .ts file as livestreamer constantly recorded it. I was also able to get video files larger than 2GB with this method. :D

**Comment by joseantonnio** [comment]
Well, I need to revive this topic. Azubu stopped working again with Livestreamer =/

**Comment by gverm** [comment]
@junnykx it still works for me

**Comment by itonohito** [comment]
Doesn't work for me either. Using latest windows build of livestreamer - livestreamer-v1.12.2-120-gab80dbd.
Tried stream http://www.azubu.tv/ProdotaRU to be exact. Got the following:

[cli][info] Found matching plugin azubutv for URL http://www.azubu.tv/ProdotaRU
error: No streams found on this URL: http://www.azubu.tv/ProdotaRU

**Comment by ghost** [comment]
@itonohito

Try again with the updated plugin (provided by [ThomasReedt](https://github.com/ThomasReedt)).

[ThomasReedt](https://github.com/ThomasReedt) commented [on 22 Feb](https://github.com/chrippa/livestreamer/issues/1222#issuecomment-186943906)

> Here is quick fix for azubutv. [azubutv.py](https://gist.github.com/ThomasReedt/eb55780c1c3d66c61d5b/raw/e4f543d72e3e64ce4dd37e795d3e1dfd6809e720/azubutv.py)
> Just replace original plugin in livestreamer directory.

```
livestreamer "http://www.azubu.tv/axt" best
[cli][info] Found matching plugin azubutv for URL http://www.azubu.tv/axt
[cli][info] Available streams: 270p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
```

**Comment by itonohito** [comment]
Thanks! It works.
