### ISSUE TITLE
Livestreamer not working [douyutv]

### ISSUE THREAD

**Issue by henry99a** [chrippa/livestreamer#1224]
livestreamer-v1.12.2

\livestreamer-v1.12.2\livestreamer.exe www.douyutv.com/71771
[cli][info] Found matching plugin douyutv for URL www.douyutv.com/71771
error: Unable to validate JSON: Unable to validate key 'data': u'\u63a5\u53e3\u5
df2\u5173\u95ed' does not equal None or Type of u'\u63a5\u53e3\u5df2\u5173\u95ed
' should be 'dict' but is 'unicode'

**Comment by 0834dfbd2b** [comment]
can you try to install the nightly build? it works for me on 1.12.2

```
livestreamer.exe -V
livestreamer.exe 1.12.2
```

```
livestreamer.exe www.douyutv.com/71771 best 
[cli][info] Found matching plugin douyutv for URL www.douyutv.com/71771 
[cli][info] Available streams: middle2, middle (worst), source (best) 
[cli][info] Opening stream: source (http)
```

**Comment by henry99a** [comment]
thanks
