### ISSUE TITLE
Stable release / Dev Build(s)

### ISSUE THREAD

**Issue by ZatsuneSakurako** [chrippa/livestreamer#1228]
I was looking if Livestreamer support Beam, I found one commit saying that it seems to be done but the stable release is getting pretty old.

So, do you plan to make a new release? Or at least, it there a way to download more recent build of livestreamer? (travis website recently changed so I can't find if it's possible)

**Comment by Vangelis66** [comment]
Hello :-)

I am just another user; I happen to be on Windows, 
so I grabbed the latest nightly zip from: 

http://docs.livestreamer.io/install.html#windows-binaries => 
http://docs.livestreamer.io/install.html#nightly-build => 
[nightly-build](http://livestreamer-builds.s3.amazonaws.com/livestreamer-latest-win32.zip)

This was built from code snapshot git-ab80dbd, pushed on 02/02/2016.
There is indeed file "beam.py" inside the built-in plugins 
`livestreamer-latest-win32\livestreamer-v1.12.2-120-gab80dbd\livestreamer-1.12.2-py2.7.egg\livestreamer\plugins\`, so I guess Beam is supported (but not checked myself...).

If you've used the installer for the release version initially, 
I suppose you can update that by overwriting existing folders 
& files inside your installation directory with the contents of 
the nightly zip.

Hope I've helped!

Regards

**Comment by ZatsuneSakurako** [comment]
Yeah, but I ask it not only for myself that's why I was talking about a "release" or "easy" link
