### ISSUE TITLE
afreeca 'Connection aborted.', BadStatusLine

### ISSUE THREAD

**Issue by AleXoundOS** [chrippa/livestreamer#1246]
Oftentimes after "[cli][info] Opening stream: live (hls)" message livestreamer fails to load stream with:
`[cli][error] Could not open stream: Unable to open URL: http://chromecast.afreeca.gscdn.com/livestream-10/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.wR5Fmo4756ncqksOSR9y0dFkVporjNqhronw-l-24ueTVQ0N7mOVq0czZ2RlUSy7ByRbF2USFnqB-bxaQ5D3_hzrIZdDvZ_dyNoULlKX3Vk (('Connection aborted.', BadStatusLine("''",)))`
Then it exits.

After several sequential starts of livestreamer with same arguments it finally loads stream and plays fine. Usually not more than 3 attempts is needed. Maybe it's possible to tune livestreamer so that it retries this url connection several times internally by itself? So that user doesn't need to sequentially start the program manually until it works.

**Comment by scottbernstein-zz** [comment]
There are a whole bunch of command-line retry options that you can try.  Check here:
http://docs.livestreamer.io/cli.html#command-line-usage

**Comment by AleXoundOS** [comment]
Thank you. `--retry-open` seems to allow to tune the number of retries (default is 1).
