### ISSUE TITLE
error [cli][error] Could not open stream: Unable to open URL

### ISSUE THREAD

**Issue by danf22** [chrippa/livestreamer#1282]
can you help me  with this error.

sudo livestreamer http://livestream.com/accounts/15106628/events/4425181/player  best  --player "omxplayer --win '35 200 650 604' -o hdmi" --fifo --yes-run-as-rootsudo l

[cli][info] Found matching plugin livestream for URL http://livestream.com/accounts/15106628/events/4425181/player
[cli][info] Available streams: 270p (worst), 270p_hls, 432p (best), 432p_hls
[cli][info] Opening stream: 432p (akamaihd)
[cli][error] Could not open stream: Unable to open URL: http://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf (404 Client Error: Not Found)

Thank you

**Comment by intact** [comment]
#1272

**Comment by danf22** [comment]
Super men Thank you

**Comment by danf22** [comment]
can you help me with another thing, I can open a youtube live streaming.

root@raspberrypi:/home/pi# livestreamer https://youtu.be/H-6LVwddye4 best --player "omxplayer --win '35 200 650 604' -o hdmi" --fifo --yes-run-as-root
error: No plugin can handle URL: https://youtu.be/H-6LVwddye4

Thank you

**Comment by scottbernstein-zz** [comment]
The plugin doesn't recognize the "youtu.be" URL.  Click on this link to get the youtube.com URL and use that one.  It will work fine.

Date: Wed, 13 Apr 2016 10:58:48 -0700

**Comment by danf22** [comment]
Super men Thank you
