### ISSUE TITLE
Twitch: Unable to open URL (500 Server Error)

### ISSUE THREAD

**Issue by ear** [chrippa/livestreamer#1288]
I think twitch might have had some changes to its own video delivery service very recently. They might have broken the livestreamer plugin:

```
Found matching plugin twitch for URL https://secure.twitch.tv/magic/v/37885081
error: Unable to open URL: http://usher.twitch.tv/vod/37885081?allow_audio_only=true&p=595842&allow_source=true&nauthsig=0240bac301f35a8f24dbc83a7ba72744c74a6872&player=twitchweb&nauth=%7B%22user_id%22%3Anull%2C%22vod_id%22%3A37885081%2C%22expires%22%3A1460715486%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%7D&type=any (500 Server Error: Internal Server Error)
```

**Comment by ear** [comment]
Update: it does still work when using the non-`secure.` url like `https://www.twitch.tv/magic/v/37885081` instead. Even though it is also over https.

**Comment by skulblakka** [comment]
Both URLs work fine over here. 

> 500 Server Error: Internal Server Error

Might have been a temporal issue on twitch's side.

**Comment by ear** [comment]
Thanks for looking into it. I guess it was a fluke.
