### ISSUE TITLE
streamup.com is no longer working again

### ISSUE THREAD

**Issue by rbong** [chrippa/livestreamer#1293]
streamup has again changed its API.

```
pi@raspberrypi:~ $ livestreamer --version
livestreamer 1.12.
```

This is LTS Raspbian. This also occurs on OS X El Capitan and the latest Arch Linux.
I have begun plugin updates at [my fork](https://github.com/rbong/livestreamer/tree/streamup). The plugin now captures the stream, but it is broken up into multiple parts ends after about a minute.
I am working on remedying this, but perhaps someone else can do it faster.

**Comment by intact** [comment]
you can try #1206

**Comment by rbong** [comment]
I mistakenly thought that was merged and had stopped working- I had actually copied it in my previous build of livestreamer and it was overwritten. I will be more careful when reporting issues in the future.
