### ISSUE TITLE
Play TS File

### ISSUE THREAD

**Issue by ThaZMan** [chrippa/livestreamer#1296]
I saved a Youtube livestream to a file but cannot seem to play it. VLC may play the first frame but nothing else. The command I used was

`livestreamer "www.youtube.com/watch?v=asdadasdd" 480p --hls-live-edge 99999 -o Live.ts`

I've tried using the nightly build of VLC, 2.2.3 but it too does not work. Using VLC to convert it to another format produces a 1kb file.

How can I play the ts file?

**Comment by scottbernstein-zz** [comment]
This seems to come up every day:Any streams that you download from YouTube recently require nightly build of VLC 3.0 to be able to watch them.

Date: Wed, 20 Apr 2016 12:03:48 -0700
