### ISSUE TITLE
error 403 from all livestream.com streams

### ISSUE THREAD

**Issue by Qiasfah** [chrippa/livestreamer#1300]
I think this was working last week, but it seems to have broken since then.

All livestream.com streams appear to be reporting error 403 when connecting:

```
C:\>livestreamer http://livestream.com/accounts/11707815/events/4299357 480p_hls
[cli][info] Found matching plugin livestream for URL http://livestream.com/accounts/11707815/events/4299357
[cli][info] Available streams: 270p (worst), 270p_hls, 432p, 432p_hls, 480p (best), 480p_hls
[cli][info] Opening stream: 480p_hls (hls)
[cli][error] Could not open stream: Unable to open URL: http://livestream-f.akamaihd.net/i/11707815_1206159_b8464a07_1@320446/index_1756_av-p.m3u8?sd=10&dw=100&rebase=on (403 Client Error: Forbidden)
```

I poked around in livestream.py as it seems the generation URL may have changed, but haven't figured out much.

**Comment by scottbernstein-zz** [comment]
The plugin is broken for sure, but there are 2 easy ways that you can get to the same video content:For HLS:livestreamer "hlsvariant://http://api.new.livestream.com/accounts/11707815/events/4299357/broadcasts/120182004.m3u8?dw=100&hdnea=st=1461617836~exp=1461619636~acl=/i/11707815_1206159_b8464a07_1@320446/*~hmac=15cc1f33a9dfca6f857376560cf3a437a2781e1c77dfd482c8ab65a0a3ebd169" best
ORFor Akamai stream:livestreamer "akamaihd://http://livestream-f.akamaihd.net/11707815_1206159_b8464a07_1_1756@320446 swf=http://cdn.livestream.com/swf/LSPlayer.swf" best
Both will give the same result
NOTE  that the HLS link above will expire after a few minutes.  You need to refresh the page on livestream.com and view the source and look for the .m3u8 url.  The st=, exp=, and hmac= values will be different, but it will work
Date: Mon, 25 Apr 2016 11:54:17 -0700

**Comment by intact** [comment]
works for me:

```
livestreamer http://livestream.com/accounts/11707815/events/4299357 480p_hls
[cli][info] Found matching plugin livestream for URL http://livestream.com/accounts/11707815/events/4299357
[cli][info] Available streams: 270p_hls, 480p_hls, 432p_hls, 270p (worst), 432p, 480p (best)
[cli][info] Opening stream: 480p_hls (hls)
[cli][info] Starting player: ffplay
```

**Comment by Qiasfah** [comment]
Tried it again today, no changes, and it works now.

I guess whatever broke it yesterday was reverted/changed on the livestream website side.
