### ISSUE TITLE
Cannot seek video saved from hls stream

### ISSUE THREAD

**Issue by trippyhat** [chrippa/livestreamer#1312]
I am running with command:

```
livestreamer http://youtube.com/xxxx best -o test.mp4
```

However, since the stream never ends, I have to forcibly shutdown livestreamer when I'm done ( using  `CTRL-C`).

When I play the file back in mplayer/vlc, none of them have the correct time size (says 0:00), and I cannot seek to different sections of the video by clicking on the timebar (I can only fast forward or backward using keyboard arrow keys, but the time bar is still at 0:00).

I have tried this script:
https://gist.github.com/chrippa/7772802

But I got an error: 

```
Traceback (most recent call last):
  File "t.py", line 10, in <module>
    flv = flashmedia.FLV(infile)
  File "/Library/Python/2.7/site-packages/livestreamer/packages/flashmedia/flv.py", line 10, in __init__
    self.header = Header.deserialize(self.fd)
  File "/Library/Python/2.7/site-packages/livestreamer/packages/flashmedia/packet.py", line 19, in deserialize
    return cls._deserialize(fd, **kw)
  File "/Library/Python/2.7/site-packages/livestreamer/packages/flashmedia/tag.py", line 127, in _deserialize
    raise FLVError("Invalid FLV header")
livestreamer.packages.flashmedia.error.FLVError: Invalid FLV header
```

Is there a solution for this?

**Comment by scottbernstein-zz** [comment]
Yes, this comes up frequently.  To play any videos from YouTube currently, you need to download and use the "Daily Build" of version 3.0 of VLC Player.

Date: Wed, 4 May 2016 12:50:26 -0700

**Comment by trippyhat** [comment]
Thanks, using VLC 3.0 does resolve this issue. However, rather than be tied down to only using VLC, is there a way I can re-encode the video file in such a way that allows it to be played normally across different video players? ie, mplayer, totem.

**Comment by intact** [comment]
you can use something like: 

```
ffmpeg -i input.ts -codec copy output.ts
```

or

```
ffmpeg -i input.ts -codec copy -bsf:a aac_adtstoasc output.mp4
```
