### ISSUE TITLE
livestreamer is not supposed to be run as root. If you really must you can do it by passing --yes-run-as-root

### ISSUE THREAD

**Issue by selfler** [chrippa/livestreamer#1326]
That is a problem after install livestreamer.
Livestreamer is not supposed to be run as root. If you really must you can do it by passing --yes-run-as-root.
If anybody know how to install correct.Sorry for my poor English.Thank you very much!!

**Comment by StarWolf3000** [comment]
Well, ... why you need it to run as root? As the message says, there's actually no need to, and if you really need to, there's the option for.

Where was it installed to and which Linux system you're using?

**Comment by selfler** [comment]
Thanks.It works now.It installed well.Just dont run as root~~Thank you!
