### ISSUE TITLE
livecoding.tv is broken

### ISSUE THREAD

**Issue by vityas-off** [chrippa/livestreamer#1335]
Other stream services works fine, but livecoding.tv not working for me.
Error i get:
[cli][info] Found matching plugin livecodingtv for URL https://www.livecoding.tv/shmellyorc/
Traceback (most recent call last):
  File "/usr/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/lib/python3.5/site-packages/livestreamer_cli/main.py", line 897, in main
    handle_url()
  File "/usr/lib/python3.5/site-packages/livestreamer_cli/main.py", line 478, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/lib/python3.5/site-packages/livestreamer_cli/main.py", line 391, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python3.5/site-packages/livestreamer/plugin/plugin.py", line 313, in get_streams
    return self.streams(_args, *_kwargs)
  File "/usr/lib/python3.5/site-packages/livestreamer/plugin/plugin.py", line 227, in streams
    ostreams = self._get_streams()
  File "/usr/lib/python3.5/site-packages/livestreamer/plugins/livecodingtv.py", line 20, in _get_streams
    rtmp_url = match.group(0)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ghost** [comment]
Livecoding.tv plugin seems to work fine here.

```
livestreamer "https://www.livecoding.tv/shmellyorc/" best
[cli][info] Found matching plugin livecodingtv for URL https://www.livecoding.tv/shmellyorc/
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
```

```
Video: MPEG4 Video (H264) 1280x720 30fps 1024kbps [V: h264 main L4.1, yuv420p, 1280x720, 1024 kb/s]
Audio: AAC 48000Hz stereo 131kbps [A: aac lc, 48000 Hz, stereo, 131 kb/s]
```

Switching to HLS should also work.

```
livestreamer "hlsvariant://usmedia2.livecoding.tv:8080/hls/shmellyorc/index.m3u8?t=[...]" best
[cli][info] Found matching plugin stream for URL hlsvariant://usmedia2.livecoding.tv:8080/hls/shmellyorc/index.m3u8?t=[...]
[cli][info] Available streams: 1500k (worst, best)
[cli][info] Opening stream: 1500k (hls)
```

```
Video: MPEG4 Video (H264) 1280x720 30fps [V: h264 main L4.1, yuv420p, 1280x720]
Audio: AAC 48000Hz stereo 146kbps [A: aac lc, 48000 Hz, stereo, 146 kb/s]
```

**Comment by vityas-off** [comment]
Yep, it work just fine now with same livestreamer version oO

**Comment by AnarV** [comment]
How to fix it 
anar@demo-x:~$ livestreamer https://www.livecoding.tv/oliverthiele/
error: No plugin can handle URL: https://www.livecoding.tv/oliverthiele/
anar@demo-x:~$

**Comment by ghost** [comment]
@AnarV 

[Update](http://docs.livestreamer.io/install.html) your Livestreamer version or copy the Livecoding.tv [plugin](https://github.com/chrippa/livestreamer/blob/ab80dbd6560f6f9835865b2fc9f9c6015aee5658/src/livestreamer/plugins/livecodingtv.py) into your plugins directory.
