### ISSUE TITLE
Custom protocol

### ISSUE THREAD

**Issue by ktmn** [chrippa/livestreamer#1343]
I have no idea how it works, but is it possible to implement some sort of custom protocol (like other programs do), so that if you type into browser (for example) "livestreamer://www.twitch.tv/user" then it runs the "livestreamer www.twitch.tv/user source" command. 

If such a protocol was implemented, then creating an userscript or extension that adds button to video players that opens that video in VLC instead seems trivial.

**Comment by StarWolf3000** [comment]
This has nothing to do with livestreamer itself. It needs to be done on the user's side on the operating system level. There are some informations on MSDN on how to implement this in your own applications on Windows. If you're more confident with the Windows Registry, you can add a protocol handler on your own.

Depending on the browser you can also add custom protocols on the application level, means they will only work inside that browser. For example, a fictional `livestreamer://twitch.tv/channelname/source` can open the Twitch channel of channelname with source quality.
