### ISSUE TITLE
tga plugin for longzhu not working???

### ISSUE THREAD

**Issue by tenminute** [chrippa/livestreamer#1344]
No streams found. I'm trying a bunch of random streams but I get this... (I'm using the nightly build)

C:\WINDOWS\system32>livestreamer http://star.longzhu.com/qqgame best
[cli][info] Found matching plugin tga for URL http://star.longzhu.com/qqgame
error: No streams found on this URL: http://star.longzhu.com/qqgame

**Comment by ghost** [comment]
You can try to use the updated plugin (#1289) (provided by [intact](https://github.com/intact)) ...

```
livestreamer "http://star.longzhu.com/130415" best
[cli][info] Found matching plugin tga for URL http://star.longzhu.com/130415
[cli][info] Available streams: 720p_hls, 720p_http, 720p (worst, best)
[cli][info] Opening stream: 720p (rtmp)
```

```
Video: MPEG4 Video (H264) 1280x720 30fps 1536kbps [V: h264 high L3.1, yuv420p, 1280x720, 1536 kb/s]
Audio: AAC 48000Hz stereo 131kbps [A: aac lc, 48000 Hz, stereo, 131 kb/s]
```

... or use your browser developer tools to access all streams directly with Livestreamer.

```
livestreamer "httpstream://203.130.56.117/flv1.plu.cn/onlive/c00dd9bdc49e443aa7cd0a642f5357bd.flv?wsSecret=76aeb5338c2d76230f82d4fefbf8cdf6&wsTime=57564849&wshc_tag=0&wsts_tag=57564849&wsid_tag=6de42e82&wsiphost=ipdbm" best
[cli][info] Found matching plugin stream for URL httpstream://203.130.56.117/flv1.plu.cn/onlive/c00dd9bdc49e443aa7cd0a642f5357bd.flv?wsSecret=76aeb5338c2d76230f82d4fefbf8cdf6&wsTime=57564849&wshc_tag=0&wsts_tag=57564849&wsid_tag=6de42e82&wsiphost=ipdbm
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
```

```
Video: MPEG4 Video (H264) 1280x720 30fps 1536kbps [V: h264 high L3.1, yuv420p, 1280x720, 1536 kb/s]
Audio: AAC 48000Hz stereo 131kbps [A: aac lc, 48000 Hz, stereo, 131 kb/s]
```

**Comment by tenminute** [comment]
Ahhh... stupid me, duh???

I came across that but didn't know exactly what it was or how to use it. I couldn't even figure out how to download until it now (still a noob to github/livestreamer). It took me a good hour but I figured it out.

THANKS!!!
