### ISSUE TITLE
ITV re-stream with ffmpeg

### ISSUE THREAD

**Issue by bezik46** [chrippa/livestreamer#1347]
Hoping to get an answer here, but I am not sure it is a bug in LS

Trying to re-stream UK ITV to local LAN with LS piped to ffmpeg

livestreamer -O "http://www.itv.com/hub/itv" best 2>NUL | ffmpeg -re -i - -sn -vcodec copy -acodec copy -f flv "rtmp://127.0.0.1/MonaClients/itv"

but only get an error

pipe:: Invalid data found when processing input

Same for BBC works perfectly fine.

**Comment by 10mins** [comment]
This is easier way:
`livestreamer  "http://www.itv.com/hub/itv" best --player-external-http`

http://livestreamer.tanuki.se/cli.html#cmdoption--player-external-http

**Comment by bezik46** [comment]
Excellent, thanks!
livestreamer "http://www.itv.com/hub/itv" best --player-external-http-port 59411

and then I can

ffmpeg -re -i http://127.0.0.1:59411 -sn -vcodec copy -acodec copy -f flv "rtmp://127.0.0.1/MonaClients/itv"
