### ISSUE TITLE
Livestreamer ignores --player-passthrough options, uses only hls

### ISSUE THREAD

**Issue by m5r** [chrippa/livestreamer#1368]
## Description

When passing a --player-passthrough option, the program ignores it and go for the hls stream.
### Expected / Actual behavior

Livestreamer should use whichever stream type I want him to use, given the stream type is available.

Screenshot : https://gyazo.com/a971e903b12de5178c4eeec94d7e4a54
### Environment details (operating system, etc.)

Windows 10 x64, mpv video player, installed Livestreamer 1.12.2 from the release binary.

**Comment by intact** [comment]
All live Twitch streams are HLS (only some VODs use HTTP transport).
