### ISSUE TITLE
Trying to generate a twitch oauth token with --twitch-oauth-authenticate leads to a 404 page

### ISSUE THREAD

**Issue by Quwertzuiopp** [chrippa/livestreamer#1385]
I was just trying to generate a twitch oauth token with --twitch-oauth-authenticate but it only leads to a 404 page on readthedocs, making it impossible to create the token. I allways get redirected [here](http://livestreamer.tanuki.se/en/develop/twitch_oauth.html#access_token=bdg80vs5akl44t97q0bagpuiab99j1&scope=user_read+user_subscriptions) by the url that livestreamer opens.

**Comment by skulblakka** [comment]
Duplicate of #1306 

Edit: Also your access token is visible in the URL you postet above. Might want to revoke the token in the twitch settings

**Comment by Quwertzuiopp** [comment]
Hmm, sorry. I actually searched for an existing issue but could not find it, it seems.
