### ISSUE TITLE
Ustream streams not loading in 720p despite python-librtmp being installed.

### ISSUE THREAD

**Issue by TheSneakySniper** [chrippa/livestreamer#1391]
I have this stream here:
http://www.ustream.tv/channel/kansai-hd-test 
I went on the journey of installing librmtp.
I thought it worked.
This is the installation message that I have assumed worked:
http://pastebin.com/sXhVze4C
After installing chrippa's librmtp package ( https://github.com/chrippa/python-librtmp )
It still hasn't given me the option for 720p. My system is running  Linux Mint 13 Maya (GNU/Linux 3.2.0-23-generic i686)

Everything is installed, although pip is running version 1.0
(HInt, i know this stream isn't 720p, but streams that are 720p only load in 240p.)

Here is what happens when I load the stream:

This is the first time I run the command (all the time)

`myserver@foobar livestreamer http://www.ustream.tv/channel/kansai-hd-test

[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/kansai-hd-test

[plugin.ustreamtv][error] Unable to fetch desktop streams: Unable to validate result: Unable to validate key 'stream': Unable to validate result: Unable to validate key 'streams': Unable to validate result: Type of ScriptDataReference(reference=7) should be 'dict' but is 'ScriptDataReference' or Type of ScriptDataReference(reference=7) should be 'list' but is 'ScriptDataReference' or [ScriptDataObject([(u'name', u'uhs_tcdn'), (u'url', u'http://uhs-live-default.ustream.tv/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'streams', [ScriptDataObject([(u'chunkTime', 5000.0), (u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1468045280', u'86c2f3f234'), (u'1468045270', u'4631f31ed4'), (u'1468045290', u'4f0e70c220')])), (u'offset', 0.0), (u'isTranscoded', False), (u'width', 1280.0), (u'bitrate', 1493.0), (u'chunkId', 1468045277.0), (u'streamName', u'streams/live_1_%_%.flv'), (u'height', 720.0), (u'videoCodec', u'H264')])]), (u'streamType', u'flv/segmented')]), ScriptDataObject([(u'name', u'uhs_akamai'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-akamai.ustream.tv/sjc/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'url', u'http://uhs-akamai.ustream.tv/sjc/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'streams', ScriptDataReference(reference=7))]), ScriptDataObject([(u'name', u'uhs_llnw'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-llnw.ustream.tv/qa/sjc/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'url', u'http://uhs-llnw.ustream.tv/qa/sjc/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'streams', ScriptDataReference(reference=7))])] does not equal 'offline'
error: No streams found on this URL: http://www.ustream.tv/channel/kansai-hd-test
`

It gives me No streams found.
When I repeat the command 2 seconds later:
`myserver@foobar livestreamer http://www.ustream.tv/channel/kansai-hd-test

[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/kansai-hd-test

[plugin.ustreamtv][error] Unable to fetch desktop streams: Unable to validate result: Unable to validate key 'stream': Unable to validate result: Unable to validate key 'streams': Unable to validate result: Type of ScriptDataReference(reference=7) should be 'dict' but is 'ScriptDataReference' or Type of ScriptDataReference(reference=7) should be 'list' but is 'ScriptDataReference' or [ScriptDataObject([(u'name', u'uhs_tcdn'), (u'url', u'http://uhs-live-default.ustream.tv/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'streams', [ScriptDataObject([(u'chunkTime', 5000.0), (u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1468045300', u'c4758a0951'), (u'1468045290', u'4f0e70c220'), (u'1468045310', u'11fd76ae12')])), (u'offset', 0.0), (u'isTranscoded', False), (u'width', 1280.0), (u'bitrate', 1494.0), (u'chunkId', 1468045293.0), (u'streamName', u'streams/live_1_%_%.flv'), (u'height', 720.0), (u'videoCodec', u'H264')]), ScriptDataObject([(u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1468045300', u'c4758a0951'), (u'1468045290', u'4f0e70c220'), (u'1468045310', u'11fd76ae12')])), (u'offset', 0.0), (u'description', u'240p'), (u'bitrate', 287.0), (u'preset', u'viewer_240p'), (u'chunkId', 1468045292.0), (u'streamName', u'streams/live_2_%_%.flv'), (u'chunkTime', 5000.0), (u'resolutionFromPreset', u'240p'), (u'isTranscoded', True), (u'width', 426.0), (u'height', 240.0), (u'videoCodec', u'H264')])]), (u'streamType', u'flv/segmented')]), ScriptDataObject([(u'name', u'uhs_akamai'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-akamai.ustream.tv/sjc/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'url', u'http://uhs-akamai.ustream.tv/sjc/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'streams', ScriptDataReference(reference=7))]), ScriptDataObject([(u'name', u'uhs_llnw'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-llnw.ustream.tv/qa/sjc/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'url', u'http://uhs-llnw.ustream.tv/qa/sjc/sjc-uhs93/streams/uumf/ustreamVideo/19054868/1468023689863/'), (u'streams', ScriptDataReference(reference=7))])] does not equal 'offline'
Available streams: mobile_240p (worst, best)
`
What is the issue here? Is this not supported by 32 bit systems?

**Comment by L2501** [comment]
works with https://github.com/chrippa/livestreamer/pull/1278

**Comment by TheSneakySniper** [comment]
Well, that doesn't solve my issue, does it?

**Comment by TheSneakySniper** [comment]
That really sucks. I have no idea why this issue is happening.
