### ISSUE TITLE
Twitch VOD playback

### ISSUE THREAD

**Issue by Leseratte10** [chrippa/livestreamer#1392]
I'm using livestreamer to view twitch.tv livestreams with VLC (because twitch still can't get an HTML5 player to work) and everything works fine. 

However when I want to watch a VOD / a recorded stream from Twitch (http://twitch.tv/streamname/v/1234567) using livestreamer, VLC does not allow me to pause / resume / or skip parts of the stream - it behaves as if it was a "stream" and not a video. 

Is this because it's not supported by livestreamer? Is it not supported by VLC and can you recommend another video player?

**Comment by skulblakka** [comment]
Seeking in HLS Streams is currently not supported. Take a look at #711 for possible workarounds.

**Comment by Leseratte10** [comment]
Thanks, `--player-passthrough=hls` works, I can now pause the stream and seek. 

VLC does neither show the total time of the VOD nor the current time, but that is acceptable.
