### ISSUE TITLE
AttributeError: 'module' object has no attribute 'streams'

### ISSUE THREAD

**Issue by aar10n** [chrippa/livestreamer#1406]
I followed from the API guide and I seem to get this error EVERY TIME!

AttributeError: 'module' object has no attribute 'streams'

Using this:

```
import livestreamer
livestreamer.streams("http://www.twitch.tv/stewie2k")
```

**Comment by intact** [comment]
Works for me:

```
Python 3.4.3 (default, Jan 12 2016, 00:48:55) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import livestreamer
>>> livestreamer.streams("http://www.twitch.tv/stewie2k")
{}
```

**Comment by aar10n** [comment]
im using Python 2.7

**Comment by aar10n** [comment]
Nvm I managed to fix it

**Comment by anil-bhan** [comment]
Hi Team, 
Trying to run this file in trex0console, facing below error:

trex>start -f astf/tcp_param_change.py 

start - 
Error loading profile 'astf/tcp_param_change.py'


Python Traceback follows:

  File "/opt/trex/v3.02/automation/trex_control_plane/interactive/trex/stl/trex_stl_streams.py", line 1124, in get_module_tunables
    unc = module.register().get_streams
AttributeError: 'Prof1' object has no attribute 'get_streams'

**Comment by sima111b** [comment]
> Nvm I managed to fix it

Hi,
I am facing the same issue and get the same error.
"AttributeError: 'DinoVisionTransformer' object has no attribute '_streams'"
Could you please advise me how to fix it?

**Comment by anil-bhan** [comment]
@sima111b 
when you put a command to acquire ports using yaml
use ./t-rex-64 -i --astf --cfg /etc/xyz.yaml (if l7 traffic/pcaps)
use ./t-rex-64 -i  --stl  --cfg /etc/xyz.yaml  (if l3 traffic)

if using  trex at 2 different locations for l7
at server"
./t-rex-64 -i --astf --cfg /etc /xyz.yaml --astf-server-only
at client
./t-rex-64 -i -aastf --cfg /etc/xyz.yaml --astf-client-mask 0x1
