### ISSUE TITLE
Ustream "no streams found on this URL" previously working

### ISSUE THREAD

**Issue by highflux7** [chrippa/livestreamer#1415]
Until a few days ago (20 July 2016),  http://www.ustream.tv/channel/duval-street and http://www.ustream.tv/channel/willie-t-s-live worked fine, albeit sometimes having to retry the initial startup a couple of times until it would recognize the a valid error-free stream and launch vlc.

Now, only the following error:

$ livestreamer http://www.ustream.tv/channel/duval-street
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/duval-street
[plugin.ustreamtv][error] Unable to fetch desktop streams: Unable to validate result: Unable to validate key 'stream': Unable to validate result: Unable to validate key 'streams': Unable to validate result: Type of ScriptDataReference(reference=7) should be 'dict' but is 'ScriptDataReference' or Type of ScriptDataReference(reference=7) should be 'list' but is 'ScriptDataReference' or [ScriptDataObject([(u'name', u'uhs_tcdn'), (u'url', u'http://uhs-live-default.ustream.tv/sjc-uhs22/streams/uumf/ustreamVideo/9652368/1469356825248/'), (u'streams', [ScriptDataObject([(u'chunkTime', 5000.0), (u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1469365090', u'7e20f15766'), (u'1469365070', u'5a6eb7144e'), (u'1469365080', u'9981f6886f')])), (u'offset', 0.0), (u'isTranscoded', False), (u'width', 432.0), (u'bitrate', 521.0), (u'chunkId', 1469365075.0), (u'streamName', u'streams/live_1_%_%.flv'), (u'height', 240.0), (u'videoCodec', u'H264')])]), (u'streamType', u'flv/segmented')]), ScriptDataObject([(u'name', u'uhs_akamai'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-akamai.ustream.tv/sjc/sjc-uhs22/streams/uumf/ustreamVideo/9652368/1469356825248/'), (u'url', u'http://uhs-akamai.ustream.tv/sjc/sjc-uhs22/streams/uumf/ustreamVideo/9652368/1469356825248/'), (u'streams', ScriptDataReference(reference=7))]), ScriptDataObject([(u'name', u'uhs_llnw'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-llnw.ustream.tv/a/sjc/sjc-uhs22/streams/uumf/ustreamVideo/9652368/1469356825248/'), (u'url', u'http://uhs-llnw.ustream.tv/a/sjc/sjc-uhs22/streams/uumf/ustreamVideo/9652368/1469356825248/'), (u'streams', ScriptDataReference(reference=7))])] does not equal 'offline'
error: No streams found on this URL: http://www.ustream.tv/channel/duval-street

Worked great until just a couple of days ago...
livestreamer v1.12.2 on ubuntu 14.04.4

**Comment by ghost** [comment]
See pull request: #1278 

```
livestreamer "http://www.ustream.tv/channel/duval-street" best
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/duval-street
[cli][info] Available streams: 240p+ (worst, best)
[cli][info] Opening stream: 240p+ (uhs)
```
