### ISSUE TITLE
Vaughnlive "validate response text" error

### ISSUE THREAD

**Issue by Gotanius** [chrippa/livestreamer#1423]
Hi, 
I'm getting: "error: Unable to validate response text: Minimum length is 3 but value is 1".
I'm using the latest nightly livestreamer-v1.12.2-120-gab80dbd on windows with the vaughnlive plugin from @intact @ https://github.com/intact/livestreamer/blob/3cba09f0c286bf7d6a04333733661a96a29313c0/src/livestreamer/plugins/vaughnlive.py

**Comment by intact** [comment]
works for me:

```
livestreamer http://vaughnlive.tv/newzviewz
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/newzviewz
Available streams: live (best, worst)
```

**Comment by Gotanius** [comment]
`livestreamer http://vaughnlive.tv/Sherming777
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/Sherming777
error: Unable to validate response text: Minimum length is 3 but value is 1`

Hmm it seems to work for me with newzviewz. Any idea why it's not working with Sherming777 or Sherming3333 ?

**Comment by intact** [comment]
@Gotanius use http://vaughnlive.tv/sherming777 for now (with small s)

**Comment by Gotanius** [comment]
Well... don't I feel like an idiot >.< 
Thanks for the tip :)
