### ISSUE TITLE
'Best' quality no longer works with newest Twitch quality format

### ISSUE THREAD

**Issue by gravyboat** [chrippa/livestreamer#1433]
For TI6 (http://www.dota2.com/international/overview/) Twitch has modified how their list of qualities are now listed, they are as follows: `1080p60, 144p30, 240p30, 360p30, 480p30, 540p30, 720p30, 720p60, audio`. This means that defaulting to `best` no longer works as it doesn't understand the new format of `1080p60`. I assume this is true for the other qualities, but I haven't tested them.

**Comment by intact** [comment]
maybe you can try #1429

**Comment by gravyboat** [comment]
Definitely feels like that should do it, thanks @intact, didn't catch that one when I searched.
