### ISSUE TITLE
No streams found on this URL

### ISSUE THREAD

**Issue by yannbertrand** [chrippa/livestreamer#1455]
```
 $ livestreamer twitch.tv/esl_csgo
 [cli][info] Found matching plugin twitch for URL twitch.tv/esl_csgo
 error: No streams found on this URL: twitch.tv/esl_csgo
```

I get this error for every Twitch url I've tried. Is there something particular that I missed? I'm using Mac OS.

**Comment by hobbldygoop** [comment]
Seems twitch now requires client_ids for all API calls otherwise they fail.
edit: you can still watch streams if you supply a valid --twitch-oauth-token token

**Comment by yannbertrand** [comment]
Oh okey!

Should I do a pull request to add this information in the install instructions?

Is there a way of storing this info to avoid typing `--twitch-oauth-token th3t0k3n` each time you launch it?

**Comment by skulblakka** [comment]
> Is there a way of storing this info to avoid typing --twitch-oauth-token th3t0k3n each time you launch it?

Just add `twitch-oauth-token=TOKEN` to your [config file](http://docs.livestreamer.io/cli.html#configuration-file).
