### ISSUE TITLE
Twitch Client-ID Requirement

### ISSUE THREAD

**Issue by ThrowAwayAccount023948029834** [chrippa/livestreamer#1462]
They finally implement the Client-ID Requirement? I'm getting this error now.

`livestreamer -p mpv twitch.tv/monstercat best
[cli][info] Found matching plugin twitch for URL twitch.tv/monstercat
error: Unable to open URL: https://api.twitch.tv/api/channels/monstercat/access_token.json (400 Client Error: Bad Request for url: https://api.twitch.tv/api/channels/monstercat/access_token.json?as3=t)`

**Comment by liz1rgin** [comment]
i'm opened stream now, no problem

**Comment by skulblakka** [comment]
Duplicate of #1456
