### ISSUE TITLE
picarto plugin is broken: [cli][error] No data returned from stream

### ISSUE THREAD

**Issue by klendrop** [chrippa/livestreamer#1468]
After recent updates by picarto, things seem to be broken (I verified that this stream was online at the time I wrote this comment):

```
livestreamer picarto.tv/DonCoyote best
[cli][info] Found matching plugin picarto for URL picarto.tv/DonCoyote
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] No data returned from stream
```

I tried [#1332](https://github.com/chrippa/livestreamer/pull/1332) as it was referenced in an [older issue](https://github.com/chrippa/livestreamer/issues/1419), however that does no longer work.
If anyone has a quick fix for this, I'd be very happy.
(btw. I'm new to this. Is there a way to find the newest version of a file in all forks? In case someone has already fixed it somewhere?)

**Comment by Swirt** [comment]
I've done a pull request #1469 that fixes the plugin after recent Picarto update.

**Comment by klendrop** [comment]
It works again for single streams. Thank you very much.
Streams that are part of a multi-stream appear to be still broken:

```
livestreamer picarto.tv/Brokenlynx21 best
[cli][info] Found matching plugin picarto for URL picarto.tv/Brokenlynx21
error: No streams found on this URL: picarto.tv/Brokenlynx21
```

**Comment by klendrop** [comment]
Apparently picarto did another update and multi-streams work now.
