### ISSUE TITLE
no plugin for picarto 

### ISSUE THREAD

**Issue by nazmifr** [chrippa/livestreamer#1474]
Hi,
I saw that there is an issue where the person is not able to get data back from a stream on picarto, I have a problem that might be related, I tried 
livestreamer picarto.tv/Rediamond
and got
error: No plugin can handle URL: picarto.tv/Rediamond

then I tried updating livestreamer from the version in the Debian repositories to the latest, and still, there is no plugin that can handle the stream.

Do you have any infos ?
Also I was wondering, what does it take/do you have documentation on how to write plugins for other services as I know some services that are not supported yet :'(

Thanks in advance

PS: I forgot to mention, I'm using debian 8 Jessie 64bits

**Comment by alchzh** [comment]
Maybe Jessie repos don't have the picarto???
it's pretty old though... check what version you have

**Comment by nazmifr** [comment]
Hi, 
thanks for your response, I thought I added some infos yesterday but apparently that wasn't posted so:
I found an issue:
https://github.com/chrippa/livestreamer/issues/803

so I formatted the URL the way he said to,
https://picarto.tv/live/channel.php?watch=<channel>

 now it's recognised but it doesn't find any stream:

[cli][info] Found matching plugin picarto for URL https://picarto.tv/live/channel.php?watch=ElliotLi
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
**[cli][error] No data returned from stream**

Like on this issue:
https://github.com/chrippa/livestreamer/issues/1468

I looked at the other issue but I can't find what I need to do, I tried updating livestreamer to it's latest version using python-pip but the problem is still there.

Does anyone have infos about that ?

**Comment by klendrop** [comment]
My solution in that other issue was to locate the picarto.py file and copy and paste the #1469 changes in. But as stated in that issue, only works for streams that aren't part of a multi-stream.

**Comment by nazmifr** [comment]
Thanks, well, single streams seem to be all I'll need anyway so it's perfect, I'll try asap (probably once I'll find the file)
