### ISSUE TITLE
Sound Lags on Twitch Streams over VLC

### ISSUE THREAD

**Issue by EpsilonAlpha** [chrippa/livestreamer#1479]
Hello every1,

i have the strange problem on twitchs streams: I open via Livestreamer in VLC then i have sound lags/audio outages which i can't explain. The Video Stream runs fine! I use Windows 10

Here is was i already tried:
- in the livestreamerrc i tried to use VLC with and without the option "--file-caching=5000"
- \- meaning: 
                player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" 
                                               and
                player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --file-caching=5000
- I tried to open the streams with and without the oauth Token of Twitch
- I tried watch the stream in lower qualities, including mobile quality (!)
- I usally open the stream over Chatty and manually over cmd

The Issue also appears on multiple streamers from different countries.
Needless to say that my ISP Connection has 100 Mbit/s in Downstream and 6 Mbit/s in Upstream so should be easy able to handle the Stream, also my Gaming PC should be able to handle the Stream Data with ease.

The Timeframe since the issue appeared i can't say that for just, but the last days for sure!

What informations do i need to provide else?

**Comment by skulblakka** [comment]
Have you tried using a different player? I had issues like this before with VLC and switched to mpv. Runs smooth ever since.

**Comment by EpsilonAlpha** [comment]
Worked for me thx, much more fluent! \o/

But a maybe stupid question? How do i adjust the volume inside the player? :/

**Comment by EpsilonAlpha** [comment]
Got it 9 and 0 ;)

**Comment by EpsilonAlpha** [comment]
Perfect solution!

**Comment by EpsilonAlpha** [comment]
Okay, switched from 32bit to 64bit Version of VLC, that fixed my problem
