### ISSUE TITLE
My working GUI for Livestreamer

### ISSUE THREAD

**Issue by Akandesh** [chrippa/livestreamer#1480]
I'm sorry for posting this in the issue section even though I do not have a issue but I believe that this can help multiple threads. 

I've been coding on this GUI for little over a year now and thought I could share it with you now since I think it's more useful now than ever. 
With my software you do not need to copy/paste a authentication key each time you launch a stream.
It has a favorites list so you wont have to copy anything! 
It looks like this: https://i.gyazo.com/36c0da645899530d66a95c5112118a77.png

Source: https://github.com/Akandesh/Livestreamer-GUI
Download: http://files.akandesh.com/Programs/Livestreamer.exe

Thanks!

**Comment by Akandesh** [comment]
Just found https://github.com/bastimeyer/livestreamer-twitch-gui lol, I would've abandoned this ages ago if I had found this earlier.

**Comment by LoadingMex** [comment]
nice i was just looking for that and didnt find anything
