### ISSUE TITLE
Plugin for Stream.me (already have stream url grabber)

### ISSUE THREAD

**Issue by gverm** [chrippa/livestreamer#1487]
Is there someone who can help me create a working plugin for this platform?
I made this script to get the hls stream link from the link given by the user: http://pastebin.com/cT5issHN
I'm not good enough with this stuff to create an actual plugin out of this, but I hope it helps somebody to make one.

**Comment by gverm** [comment]
this is now available in streamlink: https://github.com/streamlink/streamlink/pull/23/commits/aadfc7ab7122c2e74e9097d58bcaab55f3baf2a0

**Comment by intact** [comment]
you can try #1488
