### ISSUE TITLE
400 Client Error HELP!!!

### ISSUE THREAD

**Issue by srghost** [chrippa/livestreamer#1499]
Well, i've passed some days without using the computer and when i came back, tryied to watch any streams and none have worked.

I've been tryied to reinstall the Livestreamer and VLC Player but still not working, please i need some help.

![screenshot_2](https://cloud.githubusercontent.com/assets/22486000/18896642/ba4e2e1c-84f9-11e6-8850-9a1b78d690e6.jpg)

**Comment by srghost** [comment]
FOUND THE SOLUTION

**Comment by nickyhajal** [comment]
What was the solution?

**Comment by nickyhajal** [comment]
Solution is here: https://github.com/chrippa/livestreamer/issues/1481
