### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Chronophylos** [chrippa/livestreamer#1504]
Every time I try to open a twitch.tv stream I get a Bad Request

```
$ livestreamer twitch.tv/monstercat
[cli][info] Found matching plugin twitch for URL twitch.tv/monstercat
error: Unable to open URL: https://api.twitch.tv/api/channels/monstercat/access_token.json (400 Client Error: Bad Request)
```

other websites/plugins work without a problem

**Comment by TheWoodsy** [comment]
Same here. On Live Stream or VOD -  400 error

livestreamer 1.12.2 windows
livestreamer https://www.twitch.tv/thebloodraid/v/90190337 best --player-passthrough hls

[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/thebloodraid/v/90190337 error: Unable to open URL: https://api.twitch.tv/api/vods/90190337/access_token.json (400 Client Error: Bad Request)

> **Workaround:-**
> livestreamer --twitch-oauth-authenticate
> take access_token=xxxx from URL
> livestreamer https://www.twitch.tv/blah best --twitch-oauth-token xxxx

**Comment by javiercantero** [comment]
See #1478
