### ISSUE TITLE
Goodgame moved to the new version of the site.

### ISSUE THREAD

**Issue by flijloku** [chrippa/livestreamer#1513]
Goodgame moved to the new version of the site.But goodgame plugin still be works on "old.goodgame.ru". Save https://yadi.sk/i/7MSInb_1wbpQP and replace old plugin. And will waiting when it will be fixed.

**Comment by psihkakihmalo** [comment]
I very much hope that the plug-in for new goodgame coming soon... i want it... i need it... )

**Comment by ghost** [comment]
Could someone write extractor for youtube-dl?
