### ISSUE TITLE
tga plugin for longzhu not working... again???

### ISSUE THREAD

**Issue by tenminute** [chrippa/livestreamer#1519]
This was working last week, but all of a sudden I tried it today and it's not working. I'm using the plugin from intact here https://github.com/chrippa/livestreamer/pull/1289. I'm trying a bunch of random streams and I'm just getting this weird error. I also tried using the browser developer tools to access the streams, but I don't know exactly how to do it. Does anyone have a solution? Kind of desperate for this to work... I use it everyday basically.

This is the error I get...

C:\WINDOWS\system32>livestreamer http://star.longzhu.com/158299?from=challcontent best
[cli][info] Found matching plugin tga for URL http://star.longzhu.com/158299?from=challcontent
error: Unable to validate JSON: Unable to validate key 'data': {u'preview_auto': True, u'preview2': u'http://img2.plures.net/live/screenshots/1558132/04e3/78ee/fc4c/ef45/6f80/f2df/9aa0/8e98_1476772959.jpg', u'game': [{u'Name': u'\u82f1\u96c4\u8054\u76df', u'tag': u'lol', u'Id': 4, u'name': u'\u82f1\u96c4\u8054\u76df', u'id': 4}], u'channel': {u'domain': u'158299', u'videos': 0, u'grade': 8, u'h5': u'http://star.longzhu.com/m/158299', u'tag': u'', u'broadcast_begin': 1476764946000L, u'id': 1558132, u'vid': 0, u'belle': 0, u'followers': 249, u'glamours': 211100, u'status': u'\u7535\u4e00\u5b9e\u529b\u8eba\u8d62\u7ec4~', u'_type': 1, u'weight': 0, u'_subtype': 0, u'flowers': 4238, u'live_source': 16, u'name': u'\u7c89\u6f20\u5c0f\u7a9d', u'url': u'http://star.longzhu.com/158299', u'stream_types': 12, u'avatar': u'http://img2.plures.net/a11a/405d/cb80/1345/2908/a837/fd5e/3af8.jpg', u'broadcast_duration': 8335}, u'preview': u'http://img2.plures.net/live/screenshots/1558132/04e3/78ee/fc4c/ef45/6f80/f2df/9aa0/8e98_1476772959.jpg', u'viewers': u'312'} does not equal None or Unable to validate key 'channel': {u'domain': u'158299', u'videos': 0, u'grade': 8, u'h5': u'http://star.longzhu.com/m/158299', u'tag': u'', u'broadcast_begin': 1476764946000L, u'id': 1558132, u'vid': 0, u'belle': 0, u'followers': 249, u'glamours': 211100, u'status': u'\u7535\u4e00\u5b9e\u529b\u8eba\u8d62\u7ec4~', u'_type': 1, u'weight': 0, u'_subtype': 0, u'flowers': 4238, u'live_source': 16, u'name': u'\u7c89\u6f20\u5c0f\u7a9d', u'url': u'http://star.longzhu.com/158299', u'stream_types': 12, u'avatar': u'http://img2.plures.net/a11a/405d/cb80/1345/2908/a837/fd5e/3af8.jpg', u'broadcast_duration': 8335} does not equal None or Unable to validate key 'id': Type of 1558132 should be 'basestring' but is 'int'

This is my attempt using the developer tools...

C:\WINDOWS\system32>livestreamer httpstream://153.37.232.178/flvtx.plu.cn/onlive/92d04fb8f4834dee9770b773e7bc847c.flv?mkey=5805e42cd2ec3fb4&f=7625&c=0&txSecret=e14688dae7ef95798dcb8a4d81a856d5&txTime=5805c534&p=.flv best
[cli][info] Found matching plugin stream for URL httpstream://153.37.232.178/flvtx.plu.cn/onlive/92d04fb8f4834dee9770b773e7bc847c.flv?mkey=5805e42cd2ec3fb4
Available streams: live (worst, best)
'f' is not recognized as an internal or external command,
operable program or batch file.
'c' is not recognized as an internal or external command,
operable program or batch file.
'txSecret' is not recognized as an internal or external command,
operable program or batch file.
'txTime' is not recognized as an internal or external command,
operable program or batch file.
'p' is not recognized as an internal or external command,
operable program or batch file.

**Comment by intact** [comment]
Try new version https://github.com/intact/livestreamer/blob/fix-tga/src/livestreamer/plugins/tga.py

**Comment by tenminute** [comment]
Awesome, man! You rock!
