### ISSUE TITLE
trying to download a twitch vod, but I'm getting an "unrecognized arguments" error

### ISSUE THREAD

**Issue by darthblumer** [chrippa/livestreamer#1526]
I've been using this format

livestreamer --twitch-auth-token (token) -o D:\folder\filename.mp4 --hls-segment-threads 4 VODURL best

**Comment by darthblumer** [comment]
I'm using Mac OSX and I have VLC installed. I'll show an image if that helps

**Comment by flijloku** [comment]
maybe "--twitch-oauth-token"?Or try replace plugin (https://github.com/chrippa/livestreamer/issues/1490#issuecomment-248632748) and then I think this parameter is not needed.

**Comment by intact** [comment]
> I'm using Mac OSX and I have VLC installed.

this type of path is for Windows only:

> D:\folder\filename.mp4

for OSX you can use something like /Users/username/Documents/filename.mp4

**Comment by darthblumer** [comment]
Hey, thanks so much. I think the problem the path I was using and also the "oauth." Pretty dumb mistakes lol. So you both helped. Seems to be downloading now. Thanks again.
