### ISSUE TITLE
(afreeca) Has there ever been a fix for 19+ hls streams?

### ISSUE THREAD

**Issue by tenminute** [chrippa/livestreamer#1529]
Sorry for the TL;DR, but...

Not that hls streams don't work, or 19+ hls streams completely don't work... just wondering if anyone is able to access the streams AFTER they switch into 19+. The only way to access them is for the stream to be loaded PRIOR to them switching. Rtmp streams, on the other hand, you can access whenever you want. 

Didn't really bother me much since the few I really like to watch are rtmp streams, and the ones with hls rarely go into 19+ anyways. But... the rtmp stream I watch the most just re-did their whole station/channel recently and it now streams hls. I have to be on time for the stream now, just in case (I already missed a stream because of this). Totally pissed me off! LOL? Not really...

But have people been able to access them? Or is there/was there ever an updated plugin? It'd be awesome if someone can lead me to it.

Also because of this, I've just came across the new "streamlink" and youtube-dl. Anyone experienced with the afreeca plugins for them? And how well do they work (also meaning, if they work with the 19+ hls streams)? Are all the plugins for streamlink updated and working? Kind of sucks that livestreamer is officially abandoned now. Just gonna have to spend the next few days being a noob and trial and error with the two alternatives if nothing's updated.

Edit: Also, I have a backup folder named "7.1.2016 plugins" so those are the latest plugins I have (totally can't even find where I got it from on here) and I'm on Windows 10 if it matters.

**Comment by Serkora** [comment]
Are you sure your channels don't broadcast in rtmp? It seems that rtmp info link is incorrect in the plugin, change line 10 here https://github.com/chrippa/livestreamer/blob/develop/src/livestreamer/plugins/afreeca.py#L10 (or your version of the plugin) to this —
```
    "rtmp": "http://resourcemanager.afreeca.tv:9090/broad_stream_assign.html",
```
Works fine even for the adult category (which I don't really get — a bunch of people either playing cards/lottery or just drinking and eating)

As for the hls:
1. You might want to contact the person responsible for http://d-c.kr/, as he manages to retreive urls for 19+ vods, might be able to help. 
2. You can still get and record the hls key in advance and reuse it later for that broadcast after it turns 19+.

**Comment by nOLanSea** [comment]
I have same line in afreecatv.py as this https://github.com/chrippa/livestreamer/blob/develop/src/livestreamer/plugins/afreeca.py#L10
But 19+ streams doesn't work, says: "no streams found on this url"

**Comment by Serkora** [comment]
That's an incorrect address, change it to the one I provided above: `http://resourcemanager.afreeca.tv:9090/broad_stream_assign.html`

**Comment by nOLanSea** [comment]
So, now rmtp and hls are same?
`http://resourcemanager.afreeca.tv:9090/broad_stream_assign.html`

**Comment by Serkora** [comment]
Yep, apparently so. That actually makes some sense as otherwise the "broadcast_type" parameter was kind of useless.

**Comment by tenminute** [comment]
@Serkora Awesome, man... thanks! I stopped checking this because there were no replies. Wished I would've checked back sooner. Only some channels were showing rtmp available streams; the rest were only showing hls. It works now (the plugin for Streamlink isn't even updated).

BUT... after testing, before opening the stream, SOMETIMES cmd would just load for a while and rtmpdump.exe would "stop working" and crash. And as for recording rtmp streams, sometimes it'll record fine and sometimes there would only be audio with no video/messed up video... or it would crash the player (testing VLC and Potplayer with same results). I think for now, I'm just going to keep Livestreamer the way I had it and Streamlink with the changed address.

And as for http://d-c.kr/, I'm assuming the guy would only reply to Koreans/Korean speakers(?). Are you guys having issues with that site right now? It was improved (beta) and redirected about two weeks ago and then this past week it's been unavailable.

**Comment by nOLanSea** [comment]
Serkora, I did as you said but 19+ streams no work.
http://pix.my/iZDHz2
http://pix.my/JVzhmp

**Comment by Serkora** [comment]
@nOLanSea 
Are you sure the correct plugin is being used? livestreamer had several afreeca ones, total mess. It works fine for me (some random 19+ stream, jaedong23 is public right now). You can try manually opening the resourcemanager url in the browser and see if the link is there (it must be) and then use it with the livestreamer just to be sure the stream loads.

**Comment by nOLanSea** [comment]
@**Serkora**
I edited plugin as you said. Look this is my plugins folder https://www.dropbox.com/s/688irs0aa5s38c2/plugins_nolansea.zip?dl=0

**Comment by Serkora** [comment]
@nOLanSea 
Ok, it's because of this:
```
broadcast = channel["BROAD_INFOS"][0]["list"][0]["nBroadNo"]
if not broadcast:
    return
```
19+ streams (at least) do not return broadcast number and your plugin just exists. 

Workaround is to get the broadcast number from the web-page. You can use my version or pick only the necessary things from it (it's not polished, has some `print`s here and there, duplicated code etc) and edit yours — 
[afreecatv_serkora.zip](https://github.com/chrippa/livestreamer/files/728755/afreecatv_serkora.zip)

**Comment by nOLanSea** [comment]
**@Serkora**
I just replaced your afreecatv.py and got the next error
http://pix.my/jKpHBm

**Comment by Serkora** [comment]
You must be using an obsolete version of python (2.X) then.
Remove `import urllib.parse as parse` (line 7) and replace `import urllib.request as request` with `import urllib2 as request`.
This should make it work on python2, but not an elegant solution, breaks compatibility with python3 etc.

A proper way would've probably been to implement the get_broadcast_id using livestreamer's `http` module, but who cares.

**Comment by nOLanSea** [comment]
Done.
Getting this http://pix.my/XM7IRH

**Comment by Serkora** [comment]
@nOLanSea 
well, there's something wrong with the channel info acquisition, returns zero bytes. Too lazy to find the new correct method, so for now you can just remove lines 114-118 and it should work. Invalid usernames will cause errors elsewhere, so this check wasn't even that important, just a pretty (and uninformative) way to say that the channel probably does not exist.

**Comment by Serkora** [comment]
Found the reason — channel info POST requires a correct Referer header, so when trying to run the stream by calling `livestreamer afreeca.tv/username`, the Referer url is not correct.
Change line 65 of my plugin (https://github.com/chrippa/livestreamer/blob/develop/src/livestreamer/plugins/afreeca.py#L61) to this:
```
"Referer": "http://www.afreecatv.com/%s" % username
```

**Comment by nOLanSea** [comment]
Nothing works.
I have to back to my afreeca.py plugin...
