### ISSUE TITLE
400 client error: bad request

### ISSUE THREAD

**Issue by Lucifirius** [chrippa/livestreamer#1530]
`error: Unable to open URL: https://api.twitch.tv/api/channels/nl_kripp/access_token.json (400 Client Error: Bad Request)`

This error occurs when I try to watch a twitch stream, using the latest version of livestreamer.

**Comment by paskausks** [comment]
Can confirm. I have the same issue as well.

Also, `livestreamer --twitch-oauth-authenticate` opens the web browser, but upon receiving valid credentials, the login form shows "_Oops! We encountered an unexpected error logging you in. Please try again._"

**Comment by flijloku** [comment]
Try this: https://github.com/chrippa/livestreamer/issues/1490#issuecomment-248632748

**Comment by paskausks** [comment]
Yeah, that patch certainly solved it. Thanks!

**Comment by Lucifirius** [comment]
It worked! Thanks!
