### ISSUE TITLE
Unable view Twitch streams

### ISSUE THREAD

**Issue by rubickcz** [chrippa/livestreamer#1538]
When I try to play any Twitch live stream or video, livestreamer exits with the following error:
```
$ livestreamer https://www.twitch.tv/tsm_doublelift
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/tsm_doublelift
error: Unable to open URL: https://api.twitch.tv/api/channels/tsm_doublelift/access_token.json (400 Client Error: Bad Request for url: https://api.twitch.tv/api/channels/tsm_doublelift/access_token.json?as3=t)
```

**Comment by saggitar** [comment]
In another Issue someone mentioned using `--http-header Client-ID=jzkbprff40iqj646a697cyrvl0zt2m6` as a command line option. This works for me. (I also tried generating an access token, but `livestreamer --twitch-oauth-authenticate` leads me to an invalid page. Not quite sure where the Client-ID in the command above comes from :D)

**Comment by rubickcz** [comment]
This works for me as well. Thanks.

**Comment by flijloku** [comment]
Try this: https://github.com/chrippa/livestreamer/issues/1490#issuecomment-248632748
Or use https://github.com/streamlink/streamlink/releases
