### ISSUE TITLE
Vaughnlive.py Unable to validate response text:  (again)

### ISSUE THREAD

**Issue by cirrusUK** [chrippa/livestreamer#1540]
using latest plugin //  https://github.com/intact/livestreamer/commit/040cc0e85ea42a6cbf3ddb7184ac41ac50cf4f96
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/crimecentral
error: Unable to validate response text: Minimum length is 2 but value is 1
[1]    19820 exit 1     livestreamer -p mpv http://vaughnlive.tv/crimecentral worst

**Comment by intact** [comment]
You need new version https://github.com/intact/livestreamer/blob/fix-vaughn/src/livestreamer/plugins/vaughnlive.py

**Comment by cirrusUK** [comment]
i have tried that, same result.

**Comment by intact** [comment]
new plugin works for me

```
livestreamer http://vaughnlive.tv/crimecentral worst
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/crimecentral
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (rtmp)
[cli][info] Starting player: ffplay
[cli][info] Player closed
[cli][info] Stream ended
```

**Comment by cirrusUK** [comment]
@intact  My bad i'd forgotten livestreamer was running in ~/venv  thanks.
