### ISSUE TITLE
IDNA codec too long

### ISSUE THREAD

**Issue by spcsmrf** [chrippa/livestreamer#1561]
Here's the log. I dont really know whats wrong so just ask me if you need more info :)

> E:\ssdprg\python34\Scripts>livestreamer -o "E:\storage\film\JK2016\Julkalendern: Selmas saga - Avsnitt 24 | SVT Play.mp4" svtplay.se\video\11651330\julkalendern-selmas-saga\julkalendern-selmas-saga-sasong-1-avsnitt-24 best
[cli][info] Found matching plugin svtplay for URL svtplay.se\video\11651330\julkalendern-selmas-saga\julkalendern-selmas-saga-sasong-1-avsnitt-24
error: encoding with 'idna' codec failed (UnicodeError: label too long)

**Comment by intact** [comment]
Your URL is bad (try svtplay.se/video/11651330/julkalendern-selmas-saga/julkalendern-selmas-saga-sasong-1-avsnitt-24 )

**Comment by spcsmrf** [comment]
Thanks so much for the help. I frikking hate my self tried everything except that lol.
