### ISSUE TITLE
AES encryption, HLS stream. What syntax?

### ISSUE THREAD

**Issue by ghost** [chrippa/livestreamer#1562]
Hi guys, sorry for my profane language but I'm no programmer.

I'm trying to download a .m3u8 stream. I'm subscribed to the service offering that stream but I wouldn't know what command to write to pass Livestreamer my key.
Actual website is hidden for privacy reasons.

Right now I write
`livestreamer "hls://https://fakelinkto.m3u8" best -o video.ts`

But I receive
`Failed to create decryptor: unable to open URL: https://fakelinktokey.php (403 Client error forbidden)`

Would anybody point me in the right direction?
Many thanks

**Comment by flijloku** [comment]
Probably it will help: https://github.com/streamlink/streamlink/issues/150 ?

**Comment by ghost** [comment]
Hey @flijloku thanks, I just tried to use streamlink but I receive the same error message: Failed to create decryptor.

The thing is I'm subscribed to the service and if I edit the m3u8 file I can see my key, isn't there a way to tell Livestreamer that I have it?

**Comment by flijloku** [comment]
@rodolfofanti Hi! Livestreamer project is almost abandoned.  I think you need to ask questions in streamlink theme. There are a lot of knowledgeable people.  I am absolutely not understand this - just accidentally found the question. And not quite understand English :)

**Comment by ghost** [comment]
Thank you I just created a thread there!! All the best, happy 2017!
