### ISSUE TITLE
unable to open URL (400 client error: bad request)

### ISSUE THREAD

**Issue by jantrance** [chrippa/livestreamer#1563]
No matter which stream I open I get this error message

Found matching plugin twitch for URL twitch.tv/fopt_membrillo
error: Unable to open URL: https://api.twitch.tv/api/channels/fopt_membrillo/access_token.json (400 Client Error: Bad Request)

![image](https://cloud.githubusercontent.com/assets/13710925/21626115/a8599cb0-d20f-11e6-9390-129884efb4e3.png)

**Comment by flijloku** [comment]
Try this: https://github.com/chrippa/livestreamer/issues/1490#issuecomment-248632748
Or use https://github.com/streamlink/streamlink/releases

**Comment by jantrance** [comment]
Fixed with: https://youtu.be/dAdMQjjw_gk
