### ISSUE TITLE
Can I download a video in higher than 720p?

### ISSUE THREAD

**Issue by ghost** [chrippa/livestreamer#1575]
Not sure if this's the right place to ask but is it possible to do so?

**Comment by flijloku** [comment]
Why not?

**Comment by ghost** [comment]
"Available streams: 144p (worst), 240p, 360p, 720p (best), audio_mp4, audio_webm"
but it has 1080p, atleast on youtube or the livestreamer version from debian sid is too old.

**Comment by scottbernstein-zz** [comment]
Check out the Streamlink project which has taken up developing livestreamer in the last few months after this project was abandoned.  Already that project has added support for 1080p videos on Youtube.

________________________________

**Comment by flijloku** [comment]
Yes, livestreamer support only in 720p for youtube, so follow the advice above. Or use https://github.com/rg3/youtube-dl

**Comment by ghost** [comment]
Using the option "best" I get 720p too so I'll just ask on their page.

**Comment by flijloku** [comment]
If I am not mistaken for 1080 will need ffmpeg.

**Comment by ghost** [comment]
didnt know that thanks

**Comment by flijloku** [comment]
https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg
