### ISSUE TITLE
Trying to download hewillnotdivide.us - AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by made-by-chris** [chrippa/livestreamer#1576]
Hi I'm trying to download the stream from the HWNDU project @ https://hewillnotdivide.us
The only link I've found which I found which contains video was this. Could you help me find the right URL, or suggest what I'm doing wrong ? Thanks. 
https://vod.livestream.com/events/0000000000694072/3f4489c2-b32d-4965-8a99-46ee7960166e_2320-2687.ts

**Comment by made-by-chris** [comment]
I've made a tiny bit of progress by inputting the URL provided in the actual flash player: 
https://livestream.com/accounts/23093026/events/6897778/player?width=0&height=0&enableInfoAndActivity=true&autoPlay=true&mute=false

and here's the output https://ghostbin.com/paste/7x6mv

getting closer..

**Comment by mikhoul** [comment]
Here's the URL you are looking for: https://livestream.com/accounts/23093026/events/6897778/player?width=0&height=0&enableInfoAndActivity=true&autoPlay=true&mute=false%22

Regards :octocat:

**Comment by mikhoul** [comment]
@basiclaser 

I tried to record the stream with "Streamlink" and it work. 😀 

Streamlink is an active fork of livestreamer and the syntax is almost the same, you can download it here: https://github.com/streamlink/streamlink/releases/tag/0.3.1


Here's the string I used to record your stream:

`F:\Streamlink\bin\streamlink.exe "https://livestream.com/accounts/23093026/events/6897778/player?width=0&height=0&enableInfoAndActivity=true&autoPlay=true&mute=false" best -f -o H:\Telechargement\TVA.ts`

Just modify the path to where streamlink will be on your computer AND the output path for the recorded stream mine is "H:\Telechargement\TVA.ts" but put it and name it what you want  😸 

Regards :octocat:

**Comment by made-by-chris** [comment]
Thanks Bud! I got there in the end by using youtube-dl also..
