### ISSUE TITLE
Specific Youtube videos return error 410 gone

### ISSUE THREAD

**Issue by msikma** [chrippa/livestreamer#1587]
* Mac OS X 10.12.3
* Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
* livestreamer 1.12.2

The URL: https://www.youtube.com/watch?v=Wng19r5C1ck - it appears to work fine on Youtube itself. However, when I load it into Livestreamer, I get the following result:

    livestreamer "https://www.youtube.com/watch?v=Wng19r5C1ck"
    [cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=Wng19r5C1ck
    [cli][info] Available streams: audio_mp4, 144p (worst), 240p, 360p, 720p (best)
    [cli][info] Opening stream: 720p (http)
    [cli][error] Could not open stream: Unable to open URL: http://r16---sn-5hne6ner.googlevideo.com/videoplayback?upn=rFIq_0rk9eo&itag=22&ip=95.97.234.31&sparams=id%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&expire=1488248571&mm=31&ipbits=0&mn=sn-5hne6ner&mime=video%2Fmp4&ms=au&signature=1ACB09758349358591B09EB34EC6AF7B922FF51C.8971A43401E6D8961609C983F3D4FDFDFD812871&ratebypass=yes&source=youtube&mv=m&initcwndbps=1372500&id=o-AK85JHZCIdW-gbs3shq_wVVowXwG0LTUmn062DIho4-r&pl=17&key=yt6&beids=%5B9452307%5D&mt=1488226888 (410 Client Error: Gone for url: http://r16---sn-5hne6ner.googlevideo.com/videoplayback?upn=rFIq_0rk9eo&itag=22&ip=95.97.234.31&sparams=id%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&expire=1488248571&mm=31&ipbits=0&mn=sn-5hne6ner&mime=video%2Fmp4&ms=au&signature=1ACB09758349358591B09EB34EC6AF7B922FF51C.8971A43401E6D8961609C983F3D4FDFDFD812871&ratebypass=yes&source=youtube&mv=m&initcwndbps=1372500&id=o-AK85JHZCIdW-gbs3shq_wVVowXwG0LTUmn062DIho4-r&pl=17&key=yt6&beids=%5B9452307%5D&mt=1488226888)

I also get an error on this video, which is from the same user's channel: https://www.youtube.com/watch?v=bry8-Sy3jVg

However, this video from that user works just fine: https://www.youtube.com/watch?v=u6YvzUM2R9Y

I'm not entirely sure why these two specific videos are different and refuse to open.

**Comment by cdrage** [comment]
@msikma Livestreamer has been abandoned. Please try our fork of Livestreamer at http://github.com/streamlink/streamlink

**Comment by msikma** [comment]
@cdrage thanks. Unfortunately this seems to have been a temporary issue, as I can't reproduce it now. So I'll just close this without reopening it on Streamlink.
