### ISSUE TITLE
Unable to open URL ... 404 Client Error: Not Found

### ISSUE THREAD

**Issue by ROMaster2** [chrippa/livestreamer#1595]
"error: Unable to open URL: https://api.twitch.tv/kraken/user.json (404 Client Error: Not Found)"
Log:
http://i.imgur.com/Pxfteir.png

**Comment by cdag** [comment]
Ran into the same issue just now, even tried getting a new oauth token and still doesn't work.

**Comment by cdag** [comment]
Nevermind, apparently it works now for me.... I think they just had some sort of minor server hiccup for their api. Does it work now for you?
