### ISSUE TITLE
Twitch delay and rtmp

### ISSUE THREAD

**Issue by rhazor** [chrippa/livestreamer#1597]
Watching Twitch on VLC or MPC-HC delays stream to like 30 seconds and it's impossible to follow chat.

I found some infos that watching through rtmp would reduce delay, but problem is that passing `player-passthrough=rtmp` in `livestreamerrc` or simply running a command e.g. `livestreamer twitch.tv/channel source --player-passthrough rtmp` does nothing and ignores it and runs in default `hls`.

Also I tried adding these in `livestreamerrc`, but no change:
```
hls-live-edge=1
hls-segment-threads=3
```

I'm on Win10.

**Comment by flijloku** [comment]
Twitch use hls format. Not rtmp.
