### ISSUE TITLE
Can I resume the download if I lost my connection?

### ISSUE THREAD

**Issue by NiGHTsC** [chrippa/livestreamer#1616]
I know the video isn't complete, it's only 1h long while it should be 1h and 30mins.
Here is my code
`livestreamer "hls://VideoURL" best -o X:\GM\video.TS`

Is it possible to continue the download from 1h instead of restart the download from beginning?

**Comment by cdrage** [comment]
@chrippa Has abandoned Livestreamer, please use: https://github.com/streamlink/streamlink

**Comment by NiGHTsC** [comment]
I thought so, too bad :(
