### ISSUE TITLE
Properly end livestreamer

### ISSUE THREAD

**Issue by l-pa** [chrippa/livestreamer#1624]
How to properly end livestreamer? I'm using Ctrl-C (Windows), but when I do this while I'm recording, my video file is corrupted (it doesnt show lenght), but when stream is over, or internet issues and livestremer is still running, video file is ok.

**Comment by cdrage** [comment]
Hi, please use https://github.com/streamlink/streamlink as Livestreamer has been abandoned by @chrippa 

No amount of talking to him (his twitter / email / work) has amount to any communication to the community.
