### ISSUE TITLE
The vlc player is always black 

### ISSUE THREAD

**Issue by zhangwenwen** [chrippa/livestreamer#1628]
I use livestreamer+vlc  player to play the live stream(I tried live streams from youtube and twitch.tv),and the player is opened successflly, however the player displayed a black screen with nothing.

I can view the live streams in web browser  successfully.

The Terminal outputed:
```
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/polkjhbv
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: /usr/bin/vlc

```
What are the matters?

Thanks

**Comment by cdrage** [comment]
@zhangwenwen 

This is a friendly reminder that livestreamer has been abandoned by @chrippa 

Please use the fork of livestreamer called __streamlink__ located here: https://github.com/streamlink/streamlink

**Comment by zhangwenwen** [comment]
Thanks
