### ISSUE TITLE
How to extract stream URL without API?

### ISSUE THREAD

**Issue by bamtan** [chrippa/livestreamer#1667]
Hi, I'd like to obtain the stream URL by using the CLI interface, and without the API as documented here (http://docs.livestreamer.io/api_guide.html#extracting-streams). 

Are there any arguments to do this via CLI without creating a Python script?

My main goal is to simply get the `.m3u8` URL of a quality I've requested, and not play it with a player.

**Comment by cdrage** [comment]
Use https://github.com/streamlink/streamlink/ mah friend

**Comment by bamtan** [comment]
Found the solution

`livestreamer --stream-url twitch.tv/channel_name audio_only`
