### ISSUE TITLE
Fresh windows install. No output from command line

### ISSUE THREAD

**Issue by RickKukiela** [chrippa/livestreamer#1687]
Just installed, set my vlc path in the config and went to a command line and typed `livestreamer twitch.tv/path/to/stream` and i get no output. Vlc does not open. I cannot break the execution with a Control + C or Control + ] I literally have to end task to get it to stop. Even just running `livestreamer --help` or `livestreamer -h` also freezes and has no output. However `livestreamer --version` does output 1.12.2 and quits.

I really have no idea whats going on here.

**Comment by WolfganP** [comment]
This project was abandoned years ago, switch to https://github.com/streamlink/streamlink

**Comment by RickKukiela** [comment]
Yeah i realized that after I posted this. Thanks :)
