### ISSUE TITLE
Issue to read streams

### ISSUE THREAD

**Issue by karlo2105** [chrippa/livestreamer#199]
I found great quality streams but i Cannot play them with livestreamer. 
<code>
%systemdrive%\progra~1\livestreamer\livestreamer -l debug "hlsvariant://http://62.65.136.9:1935/bslive/39_1.smil/playlist.m3u8?u=672976530&t=ohqvfESWTJuIdd3P&r=891882195" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://62.65.136.9:1935/bslive/39_1.smil/playlist.m3u8?u=672976530&t=ohqvfESWTJuIdd3P&r=891882195
[cli][info] Opening stream: 1328k
[stream.hls][debug] Starting buffer filler thread
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Sequences in this playlist are encrypted
[stream.hls][debug] Buffer filler thread completed
[cli][error] Could not open stream: Need pyCrypto installed to decrypt data
</code>

**Comment by scineram** [comment]
Hi! I'm getting a pyCrypto error with the <a href="https://gist.github.com/intact/3d6af5f361c1a44fd878">daisuki plugin</a>, even after I copied the Crypto directory from pycrypto-2.6.1.win32-py2.7.exe. Do you have any idea how to fix? Thanks!
```
C:\livestreamer http://www.daisuki.net/anime/watch/CONCRETEREVOLUTIO/7sd
[cli][info] Found matching plugin daisuki for URL http://www.daisuki.net/anime/watch/CONCRETEREVOLUTIO/7sd
error: pyCrypto needs to be installed

**Comment by karlo2105** [comment]
Pycrypto is already included to Livestreamer. I guess this plugin needs fix.

**Comment by g3271084** [comment]
karlo, did you manage to get streams working along with certificate and private key?

**Comment by intact** [comment]
@karlo2105  plugin still works for me ;)

@scineram try new version (with better error reporting)

**Comment by scineram** [comment]
@intact Hi, I'm still getting a similar error with the new version.

```[cli][info] Found matching plugin daisuki for URL http://www.daisuki.net/anime/watch/ONEPUNCHMAN/zud```
```error: pyCrypto needs to be installed (exception: cannot import name Random)```

Do I need any special option to call it instead of simply
```livestreamer http://www.daisuki.net/anime/watch/ONEPUNCHMAN/zud```?
Maybe use my own login? Thanks for help.

**Comment by intact** [comment]
@scineram livestreamer contains incomplete pycrypto in library.zip

You can try:

1. delete Crypto.Cipher._AES.pyd in Livestreamer directory
2. delete Crypto in Livestreamer\library.zip
3. copy Crypto folder from pycrypto-2.6.1.win32-py2.7.exe
4. install new version of [daisuki plugin](https://gist.github.com/intact/3d6af5f361c1a44fd878)

**Comment by testodo** [comment]
@intact after steps above:

error: pyCrypto needs to be installed (exception: No module named winrandom)

**Comment by scineram** [comment]
@intact Many thanks, it works now! It downloads with -o, playback also works if I use --player-passthrough=http.
By the way I'm guessing there is no way to also put the subtitle on the stream, right?
I have to download that manually.

**Comment by intact** [comment]
@scineram Livestreamer do not support subtitles (but maybe daisuki plugin can print URL for subtitles)

**Comment by cybertvnet** [comment]
Hi,
Is there anyway to put username and password to the livestreamer?
I am trying few things.. it's giving 403 forbidden..  Please help... 
sam@ubuntu:~$ livestreamer "hds://http://hlsent5-lh.akamaihd.net/z/ams52_suntv@318185/manifest.f4m params={'v':'myuserid'} verify=False cert=('/path/to/client.crt', '/path/to/private.key')"
[cli][info] Found matching plugin stream for URL hds://http://hlsent5-lh.akamaihd.net/z/ams52_suntv@318185/manifest.f4m params={'v':'myuserid'} verify=False cert=('/path/to/client.crt', '/path/to/private.key')
error: Unable to open URL: http://hlsent5-lh.akamaihd.net/z/ams52_suntv@318185/manifest.f4m (403 Client Error: Forbidden)
