### ISSUE TITLE
Video does not play at start but audio does

### ISSUE THREAD

**Issue by aksarkar** [chrippa/livestreamer#247]
This happens on all Twitch streams I tried at all quality settings. mplayer2 starts and shows the first frame, but does not update the video or the time elapsed (stuck at 00:00:00) even though the audio plays.

mplayer2 config:

```
ao=alsa
cache-min=20
cache=8192
dvd-device=/dev/sr0
font="Segoe UI"
nolirc=true
prefer-ipv4=false
really-quiet=false
vo=xv
```

This also happens with vo=gl. With xv/gl, if I seek forward when the player starts, the video and audio restart synced. If I change vo=x11, I get no video (blank window) but audio still plays.

livestreamer g46b9e07
rtmpdump dc76f0a
mplayer2 g6c87a98
Arch Linux

**Comment by tyzoid** [comment]
Just for posterity, ffplay seems to work fine: `livestreamer twitch.tv/<user> --player ffplay`
