### ISSUE TITLE
Twitch.tv error: no streams found on this URL

### ISSUE THREAD

**Issue by ubongo1** [chrippa/livestreamer#252]
No matter which steam from twitch.tv I try to watch I always get the same error.
for example: when I write livestreamer twitch.tv/ongamenet best(tried every other quality)
[cli][info] Found matching Plugin.......
error: no streams found on this URL: twitch.tv/ongamenet
I already tried different streams same result

**Comment by rougerbaptiste** [comment]
Perhaps someone can help me even if I come after the fight... I'm using Debian 8.2 with livrestreamer 1.10.2 and have the same error ubongo had... what can I do ?

**Comment by intact** [comment]
@rougerbaptiste install newer version of livestreamer (1.11.1+)

**Comment by 4311021x** [comment]
The latest version on the official stable Debian repositories is too old.
If you don't want to install from the testing repositories you could also just update the twitch plugin.

```bash
mkdir -p ~/.config/livestreamer/plugins
wget https://github.com/chrippa/livestreamer/blob/master/src/livestreamer/plugins/twitch.py
mv twitch.py ~/config/livestreamer/plugins/
echo 'export XDG_CONFIG_HOME="$HOME/.config" >> /etc/profile.d/pam_env
```
