### ISSUE TITLE
[Win]Livestreamer+MPC-HC 1.7.3 "failed to render file"

### ISSUE THREAD

**Issue by ghost** [chrippa/livestreamer#318]
Hi there, so today I tried to use Livestreamer for the first time on Windows but it didn't work out.

This is my config:

```
player="C:\Program Files (x86)\KCP\MPC-HC\mpc-hc.exe"
player-no-close
rtmpdump=C:\Program Files (x86)\Livestreamer\rtmpdump\rtmpdump.exe
```

In cmd I put:

```
livestreamer twitch.tv/NAMEHERE low
```

The matching plugin was found, it said opening stream low and then started the player but the player is just blank and says "failed to render file."
The stream was something popular I picked from the homepage to test which worked fine on the browser. Nothing that needed any sort of authentication.
Am I doing something wrong?

**Comment by carnifexx** [comment]
run into the same problem today (win10pro x64, mpc-hc1.7.10 x64, no extra codecs, livestreamer 1.12.2)
I solved it by setting MPC-HC to:
View > Options > Playback > Output > DirectShow Video > to "System Default"

this is my twitch stream .bat file, named "rbtv.bat":
@echo
cd C:_Anzeige\Livestreamer
livestreamer.exe http://www.twitch.tv/rocketbeanstv source
@echo off

Works great and fast now just by open the desktop shortcut to the rbtv.bat file, and without using flash, a Browser or VLC. It just a noob-amateur tip, I know, but I hope it helps future stream watchers.

Edit: now I changed it to "Enhanced Video Renderer" which looks way better (surprise!).
