### ISSUE TITLE
Stream hls error?

### ISSUE THREAD

**Issue by MICKXY** [chrippa/livestreamer#331]
I am currently using VLC 2.1.3 and Livestreamer 1.7.5 and I am getting the following error while trying to watch streams on VLC.

C:\Users\Mick>livestreamer http://www.twitch.tv/esltv_lol high
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/esltv_lol
[cli][info] Opening stream: high
[cli][info] Starting player: 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[stream.hls][error] Failed to open sequence 1345: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1345.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[stream.hls][error] Failed to open sequence 1345: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1345.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[stream.hls][error] Failed to open sequence 1345: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1345.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[stream.hls][error] Failed to open sequence 1364: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1364.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[stream.hls][error] Failed to open sequence 1364: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1364.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[stream.hls][error] Failed to open sequence 1364: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1364.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[stream.hls][error] Failed to open sequence 1365: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1365.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1365: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1365.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1365: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1365.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1367: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1367.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1367: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1367.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1367: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1367.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1368: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1368.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1368: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1368.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1368: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1368.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1369: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1369.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1369: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1369.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1369: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1369.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1370: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1370.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1370: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1370.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1370: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1370.ts (4
04 Client Error: Not Found)
[stream.hls][error] Failed to open sequence 1371: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1371.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[stream.hls][error] Failed to open sequence 1371: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1371.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[cli][error] Error when reading from stream: Read timeout
[stream.hls][error] Failed to open sequence 1371: Unable to open URL: http://vid
eo25.sfo01.hls.twitch.tv/hls9/esltv_lol_8876584288_74424189/high/index1371.ts (H
TTPConnectionPool(host='video25.sfo01.hls.twitch.tv', port=80): Read timed out.
(read timeout=<object object at 0x011B1498>))
[cli][info] Stream ended

On the last line, VLC closes by itself.

What happens during this is, stream plays normally for a few seconds, starts stuttering, video freezes but audio still can be heard, stream will be normal for a couple of seconds and it repeats. If the stream freezes too many time, VLC will close by itself

**Comment by refriedfood** [comment]
Since this is the only place I could find help relating to this error and livestreamer. The m3u8 file plays fine in certain versions of VLC, however it drops during the .ts exchange in other players (after 1-10 minutes) and eventually locks up in VLC. Now to try and avoid this I tried using combinations in livestreamer but to no avail. You can try the 24/7 m3u8 right here and see if you get the same error:
`
([Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure)`

livestreamer hls://https://cams.cdn-surfline.com/wsc-west/wc-elportocam.stream/chunklist.m3u8 best

However, you can open the m3u8 in VLc or even https://www.hlsplayer.net/
