### ISSUE TITLE
[Request] auto-retry

### ISSUE THREAD

**Issue by VackerSimon** [chrippa/livestreamer#333]
It would be great if Livestreamer could auto-retry every x seconds if no stream is found or if it times out. Right now I have a .bat file which does this but because of an issue in Windows it allocates memory on each process start and doesn't release it until you restart.

**Comment by pragma-** [comment]
Is there no option for limiting how many times --retry-streams will retry?  I'd like livestreamer to exit after attempting 5 retries with 30 seconds in between retries so that the rest of a script may execute and do stuff.
