### ISSUE TITLE
Problems using Livestreamer with Twitch & VLC.

### ISSUE THREAD

**Issue by GeekGames73** [chrippa/livestreamer#362]
Hello,

I downloaded Livestreamer today in order to record PlayStation 4 gameplay that I was streaming through Twitch. I set up the program the correct way, and this is the result I've been getting:

C:\Users\Joe>@echo
ECHO is on.

C:\Users\Joe>cd c:\program files (x86)\livestreamer

c:\Program Files (x86)\Livestreamer>livestreamer.exe twitch.tv/geekgames73 best
[cli][info] Found matching plugin twitch for URL twitch.tv/geekgames73
[cli][info] Available streams: source (worst, best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'
[stream.hls][error] Failed to open segment 36: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0036-mi6v.ts (timed out)
[stream.hls][error] Failed to open segment 36: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0036-mi6v.ts (timed out)
[stream.hls][error] Failed to open segment 36: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0036-mi6v.ts (timed out)
[stream.hls][error] Failed to open segment 37: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0037-NZTU.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 37: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0037-NZTU.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 37: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0037-NZTU.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 38: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0038-B79F.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 38: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0038-B79F.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 38: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0038-B79F.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 39: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0039-dVHE.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 39: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0039-dVHE.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 39: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0039-dVHE.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 40: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0040-dP3L.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 40: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0040-dP3L.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 40: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0040-dP3L.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 41: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0041-85Ya.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 41: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0041-85Ya.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 41: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0041-85Ya.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 42: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0042-m6XD.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 42: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0042-m6XD.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 42: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0042-m6XD.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 43: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0043-nH94.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 43: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0043-nH94.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 43: Unable to open URL: http://video1
9.sfo01.hls.twitch.tv/hls30/geekgames73_9312266880_87888065/chunked/index-000000
0043-nH94.ts (404 Client Error: Not Found)
[cli][error] Error when reading from stream: Read timeout

VLC opened up ok, and played the stream for a couple of seconds but before I could start recording it froze, and this was in the Command Prompt. I am using Livestreamer with Windows 7 and my VLC is up to date.

**Comment by direwolfie** [comment]
> Try livestreamer --hls-segment-threads 4 twitch.tv/<channel> source this will set the number of used threads to 4.

@Phidelux Thanks! Adding `--hls-segment-threads 10` made the stream watchable, but it would skip a bit sometimes (which is still pretty annoying).
And occasionally it would stop completely giving the following error - `[stream.hls][error] Failed to open segment 4413 ... (timed out)`.
Before this solution I was having the same "stutter" problem with "404 Client Error", but not always - only at some times in the day, usually evenings (probably something to do with twitch servers' load?).

@chrippa I wonder if this has something to do with streams being broadcast at higher and higher fps (720p@1000fps and 1080p@80fps) and twitch becoming more and more popular.
Maybe the default value should be a bit bigger? I am a bit of a noob with Livestreamer and it took me ages to find this solution. I believe quite a few people are struggling with this.

**Comment by kil4** [comment]
@Phidelux Thanks, adding `--hls-segment-threads 4` fix

**Comment by Phidelux** [comment]
@direwolfie Setting --hls-segment-threads to a value of 10 makes in most cases no sense, because switching between threads is an expensive task. You should never use more threads than cores you have (just if you have additional thread handlers), which is in most cases a number 2^x (2, 4, 8, 16, ...). So try again with 4 or 8 but not 10.

**Comment by direwolfie** [comment]
@Phidelux Thanks! Didn't know about that. I will refrain from setting to more than the no. of cores on the cpu.
I set it to 4 threads and it seems to work for now.
