### ISSUE TITLE
Choose subtitles language with Crunchyroll

### ISSUE THREAD

**Issue by zJoul** [chrippa/livestreamer#364]
Is there a way to change subtitle when playing a crunchyroll stream ?

If I use a crunchyroll.fr URL, I got this error : 
`error: No plugin can handle URL: http://www.crunchyroll.fr/...`
so I must use the .com url.

**Comment by holymoly55** [comment]
configure the language on the settings page don't work anymore :'(

**Comment by nih0** [comment]
@asermax Which browser did you use? I tried it with Chrome + IE but it did not work.

I found this project: http://www.darkztar.com/forum/showthread.php?219034-Ripping-videos-amp-subtitles-from-Crunchyroll-%28noob-friendly%29 where you can change the subtitles language. 

I did not understand the code 100%(not a python coder) but it seems like you can not choose the language over the api.

**Comment by asermax** [comment]
I did it over chrome, but it was a while ago so that may have changed. Also we had to change some of the implementation of the plugin because the API started failing, so that may have afected how it works.

As for the program you linked, that seems to be using a different mechanism to get a handle on the stream; instead of using the API, it seems to be scrapping the site and getting the RPC stream from the flash player.
The API we're using provides a HLS stream with hard subs instead, and as far as we tried (we don't have a documentation on the API), it was not posible to change the language for the video using it.
If I have some time, I'll do some more digging to find an alternative.

**Comment by lamethoderose** [comment]
Maybe that can thas help some one, I use firefox+open with and mpv/youtube-dl, I can chose my sub but I don't have premiun account (thing work too).

**Comment by maexono** [comment]
I do get german subtitles when I substitute the API_LOCALE and user agent in crunchyroll.py with "deDE" and "Mozilla/5.0 (iPhone; iPhone OS 8.3.0; de_DE)" respectively. You might try something similar for your locale.

**Comment by StarWolf3000** [comment]
So then you could implement two new parameters to the cli to set the locale and user agent language and use enUS for the API_LOCALE and en_US for the user agent language by default.

These would be Crunchyroll specific.

Or both are read from the system it is running on.

Example: `livestreamer --crunchyroll-locale=deDE --crunchyroll-uagent-locale=de_DE http://www.crunchyroll.com/some/series/link qualitysetting`

This was not tested on my side, but it should not be a problem to implement them and rewrite the code of crunchyroll.py to accept the new params (I'm not that confident with Python).

**Comment by Zeyth** [comment]
Just came to say that as maexono says, after changing en_US and enUS to es_MX and esMX [can be es_ES/esES for Spain, but i want the Latin America ones] on crunchyroll.pyc, i'm getting spanish subtitles, so yeah, thanks for info, and as StarWolf says, i hope someone can implement it.

**Comment by asermax** [comment]
I'll give it a look when i have some time :+1:

**Comment by StarWolf3000** [comment]
Does it work, if you just set the locale of the API and not the user agent? Your referenced pull just changes the API_LOCALE, not the user agent.

**Comment by asermax** [comment]
It does work as far as I've tested (tried with a couple of urls using different locales), but for the sake of consistency and to play it safe I'll add it to the `user-agent` as well; it completely went over my head when I was working on the patch, sorry :d
