### ISSUE TITLE
Permission problems

### ISSUE THREAD

**Issue by ghost** [chrippa/livestreamer#400]
I am trying to use VLC installed with homebrew-cask to watch live streams with Livestreamer 1.8.1. I set the player to /opt/homebrew-cask/Caskroom/vlc/2.1.4/VLC.app and when I try to run Livestreamer I get: 
cli][info] Starting player: /opt/homebrew-cask/Caskroom/vlc/2.1.4/VLC.app
error: Failed to start player: /opt/homebrew-cask/Caskroom/vlc/2.1.4/VLC.app ([Errno 13] Permission denied)

When I run Livestreamer with VLC in the normal installation folder /Applications/VLC.app, it works fine. Is there a way fix this permission error?

**Comment by Fiskie** [comment]
holy hell I've had this problem for months and only now have I found this solution. I guess it makes sense since VLC.app is just a directory...
