### ISSUE TITLE
UnicodeDecodeError on Windows 8.1

### ISSUE THREAD

**Issue by zovt** [chrippa/livestreamer#425]
Hi! I'm trying to use livestreamer to watch a twitch stream. Here is the command I am using:
`livestreamer twitch.tv/speeddemosarchivesda medium`

And here is the output (using loglevel debug):

```
[cli][info] Found matching plugin twitch for URL twitch.tv/speeddemosarchivesda
[cli][info] Available streams: high, low, medium, mobile (worst), source (best)
[cli][info] Opening stream: medium (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1095 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1096 to queue
[stream.hls][debug] Adding segment 1097 to queue
[stream.hls][debug] Download of segment 1095 complete
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe" --file-cach
ing=5000
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 784, in main
  File "livestreamer_cli\main.py", line 477, in handle_url
  File "livestreamer_cli\main.py", line 367, in handle_stream
  File "livestreamer_cli\main.py", line 247, in output_stream
  File "livestreamer_cli\console.py", line 73, in exit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 23: ordinal
 not in range(128)
```

Any ideas what is wrong? Thanks in advance

**Comment by Mebius973** [comment]
Hi, I've got the exact same error, except I can't remove my cygwin's python install because, apparently, git need it. Any Ideas?

**Comment by joshuaduffy** [comment]
When you input `python --version` into the console, what does it say?

**Comment by Mebius973** [comment]
Sorry for taking so long to answer this, I didn't noticed Github's notif :S
The problem: Apparent python conflict (or something like that)
Cause: installing and trying to launch livestreamer outside cygwin while having a cygwin installed
Solution: launch livestreamer from Cygwin :+1: 

Everything is properly working now :-)
