### ISSUE TITLE
Including a timestamp in the output filename

### ISSUE THREAD

**Issue by kstanleyadams** [chrippa/livestreamer#445]
If I plan to record multiple streams over a time period to a file, and I just want to leave livestreamer running, is it possible to append the output filename with a timestamp?

Thanks

**Comment by serendipiteez** [comment]
I tried this, but could not get it to work. 

livestreamer %1 best --retry-streams 60 --stream-timeout 6000 -o "File-$(date+%Y-%m-%d).mp4"

I need a timestamp on the file.

What should I do? Thanks!

**Comment by serendipiteez** [comment]
@chrippa is there a Windows way of achieving this? Thank you.

**Comment by skulblakka** [comment]
On Windows this seems to be a little more complicated than on Linux. Take a look at the script I posted in #1244
