### ISSUE TITLE
Twitch.tv buffering a lot, Failed to open segment, etc..

### ISSUE THREAD

**Issue by scriptomania** [chrippa/livestreamer#456]
Hi there, I'm very new to this whole livestreamer thing. As the program is made, I'm using it to watch twitch.tv streams through VLC Media player. I have the quality set to source, for every stream. 

Now for having the quality set to source, of course it's going to buffer/lag. But looking at windows task manager in windows 8.1 It's showing the CMD/VLC Media player is averaging download speeds at 2Mbps, when my max download speed is 7Mbps. It might be a slow max speed, but It runs twitch.tv livestreams on source, perfectly fast in browser. But when it comes to opening it with the livestreamer file, in VLC Media player, The speeds stay very low. 

Also the command prompt is showing the Failed to open segment error, continuously. Doesn't happen on all streams, just when It starts to dramatically buffer every second. 

My question is, How can I make the livestreamer file with VLC Media player run the default max download speed, (7Mbps) instead of averaging around 2Mbps? 

How can I make it more faster?

How could it be equally same as when It's being played in browser mode? 

Thanks!

**Comment by fragtion** [comment]
hls-segment-threads saved my 4$$. It's the only thing that's worked for me besides relaying the stream via a dedicated server. Thanks so much for adding this essential feature, so glad I found it!!!  I'm also in South Africa btw
