### ISSUE TITLE
FilmOn doest’n work

### ISSUE THREAD

**Issue by Ordval** [chrippa/livestreamer#514]
On this particular day FilmOn doest’n work. 
“error: No streams found on this URL: http://www.filmon.com/tv/bbc-two”
FilmOn is up and running, also for BBC two”.

Livestreamer works otherwise as general.
I’ve already rebooted.

I’ve seen: “Filmon plugin doesn't work #377” , “invalid json respnse when opening filmon stream #372” and several others.

I’ve put in “filmon.py” (Fix Invalid Json Response) in
[C:\Program Files\VLC\Livestreamer\livestreamer-1.10.1-py2.7.egg\livestreamer\plugins]
[C:\Users\Ordval\AppData\Roaming\livestreamer] and desperately wherever I could.

Previous message was “error: Unable to validate JSON: Unable to validate key 'streams': 
Unable to validate key 'url': Unable to validate URL attribute 'scheme': 
u'http' does not equal 'rtmp' “

I’m opening a new issue rather than writing on any of the old; which is preferable ?
Same question goes for my request for a plugin for [http://www.pluzz.fr/] put on
“Request for new plugins #328”.  Should I rather open a new ?

**Comment by Ordval** [comment]
These two 
[http://www.filmon.com/tv/the-dick-van-dyke-show]
[http://www.filmon.com/tv/the-lucy-show worst]
don't open whereas the regular live stream channels do.

**Comment by adibabu** [comment]
Filmon tv is Nice site but some time some channel did not play
[http://livetvlab.com/](url)
