### ISSUE TITLE
Feature request: Reconnect after "Stream ended"

### ISSUE THREAD

**Issue by Evu-EN** [chrippa/livestreamer#550]
Hello and thx for the great work on livestreamer so far!

However i would be extremely grateful, if somebody could add a parameter to the config, which tries to fire up the stream again after a couple of seconds -for a limited time/number of tires- as soon as "stream ended" gets detected  (in a similar manner that the --retry-streams parameter does on start up), before shutting the livestreamer window down for good.

Reason for this is obviously that some streamers don't have the most consistent connection to the streaming service, and when spectating an event from the couch (occasionally in another room from the PC) it's troublesome to stand up and fire it up again just for it to go down another time 5 minutes later...

It would also be cool if the same option would exist for the detection of "player closed", since I'm personally using --player-passthrough and my MPC closes itself once a stream ends (but also saves its status/position settings, so i don't have to adjust it again, when reinitializing livestreamer again). It would also have the nice side effect of preventing accidental manual player closings~

thx in advance

**Comment by NewsGuyTor** [comment]
I might be dumb, but this doesn't seem to work for me. I use settings that should work:
1. `livestreamer "$streamurl" best --loglevel debug --player-external-http --player-no-close --player-external-http-port "$portnumber" --retry-streams 1 --retry-open 100 --stream-segment-attempts 20 --stream-timeout 180 --ringbuffer-size 64M --rtmp-timeout 240`
2. `ffmpeg -re -i http://127.0.0.1:"$portnumber"/ -reconnect_streamed -reconnect_at_eof -y -c copy -acodec copy -timeout 30000000 filename.mp4`

It actually works great for massive connection disruptions. I've tried disconnecting the internet for almost a minute and the stream continued being saved into ffmpeg without any issues as soon as the internet returned (apart from a skip in the video ofc). However, when livestreamer outputs "Stream ended", seemingly arbitrary (the stream runs perfect if watched in its flash player), the recording ends.
