### ISSUE TITLE
Mac OSX configuration file location

### ISSUE THREAD

**Issue by Smultie** [chrippa/livestreamer#579]
I can't seem to find the location of the configuration file on Mac OS. 
Can anyone point me in the right direction?

**Comment by zdefter** [comment]
hello, i'm a bit of a noob when it comes to mac os x, so i was looking for some help with getting my config file working.

i created a file "config.txt" with the same contents as user Smultie had (and i also made the corrections as well), and placed it in my /Users/Me/.config/livestreamer/ folder but, whenever i launch a stream using the normal command, it doesn't say "Starting player: /Applications/VLC.app/Contents/MacOS/VLC --file-caching=5000" as it should and only shows "Starting player: /Applications/VLC.app/Contents/MacOS/VLC"

"Starting player: /Applications/VLC.app/Contents/MacOS/VLC --file-caching=5000" only shows up if i type out the commands in terminal. is this normal behavior?

**Comment by 7ylxr9** [comment]
I created my config.txt in /Users/Me/.config/livestreamer/ and I only typed in `twitch-oauth-token=auth code` and the auth code I got from `livestreamer --twitch-oauth-authenticate` and it just ignores that completely which makes me think the config file isn't being recognized.

**Comment by zdefter** [comment]
yep, i'm pretty sure that's what's happening. i've tried to direct livestreamer to a new config folder but, that didn't seem to do anything :(

**Comment by 7ylxr9** [comment]
I used Livestreamer GUI and everything works seamlessly and there's a GUI to pick who I want to watch instead of finding an active stream.

**Comment by zdefter** [comment]
i remember using livestreamer GUI for a brief time (around the time it was first released) but, there were some issues here and there at that time i think.

i reinstalled it and livestreamer seems to be running rather smoothly. thanks for letting me know :)
