### ISSUE TITLE
http://www.livestation.com does not work anymore

### ISSUE THREAD

**Issue by vstavrinov** [chrippa/livestreamer#581]
Example: http://www.livestation.com/en/dw

**Comment by my-password-is-password** [comment]
Does livestation still work in livestreamer?  I think they changed their site.

**Comment by potentate** [comment]
On Thu, Jan 29, 2015 at 09:09:05PM -0800, my-password-is-password wrote:

>    Does livestation still work in livestreamer? I think they changed their
>    site.

Yes, nothing works - site totally changed: it requires registration and
login now.

*******************************
###  Vladimir Stavrinov
###  vstavrinov@gmail.com
*******************************

**Comment by my-password-is-password** [comment]
I registered and the ```.m3u8``` is no longer in a meta tag.  You can still find it in the flashvars,

```
<param 
name="flashvars" 
value=config={ "key":"#$2713b892e00681c2b58",
               "wmode":"direct",
               "clip":{"url":"b_,264,528,828,.f4m",
                       "live":true,
                       "autoPlay":true,
                       "autoBuffering":true,
                       "bufferLength":5,
                       "accelerated":true,
                       "scaling":"fit",
                       "urlResolvers":["f4m","bwcheck"],
                       "provider":"httpstreaming",
                       "ipadUrl":"http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/dw_europe_en/ls_satlink/b_,264,528,828,.m3u8",
                       "baseUrl":"http://wpc.C1A9.edgecastcdn.net/hds-live/20C1A9/dw_europe_en/ls_satlink"},
                       ...
```

```
http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/dw_europe_en/ls_satlink/b_,264,528,828,.m3u8
```
becomes 
```
http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/dw_europe_en/ls_satlink/b_264.m3u8   // low quality
http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/dw_europe_en/ls_satlink/b_528.m3u8   // medium quality
http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/dw_europe_en/ls_satlink/b_828.m3u8   // high quality
````

Tried it in VLC and it worked.

**Comment by potentate** [comment]
I know. Long ago I've created my playlist:
#EXTM3U
#EXT-X-TARGETDURATION:
#EXTINF:0,CNN International                     
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/cnn/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,BBC                                   
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/bbc_world/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,DW                                    
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/dw/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,France-24                             
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/france24_en/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,Sky News
http://wpc.C1A9.edgecastcdn.net/hls-live/20C1A9/skynews/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,EuroNews                               
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/euronews_en/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,Al Jazeera International
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/aljazeera_en/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,i24 News
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/i24/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,CCTV
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/cctv_news/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,Russia Today
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/rt_en/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,Press TV
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/presstv/ls_fiber/b_,828,528,264,.m3u8
#EXTINF:0,Bloomberg
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/bloomberg/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,Espreso
http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/espresotv/ls_satlink/b_,828,528,264,.m3u8
#EXTINF:0,Ruptly-1
http://wpc.ca59.edgecastcdn.net/hls-live/20CA59/default/encoder1/ruptlystream1.m3u8
#EXTINF:0,Ruptly-2
http://wpc.ca59.edgecastcdn.net/hls-live/20CA59/default/encoder2/ruptlystream2.m3u8
#EXTINF:0,Ruptly-3
http://wpc.ca59.edgecastcdn.net/hls-live/20CA59/default/encoder2/ruptlystream3.m3u8
#EXTINF:0,Ruptly-4
http://wpc.ca59.edgecastcdn.net/hls-live/20CA59/default/encoder4/ruptlystream4.m3u8
#EXT-X-ENDLIST
