### ISSUE TITLE
www.stream4free.eu  plugin request

### ISSUE THREAD

**Issue by dynamitemedia** [chrippa/livestreamer#632]
another great site, i use some of them now in a playlist and seem to have both rtmp and HLS  

viewing page source gets hls link

**Comment by dynamitemedia** [comment]
they have changed to http://www.jtvstream.me/

**Comment by campones** [comment]
I told you I dont have bandwidth for this kind of stuff man, don't you understand?

**Comment by dynamitemedia** [comment]
i am not trying to be a jerk here or anything but isn't what your doing  not quite "legal" anyways?

**Comment by campones** [comment]
you are not trying but near to be successful.. do you want to site to stop operating?

it's an open, non geo blocked, free to access website so if you want to see videos, you don't have to hack it.. except if you have something else in mind..  right?  

this argument you know, I heard it so many times already..  it s not very legal, so I do what I want lmao.. like you would care about that if it was legal anyway ??  this is a lie... so start moving you little ass and work for once, download your stuff, rent a server, stream it.. and stop begging for what you can do sooo easily..  jerk
