### ISSUE TITLE
No streams found on this url

### ISSUE THREAD

**Issue by dannyellis-zz** [chrippa/livestreamer#633]
Just started happening about 30 minutes ago. Definitely know there is a stream and have tried many different streams to test. Keep getting back in the json that there are no streams available. Don't think it has to do with the update that just went out though.

**Comment by DeafSmartGamers** [comment]
Hello Guys!  I got error no streams found on this URL: twitch.tv/--------- when i tired to fixed it VLC media Player over livestreamer.exe then I use CMD.exe it say " error no streams found on this URL: " any know how to fix stop error ? Let me know.. Help me  Many thanks
