### ISSUE TITLE
Player halts when fast forwarding in Twitch archived broadcast

### ISSUE THREAD

**Issue by Brottweiler** [chrippa/livestreamer#655]
It's fine to watch a past broadcast, but as soon as I start to seek in the video (to fast forward) it just hangs there. Is there a way to start playing at a specific timestamp, or can this be fixed somehow?

**Comment by tyaremco** [comment]
I believe this is a VLC limitation.   VLC doesn't report any timestamps in the seekbar and jumping forward or back simply doesn't work.  MPC-HC handles all this flawlessly.   You do need to set --player-passthrough=hls however.

**Comment by Brottweiler** [comment]
I'm using mpv.
