### ISSUE TITLE
vaughnlive.tv plugin broken (503 Service Error..)

### ISSUE THREAD

**Issue by TisIte** [chrippa/livestreamer#656]
Looks like vaughnlive.tv has added some sort of ddos protection from cloudflare on their site. When visiting the home page it will check your browser for 5 seconds before redirecting to the site. This breaks the plugin and throws a "error: Unable to open URL: ........... (503 Service Error: Service Temporarily Unavailable). 

This ddos browser check occurs just once and adds a cookie cf_clearance. Using --http-cookie to add that doesn't seem to get past the 503 error. Any ideas?

**Comment by fadster** [comment]
It's doing it again now :(
