### ISSUE TITLE
[Plugin]   ilive/streamlive.to broken ..  again

### ISSUE THREAD

**Issue by cirrusUK** [chrippa/livestreamer#660]
hi
  I know you recently fixed plugin for ilive/streamlive.to but just to let you know it appears to be not working again. (Archlinux x86_64) ive tried latest livestreamer-git & rtmpdump-git and it worked fine for a few weeks then flatlined.
regards
cirrus

**Comment by potentate** [comment]
They rolled back from http://www.streamlive.to/view-channel to http://www.streamlive.to/view. Again. Ridiculous.

**Comment by daslicious** [comment]
@potentate are you going off the development branch?

**Comment by potentate** [comment]
Don't understand. What do mean? This changing in url appears just today. Yesterday there was old url.

**Comment by daslicious** [comment]
:(

**Comment by dynamitemedia** [comment]
im getting this error

[cli][info] Found matching plugin streamlive for URL https://www.streamlive.to/v
iew-now/67439/
[plugin.streamlive][warning] Failed to extract HLS streams: Unable to open URL:
http://#:1935/edge/_definst_/0i6e1w2q4non031/playlist.m3u8?xs=_we_MGk2ZTF3MnE0bm
9uMDMxfDE0MjI5NzU4MTZ8fDU0ZDA1NmE4ODQ1YTF8MWE1NTdkYjJhYWYxZGY4Y2EyN2E2YmExMDViYT
ljMjdmZDZjZjM5ZQ.. (Invalid URL u'http://#:1935/edge/_definst_/0i6e1w2q4non031/p
laylist.m3u8?xs=_we_MGk2ZTF3MnE0bm9uMDMxfDE0MjI5NzU4MTZ8fDU0ZDA1NmE4ODQ1YTF8MWE1
NTdkYjJhYWYxZGY4Y2EyN2E2YmExMDViYTljMjdmZDZjZjM5ZQ..': No host supplied)
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] No data returned from stream

**Comment by daslicious** [comment]
yeah, i don't know what the problem is

**Comment by potentate** [comment]
The problem is in changed stream URL. It becomes invalid. See example for cnn:

wget -qO - "http://www.mobileonline.tv/channel.php?n=68967" | grep xs=_we

It is similar error output above. You should scrape out from output 3 MRL for rtmp:, rtsp: and http: and replace # with hostname watch1.streamlive.to. Unfortunately this is not sufficient. There are something more we should to do.

**Comment by potentate** [comment]
You can use this script to scrap out clean right stream URLs:

wget -qO - "http://www.mobileonline.tv/channel.php?n=68967" | 
grep -Eo '[a-z]+://#:1935/edge/_definst_/[[:alnum:]]+.*\?xs=_we[^ ]+' | 
sed 's%#%watch1.streamlive.to%' 

Regrettably, but those URL doesn't work. It needs more investigations

**Comment by potentate** [comment]
It says it is for premium account, but this channel is free available on site. So it looks like auth problem.

**Comment by dynamitemedia** [comment]
so does this work?

http://watch1.streamlive.to:1935/edge/definst/0i6e1w2q4non031/playlist.m3u8....... etc

**Comment by potentate** [comment]
No. This is auth problem. Those URLs are no authorized. So, there should exists some other way to get URL.

**Comment by cirrusUK** [comment]
Thanks lad's for hacking away at this

**Comment by cirrusUK** [comment]
Just piping in with some info that devs may find relevant, i recently updated the xbmc 14 (kodi) ilive plugin and it allows me to view, so if those with the skills can see how that plugin snarfs the URL then it *might* fix this. If this is not relevant i apologise for teh noise.
