### ISSUE TITLE
Crunchyroll Streaming not working. 

### ISSUE THREAD

**Issue by nashkt** [chrippa/livestreamer#668]
Crunchyroll was recently at the receiving end of a massive DDoS attack. After that issue was resolved and crunchyroll was restored I haven't been able to use livestreamer on crunchyroll. Whatever they did server side seems to have broken streaming through livestreamer.

The specific error I get while attempting to stream is this.

[cli][info] Opening stream: high (hls)
[stream.hls][error] Failed to open segment 0: Unable to open URL: http://v.lvlt.
crcdn.net/c18/s/ve1185603/v12/video-0.ts?nvb=20150102033551&nva=20150102073651&t
oken=0b05acb0ed6593972162e (HTTPConnectionPool(host='v.lvlt.crcdn.net', port=80)
: Read timed out. (read timeout=10.0))

**Comment by troyBORG** [comment]
Same issue here
[code][cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/attack-on-titan/episode-14-still-cant-see-night-before-the-counteroffensive-1-642189
[cli][info] Available streams: high, low (worst), mid, ultra (best)
[cli][info] Opening stream: ultra (hls)
[stream.hls][error] Failed to open segment 0: Unable to open URL: http://v.lvlt.crcdn.net/c18/s/ve1121719/v12/video-0.ts?nvb=20150105184646&nva=20150105224746&token=084f5dec524da5f151ed2 (HTTPConnectionPool(host='v.lvlt.crcdn.net', port=80): Read timed out. (read timeout=10.0))
[stream.hls][error] Failed to open segment 0: Unable to open URL: http://v.lvlt.crcdn.net/c18/s/ve1121719/v12/video-0.ts?nvb=20150105184646&nva=20150105224746&token=084f5dec524da5f151ed2 (HTTPConnectionPool(host='v.lvlt.crcdn.net', port=80): Read timed out. (read timeout=10.0))
[stream.hls][error] Failed to open segment 0: Unable to open URL: http://v.lvlt.crcdn.net/c18/s/ve1121719/v12/video-0.ts?nvb=20150105184646&nva=20150105224746&token=084f5dec524da5f151ed2 (504 Server Error: Gateway Time-out)[stream.hls][error] Failed to open segment 1: Unable to open URL: http://v.lvlt.crcdn.net/c18/s/ve1121719/v12/video-1.ts?nvb=20150105184646&nva=20150105224746&token=02a8e001e3c058438c388 (HTTPConnectionPool(host='v.lvlt.crcdn.net', port=80): Read timed out. (read timeout=10.0))
[cli][error] Failed to read data from stream: Read timeout[/code]

**Comment by chrippa** [comment]
Are you guys using proxies? I think it may be same issue as #653.

It looks like Crunchyroll may have started to use some anti-proxy measures.

**Comment by troyBORG** [comment]
No proxy for me.    It let's me watch it on the website just fine.  I just want to -o it for easy batch watching in my video player or storing on tablet so I can watch when not near internet.

**Comment by troyBORG** [comment]
Well it is working today for me.  Exact same set of commands

**Comment by nashkt** [comment]
Can confrim here as well. Livestreamer is working again with crunchyroll. No idea what has changed but the issue seems to be gone!
