### ISSUE TITLE
Twitch is broken

### ISSUE THREAD

**Issue by exonys** [chrippa/livestreamer#671]
WIndows 8.1 x64 with all updates, livestreamer 1.11
Log:
C:\Users\X>livestreamer -l debug http://www.twitch.tv/cheatbanned
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/cheatbanne
d
error: No streams found on this URL: http://www.twitch.tv/cheatbanned

**Comment by jmcphe** [comment]
I got something similar which I circumvented by using a non-blank twitch-oauth-token

**Comment by VackerSimon** [comment]
If you run livestreamer --version does it say livestreamer.exe 1.11.1? If you've updated an older version there is probably old files left if you didn't remove them yourself.

**Comment by aireca** [comment]
source quality is intermittently working for me, i reinstalled and i tried with a oauth token too, still does not work sometimes, i think twitch changed source quality to 3 second videos, maybe is related. Medium quality always work. I'm using latest PotPlayer.

**Comment by exonys** [comment]
I uninstalled old version before installing new one

**Comment by exonys** [comment]
NIghtly zip works perfectly
