### ISSUE TITLE
"Failed to load plugin tga" with latest Nightly

### ISSUE THREAD

**Issue by VerGreeneyes** [chrippa/livestreamer#677]
Since the last few Nightly builds (I think since 1.11.1.10) I've been getting the following error whenever I try to watch a stream:

    Failed to load plugin tga:
      File "c:\program files (x86)\livestreamer\livestreamer-1.11.1-py2.7.egg\livestreamer\plugins\tga.py", line 15, in <module>
        _stream_re = re.compile("<iframe style='(.*)?' frameborder='0' scrolling='no' src='http://v.qq.com/iframe/live_player.html\?cnlid=(?P<cnid>\d+)&width=\d+&height=\d+'></iframe>");
      File "re.py", line 190, in compile
      File "re.py", line 242, in _compile
    error: nothing to repeat

This error doesn't actually seem to prevent Twitch streams from working (I haven't tested any other services), so it's mostly noise for me, but I assume this would cause problems for qq.com.

If it matters, I'm using 64-bit Windows 7.

**Comment by chhe** [comment]
This seems to be duplicate of #672.

**Comment by VerGreeneyes** [comment]
Ah, you're right. Don't know how I missed that one.
