### ISSUE TITLE
plugin request disney channel livestream

### ISSUE THREAD

**Issue by blendi-93** [chrippa/livestreamer#679]
can we get support pls for: http://disneychannel.de/livestream

**Comment by brickleroux** [comment]
You can already watch the HLS stream (maybe it is geo restricted):

`livestreamer "hlsvariant://https://de_fta_simulcast-lh.akamaihd.net/i/live_1@153866/master.m3u8" best`

**Comment by blendi-93** [comment]
thx, works.

how do u got the link ?

**Comment by brickleroux** [comment]
It's in the source code of the site.

**Comment by blendi-93** [comment]
y, i foun it but for what i have to looking for (.m3u(8)) ?

**Comment by chrippa** [comment]
Closing as #698 added support for this.
