### ISSUE TITLE
Preferred python version

### ISSUE THREAD

**Issue by maxnordlund** [chrippa/livestreamer#680]
I was just wondering what the difference between running this on python2 vs python3 is? Is there a preferred version?

I love this program, made AGDQ much  better to watch.

**Comment by chrippa** [comment]
Using Python 3 is preferred since it may have more security fixes and updates (especially in regards to SSL) than Python 2 but there is no differences feature-wise.

**Comment by maxnordlund** [comment]
Thanks, I'll switch to python 3 then. I found it to be cleaner in general.
