### ISSUE TITLE
MLG.tv issues

### ISSUE THREAD

**Issue by Shuggadugga** [chrippa/livestreamer#683]
It looks like MLG has begun rolling out some changes again.

I'm currently running Puppy Linux, but I've been getting the same error across my Windows and OSX partitions as well. I type in the same command to start the streams as I always have: `"livestreamer mlg.tv/*activestreamhere* best"` and get this each time: `"error: Unable to open URL: http://www.majorleaguegaming.com/player/config.json (404 Client Error:Not Found)"`

I've tried some different variations on the url, made sure the streams were active, and tried different resolutions to no avail. This error doesn't come up for all streams though. These are the broken streams that I've come across: (mlg.tv/nadeshot -- mlg.tv/opticgaming -- mlg.tv/esr). These, as of yesterday, are working as they always have: (mlg.tv/formal -- mlg.tv/mboze).

**Comment by KaDe-** [comment]
Have the same issue! and unfortunatly scumps stream also doesnt work :(, Big fan of optic gaming and hope theres a way to fix all streams
