### ISSUE TITLE
Can't use livestreamer anymore with MLG.TV

### ISSUE THREAD

**Issue by Mrfatmanjunior** [chrippa/livestreamer#691]
Just tried watching a stream on mlg.tv via livstreamer and it didn't work.

I use w7 and the latest livestreamer version.

i type the command "livestreamer mlg.tv/nadeshot best" in and it gives me this error http://gyazo.com/ac281985d875259c528408670d2772ec

EDIT: tried to do stream some other streams and i found that it only accurs on the nadeshot and scump channel. but on the scump channel it gives a different error. Other streams seems to just work fine. http://gyazo.com/d70a8a9e6374afb6375887f8e1ed5a04

**Comment by desg** [comment]
also ran into this same issue trying to watch the channel mlg.tv/moe

**Comment by chrippa** [comment]
Please try the [nightly/git version](http://docs.livestreamer.io/install.html), this is probably the samme issue that #686 fixed.

**Comment by Mrfatmanjunior** [comment]
@chrippa what do i need to do with the files? sorry if that is a dump question.

**Comment by zp** [comment]
Certain channels still appear to be broken, just updated my nightly build to what I assume should be git version 5c268a0 - and I still get the json 'media' error for mlg.tv/moe

````
[cli][info] Found matching plugin mlgtv for URL mlg.tv/moe
error: Unable to validate JSON: Key 'media' not found in {u'services': {u'playback': u'streamapi.majorleaguegaming.com'}, u'version': u'1.0', u'modules': [{u'id': u'bridge'}, {u'id': u'osmf'}, {u'params': {u'feedbackUrl': u'http://www.majorleaguegaming.com/streamfeedback', u'invisibleControls': [u'seekBar', u'timeGroup'], u'seekOnDrag': False}, u'id': u'controls'}, {u'params': {u'interval': 10000, u'service': u'http://realtime.majorleaguegaming.com/ad-manifests-delay-30/'}, u'id': u'poller'}, {u'params': {u'pService': u'//player-stats-origin.majorleaguegaming.com/channel/', u'pInterval': 30000, u'sampling': 50, u'gService': u'//streamapi.majorleaguegaming.com/service/streams/status/', u'gInterval': 45000}, u'id': u'channel'}, {u'params': {u'enableMid': True, u'enablePre': True, u'eaab': True, u'muteOnAd': True, u'invisibleMode': False, u'publisherId': u'73025'}, u'id': u'liverail'}, {u'params': {u'c2': u'14997743', u'c6': u'mlg_live'}, u'id': u'comScore'}]}
````
