### ISSUE TITLE
Saved RTMP Stream to file can't seek 

### ISSUE THREAD

**Issue by ArchUser** [chrippa/livestreamer#692]
So I used livestreamer to save a rtmp stream that I had to a file. I turned off the saving couple hours later but I can't move forward or back on the video unlike saved twitch stream. Is there a way to fix this or transcode it? Only thing I can do is speed up or slow down the playback. it's like using a vhs.

**Comment by chrippa** [comment]
This is probably the same issue as #232, try using [this script](https://gist.github.com/chrippa/7772802) to repair your files.

**Comment by ArchUser** [comment]
How do I run that script when I installed livestreamer with exe on windows? I get "no module named livestreamer.package error.

**Comment by ArchUser** [comment]
For people who are having this issue use FLVExtract + MP4Box. Grab it from here.

http://www.videohelp.com/tools?toolsearch=FLVExtract&submit=Search&portable=&s=&orderby=Name&hits=50

IMPORTANT: Get  FLV Extract 2.2.0 jofori89 (direct link) under "more downloads". This version will remux it losslessly (not trascoding) into an MP4 file in couple seconds. You can then do whatever you want with the file (edit in video editor, seek forward backwards etc. It's a normal MP4 file. There is also an option to remux to .MKV if desired.
