### ISSUE TITLE
Feature: twitch.tv / justin.tv archived video (VOD) support

### ISSUE THREAD

**Issue by janickm** [chrippa/livestreamer#70]
Hi!

I am wondering if it could be possible to extend the justin.tv plugin to also support archived videos that have urls like

http://nl.twitch.tv/jeffroiscool/b/299079587

The important part is the 299079587 video id. This ID can be used with the twitch.tv api to obtain the video url by, e.g.,

http://api.justin.tv/api/clip/show/299079587.xml

(see http://www.fakegaming.eu/TwitchTV/source/download.txt / http://www.fakegaming.eu/TwitchTV/download.php for a php implementation). Perhaps there is also another way to do this using some established livestreamer features. I primarily want to use it to automatically download archived videos to watch them, e.g., on my mobile phone.

**Comment by kaptainjak** [comment]
> It seems that "time feature" doesn't work everytime, some videos always start at the beginning.

I don't know if something changed and broke but this has been happening a lot lately, and I used to never have this problem.

The source is not flv_playlist but instead hls.

**Comment by aleksijuvani** [comment]
I'm also having trouble getting this to work with "past broadcasts". [Here's the video that I tried this on.](http://www.twitch.tv/angryjoeshow/v/5158018?t=118m10s)

**Comment by Joopiter** [comment]
Yeah, it is still not working for me at most videos, even with latest realese.

**Comment by skulblakka** [comment]
Twitch uses two different systems for VODs. One is HLS based and the other one is Flash based. While you should be able to use the time parameter on the Flash based VODs it will not work on the HLS based one because Livestreamer does currently not support HLS seeking.

**Comment by DerpDarako** [comment]
Ok thank you for this information, because this issue is very annoying... :(

**Comment by aleksijuvani** [comment]
As a workaround, I've found that you can use the player-passthrough command with MPC-HC and then you're able to seek the video in the player. I couldn't get it to work with VLC though.

```
livestreamer --player-passthrough hls --player "C:\Program Files\MPC-HC\mpc-hc64.exe" www.twitch.tv/angryjoeshow/v/5158018 best
```

**Comment by Joopiter** [comment]
@aleksijuvani It is not working for me. Video still starts always at the beginning, no matter if I use VLC or MPC-HC.

BTW you didn't add time stomp to the link in your code.

**Comment by aleksijuvani** [comment]
Oh, it'll still start at the beginning, but I was able to seek to the middle of the video with that bar at the bottom.

![this thing](http://files.1337upload.net/stufff-5cb908.png)

The timestamp is not needed when using this method. I'm using version 1.7.8 (6fcba1b) of MPC-HC. Maybe it doesn't work on older versions? Oh, and I think the video has to use the newer HLS format for this to work.

**Comment by Joopiter** [comment]
Oh, right, I didn't notice. It's working, for my video at least, thanks :)

**Comment by Hubro** [comment]
Seeking in VODs using hls passthrough also works in VLC 2.2.0 on Linux, but there are no time stamps. The current and end time just say "00:00:00".

**Comment by MaddXav** [comment]
I'm getting the same issue. No timestamps on VLC, and adding the timestamp to the video url still makes it start at beginning.

**Comment by famousketchup** [comment]
Are there any updates on VLC timestamp issue? Player-passthrough parameter works for enabling seeking, but still no exact time
