### ISSUE TITLE
Some twitch streams not loading video.

### ISSUE THREAD

**Issue by ROMaster2** [chrippa/livestreamer#700]
http://www.twitch.tv/marioman847/popout

For some reason the video from this stream won't load at ALL in Livestreamer, even when I updated Media Player Classic - Home Cinema. Other streams load just fine, just not this one. I'm wondering if it has something to do with his encoding? His highlights load just fine, but not the actual stream.

**Comment by chrippa** [comment]
Try one of the workarounds listed [here](http://docs.livestreamer.io/players.html#mpc-hc-only-plays-sound-on-twitch-streams). If that doesn't help, try another player.

**Comment by sammpo** [comment]
This also happened to me when trying to watch an mlg livestream. It only occured when selecting anything else but best and worst as the quaity. But yeah, the workaround works.
