### ISSUE TITLE
Ads on twitch

### ISSUE THREAD

**Issue by Circlebit** [chrippa/livestreamer#702]
I'm watching a lot of rocketbeanstv, a 24/7 live stream on twitch. As I understand they aren't earning any money by me watching the stream via livestreamer because I don't see the Ads. I want to support the guys by watching Ads but I need tools in my setup that only VLC offers. Would it be possible for livestreamer to display the Ads between the shows in VLC or something like that?

**Comment by chrippa** [comment]
To display the ads Flash must be be used and the whole reason Livestreamer exists in the first place is to avoid having flash installed at all, so no, it's not possible. If you want to support streamers use the flash player or donate directly.
