### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by raidprotector** [chrippa/livestreamer#704]
I just can't understand

Download a m3u8 file called master-playlist

Source: http://live.hls.globo.com/dvr/bbb01/master-playlist.m3u8?h=0401421802702466628773814218061826292869304qjpeSKkiYBnFL8_58EzgfQ&k=html5&a=F&u=583870

So livestreamer hlsvariant://http://live.hls.globo.com/dvr/bbb01/master-playlist.m3u8 best

Bad Request

Change to livestreamer hls://live.hls.globo.com/dvr/bbb01/master-playlist.m3u8 best

Bad request

The content of the file is: #EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=264000
bbb01_264/playlist.m3u8

Another change livestreamer hls://live.hls.globo.com/dvr/bbb01/bbb01_264/playlist.m3u8 best

Another bad request. I don't know what I'm doing wrong.

Using livestreamer 1.10.2

**Comment by chrippa** [comment]
It looks like you're cutting off important parts of the URL.

**Comment by raidprotector** [comment]
Where? After m3u8?

Because if I try livestreamer hls://live.hls.globo.com/dvr/bbb01/bbb01_264/playlist.m3u8?h=0401421802702466628773814218061826292869304qjpeSKkiYBnFL8_58EzgfQ&k=html5&a=F&u=5838709

The aswer is: 'k' is not recognized... 'a' is not recognized...

And if I remove that part "&k=html5&a=F&u=5838709" then give me Bad Request again.

**Comment by chrippa** [comment]
& is used by the shell. You need to quote the URL in "" or ''.

**Comment by raidprotector** [comment]
Nothing yet

livestreamer "hls://live.hls.globo.com/dvr/bbb01/bbb01_264/playlist.m3u8?h=0401421802702466628773814218061826292869304qjpeSKkiYBnFL8_58EzgfQ&k=html5&a=F&u=5838709" best

Now the error is 403: Forbidden

**Comment by chrippa** [comment]
The stream URL has probably expired or requires [cookies/headers](http://docs.livestreamer.io/cli.html#http-options) to be passed.

**Comment by raidprotector** [comment]
So, if a stream needs login/pass, needs this cookies/header option? How it works?

livestreamer --http-cookie "URL" best

**Comment by chrippa** [comment]
You will have to research what cookies or headers are needed, it's different for each service. The web developer tools in your browser are useful for this.
