### ISSUE TITLE
 No data returned from stream

### ISSUE THREAD

**Issue by assoft** [chrippa/livestreamer#705]
Stream: hitbox

Return: 
[cli][info] Available streams: 1000k, 1080p (best), 2000k, 360p, 480p, 500k (worst), 720p
[cli][info] Opening stream: 360p (rtmp)
[cli][error] No data returned from stream

**Comment by chrippa** [comment]
There has been som changes to the Hitbox plugin since 1.11.1 was released, please try the latest [nightly/git version](http://docs.livestreamer.io/install.html).

**Comment by xerc** [comment]
@ livestreamer-v1.11.1-41-g5c268a0 [w7-32]: stream "best" is not mapped correct
```
$ livestreamer http://www.hitbox.tv/teamgravity 720p
[cli][info] Found matching plugin hitbox for URL http://www.hitbox.tv/teamgravity
[cli][info] Available streams: 360p (worst), 480p, 720p, live (best)
[cli][info] Opening stream: 720p (rtmp)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000
[cli][info] Player closed
[cli][info] Stream ended

$ livestreamer http://www.hitbox.tv/teamgravity best
[cli][info] Found matching plugin hitbox for URL http://www.hitbox.tv/teamgravity
[cli][info] Available streams: 360p (worst), 480p, 720p, live (best)
[cli][info] Opening stream: live (rtmp)
[cli][error] No data returned from stream
```

**Comment by Wapniak** [comment]
nightly build works:
livestreamer-v1.11.1-41-g5c268a0>livestreamer.exe hitbo
x.tv/yuuhi 1080p
[cli][info] Found matching plugin hitbox for URL hitbox.tv/yuuhi
[cli][info] Available streams: 1000k, 1080p (best), 2000k, 360p, 480p, 500k (wor
st), 720p
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'

**Comment by assoft** [comment]
Help me!

How to update to nightly build on mac?

**Comment by skulblakka** [comment]
Try ```pip install -U git+https://github.com/chrippa/livestreamer.git```

**Comment by assoft** [comment]
@skulblakka Thank you very much.

**Comment by chrippa** [comment]
1.12.0 is now out and should fix all issues.
