### ISSUE TITLE
Best quality options don't show up while streaming from Youtube.

### ISSUE THREAD

**Issue by Khrone90** [chrippa/livestreamer#707]
As for title.
When trying to stream a video from Youtube, which of course has up to 1080p60fps in the options, livestreamer returns all the quality streams correctly flagged (the lowest is "worse" quality) but the highest one, which is always 720p (30 fps). It doesn't even show higher qualities.

This is only happening with videos from Youtube, other services, like Twitch, are working fine.

**Comment by skulblakka** [comment]
Everything above 720p is currently not supported. See #223

**Comment by Khrone90** [comment]
I didn't see the other threads. I'm sorry for the redundant question.
Thanks for the help anyway.
