### ISSUE TITLE
Still a problem with MLG.tv

### ISSUE THREAD

**Issue by KaDe-** [chrippa/livestreamer#708]
So theres afew MLG streams that cannot be watched through the plugin (livestreamer.exe) and I dont know how to fix this... I was refered to a thread with the same issue and was given a Solution which i couldnt understand and was wondering if there was a video of some sort to help?

**Comment by Shuggadugga** [comment]
Made you a quick tutorial man! Hope it fixes your issues. 

https://www.youtube.com/watch?v=JnefvV8XOu8&feature=youtu.be

**Comment by KaDe-** [comment]
I dont know what im doing wrong, Even after copying everything you did im still getting the same error! http://gyazo.com/ccb24f4b4ddf2525599b142d5f686c9a

**Comment by KaDe-** [comment]
never mind dude, it worked! thanks alot for the help
