### ISSUE TITLE
Hitbox stream not working.

### ISSUE THREAD

**Issue by Wapniak** [chrippa/livestreamer#712]
1.11.1 version, just reinstaled on windows :
livestreamer hitbox.tv/yuuhi 1080p
[cli][info] Found matching plugin hitbox for URL hitbox.tv/yuuhi
[cli][info] Available streams: 1080p (best), 360p (worst), 480p, 720p, live
[cli][info] Opening stream: 1080p (rtmp)
[cli][error] No data returned from stream
On all hitbox streams phraps from week :(

**Comment by ptkovsky** [comment]
Hitbox plugin still having issues I guess.
>livestreamer http://www.hitbox.tv/efragtv best
[cli][info] Found matching plugin hitbox for URL http://www.hitbox.tv/efragtv
[cli][info] Available streams: 360p (worst), 480p, 720p, live (best)
[cli][info] Opening stream: live (rtmp)
[cli][error] No data returned from stream

>livestreamer -j http://www.hitbox.tv/efragtv best
{
  "params": {
    "playpath": "/api/player/hls/efragtv.m3u8",
    "pageUrl": "http://www.hitbox.tv/efragtv",
    "live": true,
    "rtmp": "http://edge.hls.dt.hitbox.tv/hls",
    "swfVfy": "http://edge.vie.hitbox.tv/static/player/flowplayer/flowplayer.com
mercial-3.2.16.swf"
  },
  "type": "rtmp"
}
