### ISSUE TITLE
Allow multiple player-args to be specified.

### ISSUE THREAD

**Issue by Earnestly** [chrippa/livestreamer#714]
Currently I configure livestreamer to use `mpv` with `--profile=live`.  The configuration file looks as follows:
```
player=mpv
player-args=--profile=live
```

I have a script which fetches a title from imported data that I would also like to pass when launching livestreamer.

`livestreamer --player-args "--title=$title" "$url"`

However when attempting to do this `mpv` fails with a usage error.

The expected result would be `mpv --profile=live --title='a title' http://theurl` but something seems to be going wrong.

It may be a problem on my end with how spaces are handled however when testing without spaces in the title argument I get the following error:

`livestreamer: error: argument -a/--player-args: expected one argument`

Would it be possible to allow `-a, --player-args` to be specified multiple times?

Edit: The constructed livestreamer argument resembles the following:
`livestreamer -v --player-args '--title=Wizards & Warriors: Nes Wizards&Warriors practice runs for marathon race' http://twitch.tv/badbrakes`

**Comment by chrippa** [comment]
Try this in your config:

    player=mpv --profile=live

You don't need to use `--player-args` to pass arguments to the player generally.

Then use this in your script:

    livestreamer --player-args "--title='$title' {filename}" "$url"

The title needs to be quoted or it will end up as `--title=a title with spaces`, which mpv will see as `--title=a` and then the reset ends up being positional arguments.

**Comment by Earnestly** [comment]
That still results in a usage error as `mpv` seems to be trying to open each word as a file, e.g.
```
teapot earnest %i master ~ livestreamer -v --player-args --title='Title with spaces.' http://twitch.tv/thekotti 
[cli][info] Found matching plugin twitch for URL http://twitch.tv/thekotti
[cli][info] Available streams: audio, high, low (worst), medium, source (best)
[cli][info] Opening stream: high (hls)
[cli][info] Starting player: mpv --profile=live
Playing: with
[file] Cannot open file 'with': No such file or directory
Failed to open with.

Playing: spaces.
[file] Cannot open file 'spaces.': No such file or directory
Failed to open spaces..


Exiting... (Errors when loading file)
error: Failed to start player: mpv --profile=live (Process exited prematurely)
```

**Comment by Earnestly** [comment]
Yup, the use of {filename} is what I was missing here.  I don't know if this is the intended interface for setting player-args instead of relying on the url being at the end, but it works and solves my issue so thanks.
