### ISSUE TITLE
Youtube 60 Fps support

### ISSUE THREAD

**Issue by Anonymous1783** [chrippa/livestreamer#719]
Hi, not sure if an issue or a feature request, but livestreamer doesn't recognize 60fps quality avaible for some youtube videos.

Since firefox support is still experimental and I can't watch 60fps gameplays on it and I do not want install chrome, this support would be very useful for me.

p.s. if you don't know what I am talking about enable "media.mediasource.enabled" from about:config and you'll see the 60fps quality in video options (for videos that support it, just search a 60fps gameplay to see it)

**Comment by skulblakka** [comment]
See #223

**Comment by chrippa** [comment]
Not possible until we support MPEG-DASH, we'll use #223 to track the issue.
