### ISSUE TITLE
cannot set player args with mpv

### ISSUE THREAD

**Issue by WatermelonDriveway** [chrippa/livestreamer#726]
trying to set :
--player-args screen=2 geometry=+50+50

and get:
error: Failed to start player: /Applications/mpv.app/Contents/MacOS/mpv (Process exited prematurely)

mpv works fine with no arguments, but if i put --player-args with no arguments it tells me it is expecting an argument

**Comment by chrippa** [comment]
You must include `{filename}` somewhere in the [--player-args](http://docs.livestreamer.io/cli.html#cmdoption-a) or mpv will not know what to play. 
It’s usually enough to just use [--player](http://docs.livestreamer.io/cli.html#cmdoption-p) instead though, unless you need to add arguments after the filename.

For example,  `--player 'mpv --screen=2 --geometry=+50+50'`.

**Comment by WatermelonDriveway** [comment]
Thank you!
