### ISSUE TITLE
more channel issues on MLG.tv

### ISSUE THREAD

**Issue by KaDe-** [chrippa/livestreamer#736]
There are now more MLG issues when trying to watch certain streams, afew weeks ago the same problem happened with different streams and that was resolved, Anyone got a new fix for this one 
(channels like mlg.tv/bigtymer) are affected

**Comment by jmccarroll** [comment]
You need to pull the new repo. I was having the same problems and got it fixed.

Run this:
$ git pull git://github.com/chrippa/livestreamer.git

**Comment by KaDe-** [comment]
I dont quite understand this, is there a youtube video of sort?

**Comment by bitfl1pper** [comment]
KaDe- are you still having this issue? I might be able walk you through if you need help

**Comment by bitfl1pper** [comment]
I'm assuming you are unfamiliar with git, the main issue is that you need to get the latest development version of this software. I might be able to help walk you through that

**Comment by KaDe-** [comment]
Yes i am still having issues with this, a simple youtube would be much appreciated!

**Comment by chrippa** [comment]
1.12.0 is now out and should fix all issues.
