### ISSUE TITLE
mlg.tv 

### ISSUE THREAD

**Issue by KaDe-** [chrippa/livestreamer#745]
There is a Call of Duty tournemant this weekend and is being streamed on (mlg.tv/COD) but can not watch this using livestreamer.exe

Any fix?

**Comment by chrippa** [comment]
What error are you getting?

**Comment by KaDe-** [comment]
Im getting this error, http://gyazo.com/cf9e7a3b1ee75c380fd9fb09817251d0 also it happens with mlg.tv/bigtymer

**Comment by chrippa** [comment]
I believe this issue has been fixed, but not put out in a release yet. Please try the [nightly build](http://docs.livestreamer.io/install.html#nightly-build).

**Comment by chrippa** [comment]
1.12.0 is now out and should fix all issues.
