### ISSUE TITLE
Livestreamer doesn't accept any command in the CLI

### ISSUE THREAD

**Issue by rflensted** [chrippa/livestreamer#746]
Using Livestreamer 1.11.1 on OS X 10.9.5, I can't seem to use any command in terminal. Specifically I am trying to specify config file location using:

livestreamer --config [FILE PATH]

but it simply returns a list of the available commands.
 I might be a complete idiot and have missed an integral instruction on how to properly do this, but I can't figure it out.

**Comment by chrippa** [comment]
Livestreamer will print the help if you do not specify a stream and quality to watch. See the [tutorial](http://docs.livestreamer.io/cli.html#tutorial) for more information.

**Comment by mtlam7** [comment]
I'm also having the same issue, I just want to set the default player as MPV instead of VLC using a config file.

**Comment by chrippa** [comment]
> I'm also having the same issue, I just want to set the default player as MPV instead of VLC using a config file.

You don't need to use the `--config` option to use a config, it's only if you want to use a custom location. See [configuration file](http://docs.livestreamer.io/cli.html#configuration-file) for more information.

**Comment by ThoWoKi** [comment]
@mtlam7 you need to specify the full path!
