### ISSUE TITLE
[Twitch] API query returns a 404 "Transcode does not exist"

### ISSUE THREAD

**Issue by zer0def** [chrippa/livestreamer#749]
So apparently there are some new shenanigans going on, as attempts to view ESLtv_Hearthstone result in a 404 "Transcode does not exist" reply, along with the channel query path and string, while the stream itself is live. This effectively leaves Livestreamer not finding streams for the URI.

**Comment by skulblakka** [comment]
Can't can confirm. Works perfect on my end.

Note: The stream is actually located at /esl_hearthstone not /esltv_hearthstone

**Comment by zer0def** [comment]
Used to run under the latter, but apparently some people like their stream display names linger. Closed
