### ISSUE TITLE
Major buffering issues

### ISSUE THREAD

**Issue by premiumhostingwebdotcom** [chrippa/livestreamer#751]
Hi,
I am capturing a stream from "doiptv.com" with permission from the server owner. The problem is that when I capture it, after a few minutes I get major buffering issues and then skmetimes I get a DTS error saying the Timestamp has changed so it may affect the output file. I have to use linux command "screen -r CHANNELNAME ctrl-c" to restart it.
I use Livestreamer and then generate the rtmp with Flussonic.
On the flussonic UI, i get lots of delays.

I capture the m3u8 like this:

**Comment by premiumhostingwebdotcom** [comment]
livestreamer --yes-run-as-root   -O --http-header User-Agent=stagefright "hls://$url" best | ffmpeg -i pipe:0  -acodec aac -strict -2 -vcodec copy  -rtmp_buffer 100 -rtmp_live live  -f flv rtmp://94.23.2.165:1935/digitele/$streaming

**Comment by premiumhostingwebdotcom** [comment]
Is there any way of adding a prebuffer like in p2p so if the server does overload a bit, it wont affect the playback of the generared m3u8..?

**Comment by chrippa** [comment]
> Is there any way of adding a prebuffer like in p2p so if the server does overload a bit, it wont affect the playback of the generared m3u8..?

No, if you want pre-buffering it should be done by the application consuming the stream (there is probably a option in ffmpeg for this). You can also try using [multi-threaded streaming](http://docs.livestreamer.io/cli.html#cmdoption--hls-segment-threads).
