### ISSUE TITLE
No plugin can handle URL: http://www.tv4play.se/kanaler/tv4

### ISSUE THREAD

**Issue by Valle641** [chrippa/livestreamer#754]
Hi, i got problems with watching TV4 Play, it just says: "No plugin can handle URL: http://www.tv4play.se/kanaler/tv4" or any tv4 play URL i put in altho it acording to the plugin page it should be supported, am i doing something wrong?

Here is the script: (Yes i tried without http and it still didn't work)
@echo
livestreamer.exe http://www.tv4play.se/kanaler/tv4
@echo off
pause

**Comment by chrippa** [comment]
The tv4play plugin does not support premium streams currently. But even if it did, it would not help as the streams for the channels are encrypted using the DRM technology widevine.

**Comment by Valle641** [comment]
ow, thanks for the info, you should include that in the note section tho.
