### ISSUE TITLE
Can't open any stream

### ISSUE THREAD

**Issue by Thehail** [chrippa/livestreamer#764]
When I try to open any stream with Livestreamer, it says (in my language, from part of Windows 8) 
"No se puede ejecutar esta aplicación en el equipo
Para buscar una versión para su equipo, consulte con el editor del software."

Translated into English is this:
"You can not run this application on your computer
To find a version for your computer, contact the software publisher."

What I should do?

Screenshot:
![s](https://cloud.githubusercontent.com/assets/11244301/6426127/6d0865de-bf41-11e4-99c4-9690676b5cdc.png)

**Comment by VackerSimon** [comment]
How do you run it?

**Comment by balexandre** [comment]
@Thehail it's a command line application, it does not open with double click.

do this simple steps:

1 - Create a folder called `livestreamer` in your `C:` directory
2 - put the `.exe` inside that directory
3 - holding the <kbd>SHIFT</kbd> key right click inside that directory and choose `Open command window here`
4 - in that new black command window write: `livestreamer twitch.tv/day9tv best` or change `twitch.tv/day9tv` to the stream you need

**Comment by Thehail** [comment]
@VackerSimon throught windows command interface (cmd)
@balexandre which .exe?

**Comment by balexandre** [comment]
@Thehail  

Download the [Windows binaries](http://docs.livestreamer.io/install.html#windows-binaries) and install it to `C:\Livestreamer` the `.exe` will be there

Also, remember to open the configuration file (it will ask when you finish installing) so you point the `player` variable to the correct path of your **VLC installation**.

**Comment by Thehail** [comment]
Executed the .exe but show some text that I can't read and close inmediatly. Then I tried to open normally an stream but stil doesn't work

**Comment by Thehail** [comment]
Okey, this works but I'll need to open a command line in the folder all times I want to play a stream with livestreamer?

**Comment by balexandre** [comment]
> Okey, this works but I'll need to open a command line in the folder all times I want to play a stream with livestreamer?

Yes, hence the `command line` part. You can also create a `.bat` that you can then double click.

**Comment by Thehail** [comment]
Can you explain me how to do this? @balexandre

**Comment by balexandre** [comment]
sure:

1 - create an empty text file in the same directory and name it `streamer.bat`
2 - open it with `notepad` or any text editor and write:

    livestreamer twitch.tv/day9tv best
    pause

3 - save, close, and double click to open `twitch.tv/day9tv`

**Comment by Thehail** [comment]
But I want it to put any stream url not only one it is possible?

**Comment by balexandre** [comment]
edit the file or have more files...

It's a command line, you need to act accordingly.

**Comment by Thehail** [comment]
There isn't any .bat to open the console like shift + right click in the folder?
