### ISSUE TITLE
Error, livestreamer was not found

### ISSUE THREAD

**Issue by teghwar** [chrippa/livestreamer#767]
Error livestreamer was not found
Please check settings and or reinstall livestreamer.

So I installed it, load the gui, click a stream i want to watch and get the above message.
Have reinstalled, same error.

Any help please?

**Comment by chrippa** [comment]
It sounds like you're trying to use a GUI made for Livestreamer, but this project does not include one. I suggest you find the issue tracker for the GUI you're using and report your issue there instead.

**Comment by teghwar** [comment]
Hmm so how do you get livestreamer to work?

**Comment by chrippa** [comment]
See [Installation](http://docs.livestreamer.io/install.html) and [Tutorial](http://docs.livestreamer.io/cli.html#tutorial).

**Comment by teghwar** [comment]
Thanks pal
