### ISSUE TITLE
streamlive.to livestreamer 1.12.0

### ISSUE THREAD

**Issue by expandables2** [chrippa/livestreamer#769]
Hi i updated to the new livestreamer version and streamlive.to still does not work.

[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] No data returned from stream

**Comment by VackerSimon** [comment]
Make sure you don't have the old version still installed.

**Comment by chrippa** [comment]
Ah, the changelog is a bit wrong. After 1.11.1 the plugin was fixed and the changelog updated, but since then it was broken again (#739) which has not been fixed yet. We'll use #739 to track the latest problem.
