### ISSUE TITLE
new livestreamer update...

### ISSUE THREAD

**Issue by KaDe-** [chrippa/livestreamer#770]
Now that the new livestreamer update has been installed all of my MLG.tv problems have been fixed. But now its saying that no plugin can handle twitch.tv ?

**Comment by karlo2105** [comment]
I am on the latest release and Twitch is working fine. 

<code>
livestreamer "http://www.twitch.tv/ogamingtv" best
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/ogamingtv
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source
(best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'
[cli][info] Player closed
[cli][info] Stream ended
</code>

**Comment by Kiwical** [comment]
mine wont show best, it will show high but best or source it flickers and shows nothing but has audio

**Comment by chrippa** [comment]
Works fine here, try uninstalling, double check everything is removed from the install folder and then install again.
