### ISSUE TITLE
Failed to load playlist

### ISSUE THREAD

**Issue by sonnvl** [chrippa/livestreamer#772]
D:\livestreamer>livestreamer "hlsvariant://http://112.197.2.154/mlive/C047_SD_4/playlist.m3u8 params={'us':'ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b970
6b1cea3768adb0121213efcc5cec86760e3cc4d269f4|1694277'} verify=False" best -o NLCC.ts

[cli][info] Found matching plugin stream for URL hlsvariant://http://112.197.2.154/mlive/C047_SD_4/playlist.m3u8 params={'us':'ae54e041709292302aa98ad79011ffd1e
b83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4|1694277'} verify=False
[cli][info] Available streams: 720p (worst, best)
[cli][info] Opening stream: 720p (hls)
[download][NLCC.ts] Written 29.4 MB (1m27s @ 310.6 KB/s)                       
[stream.hls][warning] Failed to reload playlist: Unable to open URL: http://112.197.2.154/mlive/C047_SD_4/chunklist_w946306893.m3u8?us=ae54e041709292302aa98ad790
11ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (HTTPConnectionPool(host='112.197.2.154', port=80): Max retries exceeded with url: /mlive/C047_SD_4/chunklist_w946306893.m3u8?us=
ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (Caused by <class 'httplib.BadStatusLine'>: ''))
[stream.hls][warning] Failed to reload playlist: Unable to open URL: http://112.197.2.154/mlive/C047_SD_4/chunklist_w946306893.m3u8?us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (HTTPConnectionPool(host='112.197.2.154', port=80): Max retries exceeded with url: /mlive/C047_SD_4/chunklist_w946306893.m3u8?us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (Caused by <class 'socket.error'>: [Errno 10061] No connection could be made because the target machine actively refused it))
[stream.hls][warning] Failed to reload playlist: Unable to open URL: http://112.197.2.154/mlive/C047_SD_4/chunklist_w946306893.m3u8?us=ae54e041709292302aa98ad79
011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (HTTPConnectionPool(host='112.197.2.154', port=80): Max retries exceeded with url: /mlive/C047_SD_4/chunklist_w946306893.m3u8?us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (Caused by <class 'socket.error'>: [Errno 10061] No connection could be
made because the target machine actively refused it))
[stream.hls][warning] Failed to reload playlist: Unable to open URL: http://112.197.2.154/mlive/C047_SD_4/chunklist_w946306893.m3u8?us=ae54e041709292302aa98ad79
011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (HTTPConnectionPool(host='112.197.2.154', port=80): Max retries exceeded with url: /mlive/C047_SD_4/chunklist_w946306893.m3u8?us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (Caused by <class 'socket.error'>: [Errno 10061] No connection could be
made because the target machine actively refused it))
[stream.hls][error] Failed to open segment 58963: Unable to open URL: http://112.197.2.154/mlive/C047_SD_4/media_w946306893_58963.ts?us=ae54e041709292302aa98ad7
9011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (403 Client Error: Forbidden)
[stream.hls][error] Failed to open segment 58963: Unable to open URL: http://112.197.2.154/mlive/C047_SD_4/media_w946306893_58963.ts?us=ae54e041709292302aa98ad7
9011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (403 Client Error: Forbidden)
[stream.hls][warning] Failed to reload playlist: Unable to open URL: http://112.197.2.154/mlive/C047_SD_4/chunklist_w946306893.m3u8?us=ae54e041709292302aa98ad79
011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277&us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (403 Client Error: Forbidden)
[stream.hls][error] Failed to open segment 58963: Unable to open URL: http://112.197.2.154/mlive/C047_SD_4/media_w946306893_58963.ts?us=ae54e041709292302aa98ad7
9011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (403 Client Error: Forbidden)
[stream.hls][error] Failed to open segment 58964: Unable to open URL: http://112
.197.2.154/mlive/C047_SD_4/media_w946306893_58964.ts?us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4%7C1694277 (403 Client Error: Forbidden)

[cli][error] Error when reading from stream: Read timeout
[cli][info] Stream ended

How can I fix this error?

**Comment by sonnvl** [comment]
Original link: http://112.197.2.154/mlive/C047_SD_4/playlist.m3u8?us=ae54e041709292302aa98ad79011ffd1eb83f68c94a01b39b9706b1cea3768adb0121213efcc5cec86760e3cc4d269f4|1694277

**Comment by chrippa** [comment]
> 403 Client Error: Forbidden

This usually means there is some security precautions stopping you from accessing the stream. In this case since it worked for a while it might be using some kind of heartbeat to verify your access continously.
