### ISSUE TITLE
Unable to watch Twitch VODS

### ISSUE THREAD

**Issue by ughpls** [chrippa/livestreamer#777]
The command line manages to open the player(VLC) but nothing happens from there at all

**Comment by nicolas-besnard** [comment]
Same problem here for live stream 
````
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[cli][info] Player closed
[cli][info] Stream ended
```

**Comment by chrippa** [comment]
> Can be caused by the new version of VLC ?

Does it help if you downgrade VLC?

**Comment by nicolas-besnard** [comment]
@chrippa The problem appear right after upgrading VLC to 2.2.0

**Comment by nicolas-besnard** [comment]
@chrippa I just install VLC 2.1.5, and it's now working !

**Comment by ughpls** [comment]
@chrippa I have VLC 2.0.1 and the VODs still will not work.

**Comment by chrippa** [comment]
> @chrippa I have VLC 2.0.1 and the VODs still will not work.

Can you give an example URL?

**Comment by ughpls** [comment]
http://www.twitch.tv/riotgames/b/633389165

I just tried that one, but none of them work.

**Comment by chrippa** [comment]
Works fine for me with both VLC 2.1.5 and 2.2.0.

**Comment by ughpls** [comment]
Maybe its an issue with 2.0.1? But I can't seem to get it to update through the auto updater built into VLC. If I uninstall VLC in order to get the most up to date one, will I also need to re-install Livestreamer?

**Comment by chrippa** [comment]
> If I uninstall VLC in order to get the most up to date one, will I also need to re-install Livestreamer?

No, Livestreamer has no special connection to any player, VLC just happens to be the default.

**Comment by ughpls** [comment]
@chrippa I uninstalled my presumably bugged VLC and reinstalled it. Didn't touch Livestreamer per your instructions(guide I followed initially said VLC needed to be installed before Livestreamer) and it now works properly with VLC 2.2.0. Thank you.
