### ISSUE TITLE
hls option with command line

### ISSUE THREAD

**Issue by idealsat** [chrippa/livestreamer#782]
Hi
 
I running livestreamer working good.
 
How i can add option in command line.
 
Example : These options of  hls   ( --hls-live-edge SEGMENTS  --hls-segment-attempts ATTEMPTS  --hls-segment-threads THREADS ).
 
For more ( http://docs.livestre...--hls-live-edge )
 
My url example
 
livestreamer http://mydomain.com/playlist.m3u8 segments=5 attempts=20
 
Is it working like this .? or how i can put hls option with command line.?
 
Thanks

**Comment by skulblakka** [comment]
>Is it working like this?

No. You also need to enter the "--" part. Your example would look like:
```
livestreamer http://mydomain.com/playlist.m3u8 --hls-live-edge 5 --hls-segment-attempts 20
```

**Comment by idealsat** [comment]
Hi

Many thanks for your reply

i try like this but ( livestreamer http://mydomain.com/playlist.m3u8 --hls-live-edge 10 )

but its not working.

what i want when m3u8 load then its start download before 10 chunks. Not last 3 as it default value.

How i can fix this .

And which livestreamer version support this i have 1.8.

Thanks

**Comment by chrippa** [comment]
Are you getting a error? If not, check that the stream actually has that many segments available in its playlist.

**Comment by idealsat** [comment]
i not getting error but it run from last 3 segments . 

i running my own playlist server so i can control segments how many avaiable.

Which livestreamer version support command line parameters ( ( livestreamer http://mydomain.com/playlist.m3u8 --hls-live-edge 10 ) .?

Thanks

**Comment by chrippa** [comment]
It was added in 1.8. If you're not getting an error then you're using a version that supports it. Can you link the stream you're trying?

**Comment by idealsat** [comment]
Hi

Here is link  ( http://idealoglx.zapto.org/testhls/ ). This link you can watch total segments. example 885 to 924.

And you can play with this  ( http://idealoglx.zapto.org/testhls/playlist.m3u8 ).

This time its playing video from segment number 921.

Thanks

**Comment by chrippa** [comment]
Works fine here. `--hls-live-edge=10` plays from segment 915.

**Comment by idealsat** [comment]
Are you put like this ( livestreamer http://idealoglx.zapto.org/testhls/playlist.m3u8 --hls-live-edge=10 ).?

Thanks

**Comment by chrippa** [comment]
The exact command I used: `livestreamer --hls-live-edge=10 hls://http://idealoglx.zapto.org/testhls/playlist.m3u8 best`.

**Comment by idealsat** [comment]
Hi

its work like this.

but i using livestreamer in openpli there we are using like this 
( http://127.0.0.1:88/hls://http://idealoglx.zapto.org/testhls/playlist.m3u8 )

if i give run there like this ( http://127.0.0.1:88/ --hls-live-edge=10  hls://http://idealoglx.zapto.org/testhls/playlist.m3u8 )  then openpli not accepted. its give error.

Is there way we modify hardcoded or which file i can modify for this value.?

Thanks

**Comment by chrippa** [comment]
You can use the [set_option](http://docs.livestreamer.io/api.html#livestreamer.Livestreamer.set_option) method to set options in applications using Livestreamer as a library.

**Comment by idealsat** [comment]
Yes which file in library https://github.com/chrippa/livestreamer/tree/develop/src/livestreamer

Thanks

**Comment by chrippa** [comment]
You should update the application that is using Livestreamer as a library, not the library itself.

**Comment by idealsat** [comment]
Hi

I solve issue with change code in openpli.

Many thanks for your help
