### ISSUE TITLE
Dailymotion plugin doesn't seem to work anymore

### ISSUE THREAD

**Issue by TehBreakout** [chrippa/livestreamer#786]
Hello,

Since a few days, I can't watch any dailymotion stream. I think they changed something on their side.

Here are the kind of errors I get :

```[cli][info] Found matching plugin dailymotion for URL http://www.dailymotion.com
/embed/video/xmehe4
[cli][info] Available streams: 1080p+ (best), 132p (worst), 236p, 412p, 720p
[cli][info] Opening stream: 1080p+ (hds)
[stream.hds][error] Failed to open fragment 1-514: Unable to open URL: http://st
ream-06.vty.dmcdn.net/16/dm/1/xmehe4/live_src.isml/events(live_src-1426320404)/l
ive_src-audio=128000-video=399360-?hls_no_audio_only=1Seg1-Frag514 (400 Client E
rror: Bad Request)
[stream.hds][error] Failed to open fragment 1-514: Unable to open URL: http://st
ream-06.vty.dmcdn.net/16/dm/1/xmehe4/live_src.isml/events(live_src-1426320404)/l
ive_src-audio=128000-video=399360-?hls_no_audio_only=1Seg1-Frag514 (400 Client E
rror: Bad Request)
[stream.hds][error] Failed to open fragment 1-514: Unable to open URL: http://st
ream-06.vty.dmcdn.net/16/dm/1/xmehe4/live_src.isml/events(live_src-1426320404)/l
ive_src-audio=128000-video=399360-?hls_no_audio_only=1Seg1-Frag514 (400 Client E
rror: Bad Request)
[stream.hds][error] Failed to open fragment 1-515: Unable to open URL: http://st
ream-06.vty.dmcdn.net/16/dm/1/xmehe4/live_src.isml/events(live_src-1426320404)/l
ive_src-audio=128000-video=399360-?hls_no_audio_only=1Seg1-Frag515 (400 Client E
rror: Bad Request)
[stream.hds][error] Failed to open fragment 1-515: Unable to open URL: http://st
ream-06.vty.dmcdn.net/16/dm/1/xmehe4/live_src.isml/events(live_src-1426320404)/l
ive_src-audio=128000-video=399360-?hls_no_audio_only=1Seg1-Frag515 (400 Client E
rror: Bad Request)
[stream.hds][error] Failed to open fragment 1-515: Unable to open URL: http://st
ream-06.vty.dmcdn.net/16/dm/1/xmehe4/live_src.isml/events(live_src-1426320404)/l
ive_src-audio=128000-video=399360-?hls_no_audio_only=1Seg1-Frag515 (400 Client E
rror: Bad Request)```
etc...

I think Dailymotion changed something, because it worked perfectly a few days after I installed the last update.

Do you have the same problem ?
Thanks !

**Comment by barbacos** [comment]
Same issue since a few day.
Only with dailymotion

**Comment by Bromind** [comment]
Hi, just tried it right now, I had no problem.

**Comment by canoine** [comment]
Same problem here, but not on all Dailymotion streams. www.dailymotion.com/embed/video/x25eyo8 is OK, for example, but www.dailymotion.com/embed/video/x15ztwg isn't :

> [cli][info] Found matching plugin dailymotion for URL www.dailymotion.com/embed/video/x15ztwg
> [cli][info] Available streams: 1080p+ (best), 132p (worst), 232p, 408p, 720p
> [cli][info] Opening stream: 408p (hds)
> [stream.hds][error] Failed to open fragment 1-4994: Unable to open URL: http://stream-09.vty.dmcdn.net/11/dm/1/x15ztwg/live.isml/events(live-1426361198)/live-audio=128000-video=989000-?hls_no_audio_only=1Seg1-Frag4994 (400 Client Error: Bad Request)
> [stream.hds][error] Failed to open fragment 1-4994: Unable to open URL: http://stream-09.vty.dmcdn.net/11/dm/1/x15ztwg/live.isml/events(live-1426361198)/live-audio=128000-video=989000-?hls_no_audio_only=1Seg1-Frag4994 (400 Client Error: Bad Request)
> ...

**Comment by benoit-intrw** [comment]
Same problem here :
```
$ livestreamer http://www.dailymotion.com/embed/video/x173n01 best
[cli][info] A new version of Livestreamer (1.12) is available!
[cli][info] Found matching plugin dailymotion for URL http://www.dailymotion.com/embed/video/x173n01
[cli][info] Available streams: 216p (worst), 720p (best)
[cli][info] Opening stream: 720p (hds)
[stream.hds][error] Failed to open fragment 1-10468: Unable to open URL: http://stream-12.vty.dmcdn.net/04/dm/1/x173n01/live.isml/events(live-1426544205)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag10468 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-10468: Unable to open URL: http://stream-12.vty.dmcdn.net/04/dm/1/x173n01/live.isml/events(live-1426544205)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag10468 (400 Client Error: Bad Request)
```
Someone made progress to fix this ?

**Comment by benoit-intrw** [comment]
By looking at how manifest is parsed and how fragment url are build, I thought that the part `?hls_no_audio_only=1` looks weird. By removing it it's working ... but I don't know any things about HDS and f4m manifest. Is this `?hls_no_audio_only=1` supposed to be present  and used ? What do you think ??

**Comment by TehBreakout** [comment]
I just realised that sometimes, I can open a dailymotion stream after about 8 attempts in a row. Works 100% fine if I manage to start the stream. Really strange.

**Comment by gmarsay** [comment]
Same problem here, with this URL : http://games.dailymotion.com/live/x2igv5y

>$ livestreamer --player-external-http --player-external-http-port 50000 http://games.dailymotion.com/live/x2igv5y?hls_no_audio_only=1 best
>[cli][info] Found matching plugin dailymotion for URL http://games.dailymotion.com/live/x2igv5y?hls_no_audio_only=1
>[cli][info] Available streams: 216p (worst), 720p, 720p+ (best)
>[cli][info] Starting server, access with one of:
>[cli][info]  http://127.0.0.1:50000/
>[cli][info]  http://0.0.0.0:50000/
>[cli][info] Got HTTP request from unknown player
>[cli][info] Opening stream: 720p+ (hds)
>[stream.hds][error] Failed to open fragment 1-1571: Unable to open URL: http://stream-05.vty.dmcdn.net/18/dm/1/x2igv5y/live_src.isml/events(live_src-1426861629)/live_src-audio=95232-video=2099200-?hls_no_audio_only=1Seg1-Frag1571 (400 Client Error: Bad Request)
>[stream.hds][error] Failed to open fragment 1-1571: Unable to open URL: http://stream-05.vty.dmcdn.net/18/dm/1/x2igv5y/live_src.isml/events(live_src-1426861629)/live_src-audio=95232-video=2099200-?hls_no_audio_only=1Seg1-Frag1571 (400 Client Error: Bad Request)
> ...

**Comment by canoine** [comment]
The patch resolves the problem for me. Thanks.

**Comment by campones** [comment]
for me it seems   it stopped  working few days ago.. example:

http://www.dailymotion.com/video/x2lefik

it seems to contain a token now and the script    can't retrieve anything?

**Comment by cirrusUK** [comment]
you boys need to be using streamlink, livestreamer is no longer being actively developed 
https://github.com/streamlink/streamlink

**Comment by refriedfood** [comment]
Why use streamlink when livestreamer doesn't need to be actively developed because it's perfect already? Dailymotion support is just a _plugin_ that anyone can update.

**Comment by campones** [comment]
"Dailymotion support is just a plugin that anyone can update." 

yea right..
