### ISSUE TITLE
#EXTM3U header missing when trying to open twitch stream

### ISSUE THREAD

**Issue by Huppa** [chrippa/livestreamer#791]
C:\Users\User>livestreamer twitch.tv/summit1g
[cli][info] Found matching plugin twitch for URL twitch.tv/summit1g
Available streams: audio, high, low, medium, mobile (worst), source (best)

C:\Users\User>livestreamer twitch.tv/summit1g best
[cli][info] Found matching plugin twitch for URL twitch.tv/summit1g
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source
(best)
[cli][info] Opening stream: source (hls)
[cli][error] Could not open stream: Missing #EXTM3U header

C:\Users\User>

How do I fix this?

**Comment by Huppa** [comment]
# Format is option=value. Lines starting with a # is considered comments
# and are ignored.

# By default livestreamer will attempt to locate VLC on your system
# and use that, but you can also specify the location of a player
# yourself.

# Important: You must use a quoted path if there are spaces in the path. This
# is because the player command is parsed like a shell command to allow
# parameters to be passed to the player.

# Here is a few examples of players:

# VLC
#player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
#player="C:\Program Files\VideoLAN\VLC\vlc.exe"
# Using --file-caching is recommended, but is only supported in VLC 2.0+
player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --file-caching=5000
#player="C:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000

# MPC-HC, must be at least version 1.7 to be used
#player="C:\Program Files (x86)\MPC-HC\mpc-hc.exe"

# MPlayer2
#player=C:\mplayer2\mplayer2.exe -cache 4096


# Use this if you want to transport the stream to the player via a named pipe.
#player-fifo

# Use this if you want to transport the stream to the player via HTTP.
#player-http

# Use this if you want Livestreamer to only pass a URL to your player and
# let it handle the transport of the stream itself.
#player-passthrough=http,hls,rtmp

# By default Livestreamer will close the player when stream is over.
# Use this option to let the player stay or close itself instead.
#player-no-close

# Use this option if you want Livestreamer to keep trying to access
# the stream even if it goes offline or disconnects. Your player must
# support HTTP and its playlist should be set to repeat mode.
#player-continuous-http

# Show console output from the video player
#verbose-player

# RTMP streams are downloaded using rtmpdump. Full path to the rtmpdump exe
# should be specified here.
rtmpdump=@INSTDIR@\rtmpdump\rtmpdump.exe

# Log level, default is info
#loglevel=debug

# Number of threads to use when streaming HLS streams
#hls-segment-threads=1

# Number of threads to use when streaming HDS streams
#hds-segment-threads=1

**Comment by Huppa** [comment]
![2dab028c24bb055fbc79e691c59357cb](https://cloud.githubusercontent.com/assets/11510218/6676935/a17b6efa-cbf9-11e4-9847-cbdb52a43b94.png)

**Comment by CourageKeeper** [comment]
I am having this same issue starting today, and haven't been able to find any information about getting the "#EXTM3U header" or fix this. How were you able to resolve this? It's currently happening with every Twitch stream I try to open.

Edit: I thought I might as well ask here before re-opening the issue or opening a new one. I'll do that later if need be.

**Comment by knetzgerd** [comment]
I also am having trouble with this. Whenever I try and open a twitch.tv stream is get the error of a missing #EXTM3U header and I have been unable to find any information about this. I was hoping to find a solution to this problem.

**Comment by CourageKeeper** [comment]
I don't know if it will be any help, knetzgerd, but in my case it was because part of the twitch protocol was being blocked on the network I was on. I don't know enough about web traffic or networks to give more information, I'm afraid.
