### ISSUE TITLE
Kernel panic using live streamer on Mavericks

### ISSUE THREAD

**Issue by Ambigioz** [chrippa/livestreamer#792]
Hi,

I don't know if it happens only to me, but I often get kernel panics on a macbook pro 15 with Mavericks using live streamer.

I would say it happens once every 20 times I use it, and it happens only when live streamer is running.

Here's the stack trace that I get after rebooting.

http://pastebin.com/SHjqYh8v

Thanks for the excellent work!

**Comment by chrippa** [comment]
The log doesn't tell me much, but I think this is more likely to be an issue caused by the actual video playback rather than Livestreamer itself.

Perhaps this is helpful: https://support.apple.com/kb/PH14063?locale=en_US

**Comment by Ambigioz** [comment]
I don't know about that, I usually stream with VLC other network streams and I never had this happened to me.
I just reported in case there were others with this problem. Thanks.
