### ISSUE TITLE
Random error when trying to open a livestream

### ISSUE THREAD

**Issue by MonstercatUK** [chrippa/livestreamer#798]
http://prntscr.com/6icyao This is what I get when I try to open ANY stream, sometimes it's a 404 error "client not found"

**Comment by skulblakka** [comment]
Did this happen before or is this only happening now? Because twitch currently has some server issues.

**Comment by MonstercatUK** [comment]
I was watching a stream perfectly fine in source and it crashed so I tried other qualities and it didn't work still. It happened like 20 minutes ago for the first time, you reckon it's twitch not working?

**Comment by mattigins** [comment]
Was happening for me too. Seems fine now

**Comment by mattigins** [comment]
Now it doesn't work again. It is intermittent so I guess it's a twitch issue

**Comment by MonstercatUK** [comment]
Alright cheers. I was worried it was something wrong with the program itself because it was working fine all morning
