### ISSUE TITLE
--version on Windows

### ISSUE THREAD

**Issue by nanogyth** [chrippa/livestreamer#801]
Livestream said there was a new version available, but I thought I had already updated.
Running livestreamer-v1.12.0-win32-setup.exe on Windows 7, didn't change the reported version.
Uninstalling and reinstalling still reports as version 1.11.1

> livestreamer --version
livestreamer-script.py 1.11.1

**Comment by skulblakka** [comment]
This means version 1.11.1 is still installed. Make sure to remove 1.11.1 before you install 1.12.
