### ISSUE TITLE
Livestreamer dependency(WPF software)

### ISSUE THREAD

**Issue by b-barry** [chrippa/livestreamer#811]
Hello,

First of all, I  want to give a very sincere thank you for your work.
I would like to create an application based plugin in C # (WPF).
However, I have a few questions:
- Is there a way to integrate the plugin directly in a WPF program
seen that there is a binairie for Windows?
- is the license I need to include in this program ?  I want to credit Livestreamer's hard work and will do whatever you ask me.
- If I understand correctly, the plugin will bypass the ads on Twitch, there is an option to
put them?

**Comment by chrippa** [comment]
> Is there a way to integrate the plugin directly in a WPF program seen that there is a binairie for Windows?

I'm not sure what WPF is, but the [Livestreamer API](http://docs.livestreamer.io/api_guide.html) is only usable from [Python](http://python.org). The binaries available are simply an embedded version of Python + Livestreamer.

> is the license I need to include in this program ? I want to credit Livestreamer's hard work and will do whatever you ask me.

[This is the license](https://github.com/chrippa/livestreamer/blob/develop/LICENSE).

> If I understand correctly, the plugin will bypass the ads on Twitch, there is an option to put them?

Ads are always displayed by some external mechanism. It's up to you if you want to implement such things yourself, but it's not possible via Livestreamer.

**Comment by b-barry** [comment]
Hello,

Thank you for your quick answer.

I will integrate the license. Do you have some track search to implement this thing? 
I checked the HTML code of Twitch, I find the ads container but I don't know how to extract it. 
It's a flash player.

Best regards
