### ISSUE TITLE
error: This manifest requires the 'pvswf' parameter to verify the SWF

### ISSUE THREAD

**Issue by cloud90** [chrippa/livestreamer#814]
![error2](https://cloud.githubusercontent.com/assets/9502612/6785549/7dccd826-d186-11e4-8073-38c32c710e8b.PNG)

i have try this:

livestreamer hds://http://cctv-lh.akamaihd.net/z/acgn_music_box_live@125117/manifest.f4m pvswf=https://connectcast.tv/jwplayer/v5/player.swf best

but nothing.. error: unrecognized argument:  best

![error3](https://cloud.githubusercontent.com/assets/9502612/6785439/d08f2d1c-d185-11e4-8599-9ad3a74dd7c9.PNG)

**Comment by karlo2105** [comment]
What's source address ?

**Comment by cloud90** [comment]
why for me is different? what you have script exactly?

**Comment by karlo2105** [comment]
Take a closer look. 

livestreamer "hds://http://cctv-lh.akamaihd.net/z/acgn_music_box_live@125117/manifest.f4m 'pv
swf=https://connectcast.tv/jwplayer/v5/player.swf'" best
[cli][info] Found matching plugin stream for URL hds://http://cctv-lh.akamaihd.n
et/z/acgn_music_box_live@125117/manifest.f4m 'pvswf=https://connectcast.tv/jwpla
yer/v5/player.swf'
[cli][info] Available streams: 1820k (worst, best)
[cli][info] Opening stream: 1820k (hds)
[stream.hds][error] Failed to open fragment 1-237855866: Unable to open URL: htt
p://cctv-lh.akamaihd.net/z/acgn_music_box_live@125117/1080p_268e0dabed2e5535-p_S
eg1-Frag237855866 (403 Client Error: Forbidden)

**Comment by biezom** [comment]
hi you can try

<pre>livestreamer "hlsvariant://http://cctv-lh.akamaihd.net/i/acgn_music_box_live@125117/master.m3u8" best</pre>

**Comment by cloud90** [comment]
oh thank you biezom, this run perfectly! :D
