### ISSUE TITLE
twitch stream problems &command for timestamp on twitch vod

### ISSUE THREAD

**Issue by ignarteaga** [chrippa/livestreamer#818]
hi, i wanted to know if there is any way for me to open a twitch vod at a specific time.

and the other issue that i have is that i cant watch live streams on twitch in any sort of quality since, at some point, the stream begins to lag and playback the sound of the last segment of audio before the video stopped, whilst the video is still stopped, i dont know if i made myself clear.

I really dont think that this is an issue of my internet provider since i can do any other kind of activity on the web without much problem.

Thank you

**Comment by skulblakka** [comment]
See #711 for seeking in twitch vods.

**Comment by chrippa** [comment]
You can try using [multi-threaded streaming](http://docs.livestreamer.io/issues.html#multi-threaded-streaming), but if that doesn't help only improving the connection between you and Twitch servers will help.
