### ISSUE TITLE
livecoding.tv plugin?

### ISSUE THREAD

**Issue by Scrumilation** [chrippa/livestreamer#821]

**Comment by youdulayo** [comment]
+1

**Comment by betagan** [comment]
+1

I'll dump some more information as I might create the plugin later:

livecoding.tv currently only features jwplayer/rtmp streams. 
mobile streams *might* be supported later according to their roadmap (http://roadmap.livecoding.tv/)


channels are located at `livecoding.tv/<username>`. rtmp-streams can be found on these pages by looking for
    `var stream_url = "rtmp://(.*).livecoding.tv:1935/livecodingtv/cannap?t=(.*)";`

there is only one quality setting so far (no transcoding done on server side)

**Comment by intact** [comment]
#978
