### ISSUE TITLE
hitbox issues on mac

### ISSUE THREAD

**Issue by something915** [chrippa/livestreamer#823]
server:~ something915$ livestreamer hitbox.tv/whatever
[cli][info] Found matching plugin hitbox for URL hitbox.tv/whatever
Available streams: live (worst, best)
server:~ something915$ livestreamer hitbox.tv/whatever best
[cli][info] Found matching plugin hitbox for URL hitbox.tv/whatever
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] No data returned from stream

I'm on version 1.12.1

**Comment by chrippa** [comment]
Works fine here, what does `livestreamer -j url` output?

**Comment by something915** [comment]
server:~ something915$ livestreamer -j hitbox.tv/viagamehs
{
  "streams": {
    "480p": {
      "headers": {
        "Accept-Encoding": "gzip, deflate, compress", 
        "Accept": "*/*", 
        "User-Agent": "python-requests/2.2.1 CPython/2.7.6 Darwin/14.1.0"
      }, 
      "type": "hls", 
      "url": "http://edge.hls.dt.hitbox.tv/hls/viagamehs_480p/index.m3u8"
    }, 
    "360p": {
      "headers": {
        "Accept-Encoding": "gzip, deflate, compress", 
        "Accept": "*/*", 
        "User-Agent": "python-requests/2.2.1 CPython/2.7.6 Darwin/14.1.0"
      }, 
      "type": "hls", 
      "url": "http://edge.hls.dt.hitbox.tv/hls/viagamehs_360p/index.m3u8"
    }, 
    "720p": {
      "headers": {
        "Accept-Encoding": "gzip, deflate, compress", 
        "Accept": "*/*", 
        "User-Agent": "python-requests/2.2.1 CPython/2.7.6 Darwin/14.1.0"
      }, 
      "type": "hls", 
      "url": "http://edge.hls.dt.hitbox.tv/hls/viagamehs/index.m3u8"
    }, 
    "worst": {
      "headers": {
        "Accept-Encoding": "gzip, deflate, compress", 
        "Accept": "*/*", 
        "User-Agent": "python-requests/2.2.1 CPython/2.7.6 Darwin/14.1.0"
      }, 
      "type": "hls", 
      "url": "http://edge.hls.dt.hitbox.tv/hls/viagamehs_360p/index.m3u8"
    }, 
    "500k": {
      "headers": {
        "Accept-Encoding": "gzip, deflate, compress", 
        "Accept": "*/*", 
        "User-Agent": "python-requests/2.2.1 CPython/2.7.6 Darwin/14.1.0"
      }, 
      "type": "hls", 
      "url": "http://edge.hls.dt.hitbox.tv/hls/viagamehs_360p/index.m3u8"
    }, 
    "best": {
      "headers": {
        "Accept-Encoding": "gzip, deflate, compress", 
        "Accept": "*/*", 
        "User-Agent": "python-requests/2.2.1 CPython/2.7.6 Darwin/14.1.0"
      }, 
      "type": "hls", 
      "url": "http://edge.hls.dt.hitbox.tv/hls/viagamehs/index.m3u8"
    }, 
    "1000k": {
      "headers": {
        "Accept-Encoding": "gzip, deflate, compress", 
        "Accept": "*/*", 
        "User-Agent": "python-requests/2.2.1 CPython/2.7.6 Darwin/14.1.0"
      }, 
      "type": "hls", 
      "url": "http://edge.hls.dt.hitbox.tv/hls/viagamehs_480p/index.m3u8"
    }
  }, 
  "plugin": "hitbox"
}

**Comment by chrippa** [comment]
That stream is using HLS and should work fine, but the stream you posted in the original post was rtmp, please paste the output from a stream you're having issues with.

**Comment by something915** [comment]
sorry, my mistake.

server:~ something915$ livestreamer -j hitbox.tv/claine-kun
{
  "streams": {
    "live": {
      "params": {
        "playpath": "claine-kun", 
        "pageUrl": "http://hitbox.tv/claine-kun", 
        "live": true, 
        "rtmp": "rtmp://fml.B6BF.edgecastcdn.net/20B6BF", 
        "swfVfy": "http://edge.vie.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf"
      }, 
      "type": "rtmp"
    }, 
    "worst": {
      "params": {
        "playpath": "claine-kun", 
        "pageUrl": "http://hitbox.tv/claine-kun", 
        "live": true, 
        "rtmp": "rtmp://fml.B6BF.edgecastcdn.net/20B6BF", 
        "swfVfy": "http://edge.vie.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf"
      }, 
      "type": "rtmp"
    }, 
    "best": {
      "params": {
        "playpath": "claine-kun", 
        "pageUrl": "http://hitbox.tv/claine-kun", 
        "live": true, 
        "rtmp": "rtmp://fml.B6BF.edgecastcdn.net/20B6BF", 
        "swfVfy": "http://edge.vie.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf"
      }, 
      "type": "rtmp"
    }
  }, 
  "plugin": "hitbox"
}

**Comment by chrippa** [comment]
Hmm, works fine here. What happens if you run the command line outputed by `livestreamer -c hitbox.tv/claine-kun`?

**Comment by something915** [comment]
server:~ something915$ livestreamer -c hitbox.tv/claine-kun
Available streams: live (worst, best)

server:~ something915$ livestreamer -c hitbox.tv/claine-kun best
/usr/local/bin/rtmpdump --rtmp="rtmp://fml.B6BF.edgecastcdn.net/20B6BF" --playpath="claine-kun" --pageUrl="http://hitbox.tv/claine-kun" --live --swfVfy="http://edge.vie.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf"

server:~ something915$ livestreamer -c hitbox.tv/claine-kun worst
/usr/local/bin/rtmpdump --rtmp="rtmp://fml.B6BF.edgecastcdn.net/20B6BF" --playpath="claine-kun" --pageUrl="http://hitbox.tv/claine-kun" --live --swfVfy="http://edge.vie.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf"

**Comment by chrippa** [comment]
I meant, what happens if you run that rtmpdump command?

**Comment by something915** [comment]
server:~ something915$ /usr/local/bin/rtmpdump --rtmp="rtmp://fml.B6BF.edgecastcdn.net/20B6BF" --playpath="claine-kun" --pageUrl="http://hitbox.tv/claine-kun" --live --swfVfy="http://edge.vie.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf"
dyld: Library not loaded: /usr/local/lib/librtmp.dylib
  Referenced from: /usr/local/bin/rtmpdump
  Reason: no suitable image found.  Did find:
	/usr/local/lib/librtmp.dylib: stat() failed with errno=13
	/usr/local/lib/librtmp.dylib: stat() failed with errno=13
Trace/BPT trap: 5

**Comment by chrippa** [comment]
Looks like your rtmpdump install is broken.

**Comment by something915** [comment]
Do you know how I can fix that?

**Comment by chrippa** [comment]
How did you install it? I don't know much about OS X but I think installing via homebrew should work.

**Comment by something915** [comment]
I'm not actually sure how it was installed. I did some searching on homebrew and getting rtmpdump through it. And homebrew just successfully installed it and hitbox streams are working now.

Thanks for getting me through that!
