### ISSUE TITLE
livestreamer twitch.tv oddities

### ISSUE THREAD

**Issue by OliverLeitner** [chrippa/livestreamer#827]
livestreamer does not work for me on twitch.tv anymore, here is an strace output of the last sequence, it goes from opening directly to closing:

write(1, "[cli][info] Opening stream: medi"..., 41[cli][info] Opening stream: medium (hls)
) = 41
stat("/home/nevermind/.netrc", 0x7fff855d6ab0) = -1 ENOENT (No such file or directory)
stat("/home/nevermind/_netrc", 0x7fff855d6ab0) = -1 ENOENT (No such file or directory)
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 5
connect(5, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = 0
sendto(5, "\2\0\0\0\16\0\0\0\34\0\0\0video27.iad02.hls.tt"..., 40, MSG_NOSIGNAL, NULL, 0) = 40
poll([{fd=5, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=5, revents=POLLIN|POLLHUP}])
read(5, "\2\0\0\0\1\0\0\0\1\0\0\0\4\0\0\0\34\0\0\0\0\0\0\0", 24) = 24
read(5, "\300\20F\37\2video27.iad02.hls.ttvnw.net"..., 33) = 33
close(5)                                = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 5
fcntl(5, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(5, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("192.16.70.31")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=5, events=POLLOUT}], 1, 20000) = 1 ([{fd=5, revents=POLLOUT}])
getsockopt(5, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
poll([{fd=5, events=POLLOUT}], 1, 20000) = 1 ([{fd=5, revents=POLLOUT}])
sendto(5, "GET /hls93/jooygirl_13755146192_"..., 413, 0, NULL, 0) = 413
fcntl(5, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
poll([{fd=5, events=POLLIN}], 1, 20000) = 1 ([{fd=5, revents=POLLIN}])
recvfrom(5, "HTTP/1.1 200 OK\r\nContent-Type: a"..., 8192, 0, NULL, NULL) = 825
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f2db30d4000
mprotect(0x7f2db30d4000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f2db38d3fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f2db38d49d0, tls=0x7f2db38d4700, child_tidptr=0x7f2db38d49d0) = 25015
futex(0x11cd4e0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xd75990, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f2db28d3000
mprotect(0x7f2db28d3000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f2db30d2fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f2db30d39d0, tls=0x7f2db30d3700, child_tidptr=0x7f2db30d39d0) = 25016
futex(0x11d8070, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xd75990, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
select(0, NULL, NULL, NULL, {0, 1000})  = 0 (Timeout)
futex(0xd75990, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
select(0, NULL, NULL, NULL, {0, 2000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 4000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 8000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 16000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 32000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
brk(0x1440000)                          = 0x1440000
write(1, "[cli][info] Starting player: nvl"..., 34[cli][info] Starting player: nvlc
) = 34
open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 6
fstat(6, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 3), ...}) = 0
open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 7
fstat(7, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 3), ...}) = 0
pipe([8, 9])                            = 0
fcntl(8, F_GETFD)                       = 0
fcntl(8, F_SETFD, FD_CLOEXEC)           = 0
fcntl(9, F_GETFD)                       = 0
fcntl(9, F_SETFD, FD_CLOEXEC)           = 0
pipe([10, 11])                          = 0
fcntl(10, F_GETFD)                      = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
fcntl(11, F_GETFD)                      = 0
fcntl(11, F_SETFD, FD_CLOEXEC)          = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f2db8249a10) = 25021
close(11)                               = 0
mmap(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2db1fd1000
read(10, "", 1048576)                   = 0
mremap(0x7f2db1fd1000, 1052672, 4096, MREMAP_MAYMOVE) = 0x7f2db1fd1000
close(8)                                = 0
close(10)                               = 0
munmap(0x7f2db1fd1000, 4096)            = 0
fcntl(9, F_GETFL)                       = 0x1 (flags O_WRONLY)
fstat(9, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2db8265000
lseek(9, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
fstat(9, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
munmap(0x7f2db8265000, 4096)            = 0
select(0, NULL, NULL, NULL, {0, 500000}) = 0 (Timeout)
wait4(25021, 0x7fff855d7780, WNOHANG, NULL) = 0
close(6)                                = 0
close(7)                                = 0
write(9, "G@\0\21\0\0\260\r\0\1\301\0\0\0\1\360\0*\261\4\262\377\377\377\377\377\377\377\377\377\377\377"..., 8192) = 8192
write(9, " \236\37e\233om\277\375\"\211\313\341\340\f\20\33\227\7#\377\364\376\227\361\374xB\360\242\204X"..., 8192) = 8192
write(9, "\320\37\t\334@a\326\231o\3671\307\361\307\264 \344\26\257\377\377G)\262I\220\321\252\253\367\377\377"..., 8192) = 8192
write(9, "Q>\f6\375\345kl\27R\200\16@\0278\213\230T\336\337\204\37\26xN:H\215\310\221\330q"..., 8192) = 8192
write(9, "W\352d|\356\345\345m\237\2\250s\336\335\324xo5\261:\223n\214\265\227&\37\231u\363\256\33"..., 8192) = 8192
write(9, "R\326\220\272\265\312$\344\177X\277\241:\361F\275\356\370\214\t;\237\365\260G\1\1\36p4\20t"..., 8192) = 8192
write(9, "'\256\275\266\204\340\211\17mpF\361\177\n~S\236\235\365N\t\327(O\377_\255Grsx\316"..., 8192) = 8192
write(9, "T\0\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"..., 8192) = 8192
write(9, "R\260\"\363\342X\351r\265\362pDW\334\315\302\232/\360\237\33\324\2421\372x8\306.i\342\4"..., 8192) = 4096
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=24990, si_uid=1000} ---
write(9, "\31\223\241\351\220\273\10\204G]\267}\333\332\342Y\235\362o\324\365\221u|\302\26\261\357k\331D\335"..., 4096) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=24990, si_uid=1000} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=25021, si_status=0, si_utime=8, si_stime=12} ---
write(1, "[cli][info] Player closed\n", 26[cli][info] Player closed
) = 26
futex(0x11bf660, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xd75990, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xd75990, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
write(1, "[cli][info] Stream ended\n", 25[cli][info] Stream ended
) = 25
close(9)                                = 0
kill(25021, SIGKILL)                    = 0
wait4(25021, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 25021
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f2db7e39340}, {0x46460e, [], SA_RESTORER, 0x7f2db7e39340}, 8) = 0
rt_sigaction(SIGTERM, {SIG_DFL, [], SA_RESTORER, 0x7f2db7e39340}, {0x46460e, [], SA_RESTORER, 0x7f2db7e39340}, 8) = 0
munmap(0x7f2db4bcc000, 262144)          = 0
exit_group(0)                           = ?
+++ exited with 0 +++

system is a current xubuntu lts desktop.

tried on three different streams in two days with two different players (nvlc, mplayer), always the same result.

**Comment by chrippa** [comment]
It looks like the player is refusing the input and exits. You can use `--verbose-player` to see its output.

**Comment by OliverLeitner** [comment]
thank you for the info, chrippa, that commandline argument did help, it was a problem in my xorg config, all fixed now.
