### ISSUE TITLE
bug on many lives on dailymotion games

### ISSUE THREAD

**Issue by DerpDarako** [chrippa/livestreamer#829]
Hello,

I tried to watch some lives on dailymotion games but it doesn't work with livestreamer when i'm not facing any problem when i want to watch twitch issue:

I try this:

[romain@freenaya ~]$ livestreamer http://games.dailymotion.com/live/xj7bck 720p
[cli][info] Found matching plugin dailymotion for URL http://games.dailymotion.com/live/xj7bck
[cli][info] Available streams: 1080p+ (best), 132p (worst), 232p, 408p, 720p
[cli][info] Opening stream: 720p (hds)
[stream.hds][error] Failed to open fragment 1-3071: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3071 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-3071: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3071 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-3071: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3071 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-3072: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3072 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-3072: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3072 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-3072: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3072 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-3073: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3073 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-3073: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3073 (400 Client Error: Bad Request)
[stream.hds][error] Failed to open fragment 1-3073: Unable to open URL: http://stream-01.vty.dmcdn.net/19/dm/1/xj7bck/live.isml/events(live-1427569307)/live-audio=128000-video=2200000-?hls_no_audio_only=1Seg1-Frag3073 (400 Client Error: Bad Request)
^CInterrupted! Closing currently open stream...

I stay at your disposal if you need more information or test

BR

**Comment by chrippa** [comment]
I believe this was fixed in 1.12.1.

**Comment by karlo2105** [comment]
I confirm it's was fixed. ;)

livestreamer "http://games.dailymotion.com/live/xj7bck" best
[cli][info] Found matching plugin dailymotion for URL http://games.dailymotion.com/live/xj7bck
[cli][info] Available streams: 132p (worst), 232p, 408p, 720p, 720p+ (best)
[cli][info] Opening stream: 720p+ (hds)
[cli][info] Starting player: 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[cli][info] Player closed
[cli][info] Stream ended

**Comment by DerpDarako** [comment]
Oh sorry, i'm using livestreamer 1.12.0... I have to wait the commit 1.12.1 for Fedora :)
