### ISSUE TITLE
Unable to use 1.12.1 except in program directory in Windows

### ISSUE THREAD

**Issue by duckness** [chrippa/livestreamer#831]
I'm pretty sure it's just me being retarded, but I can't find a solution to this issue so...

If I try to use `Livestreamer` in any directory, it defaults to version `1.7.4` for some reason.  
![11](https://cloud.githubusercontent.com/assets/6380270/6885667/e5ac9230-d65c-11e4-99b1-9d82a1b4ec9e.png)

This is the workaround. I have to `cd` to the directory it is installed, which is a little annoying
![1](https://cloud.githubusercontent.com/assets/6380270/6885673/07419724-d65d-11e4-92d7-07b12bc467d9.png)

**Comment by chrippa** [comment]
It looks like you have installed Livestreamer into multiple directories and the oldest one is taking precedence. You can type `echo %PATH%` to see which paths are searched by the command prompt.

**Comment by duckness** [comment]
holy crap I didn't think of that >.< sorry for the trouble and thanks.
