### ISSUE TITLE
error: No streams found on this URL: twitch.tv/****

### ISSUE THREAD

**Issue by SHOTbyGUN** [chrippa/livestreamer#835]
`shotbygun@shot5 ~ $ livestreamer twitch.tv/wcs`
`[cli][info] Found matching plugin twitch for URL twitch.tv/wcs`
`error: No streams found on this URL: twitch.tv/wcs`

Same stream opens up on windows with livestreamer 1.11.1 on my friends computer.

livestreamer 1.10.2
Debian Jessie 64bit
Linux Mint Debian Edition 2

I tried to install livestreamer from debian sid repository eg. version 1.12, but all I get is stack trace of "unknown distribution" error so I reverted back to default distribution version.

Is this new bug, or is my software just out of date? and if so, how can I expedite new version to come into debian jessie repository?

**Comment by chrippa** [comment]
You'll need at least 1.11.1. You can [install it from source](http://docs.livestreamer.io/install.html#source-code).

**Comment by SHOTbyGUN** [comment]
Thanks, works great! Installed 1.12.1 using pip

For everyone else using debian:

```sh
sudo apt-get remove livestreamer
sudo apt-get autoremove
sudo apt-get install python-pip
sudo pip install -U livestreamer
livestreamer -V
```
