### ISSUE TITLE
where should i put the command --http-ignore-env? in the configuration file or in the cmd

### ISSUE THREAD

**Issue by ignarteaga** [chrippa/livestreamer#837]
also, i want to know how and where should i type commands like the stream caching for vlc and the hls segment threads for them to be effective.

**Comment by chrippa** [comment]
To use on the command line, just put them after `livestreamer`, e.g.

    livstreamer --http-ignore-env http://url best

For use in the config, use the format described in the [docs](http://docs.livestreamer.io/cli.html#configuration-file), e.g. 

    http-ignore-env
    hls-segment-threads=2

**Comment by ignarteaga** [comment]
ok, thank you for helping this coding noob :D
