### ISSUE TITLE
new.livestream.com has been depreciated

### ISSUE THREAD

**Issue by jordandalley** [chrippa/livestreamer#847]
Hey there,

Love livestreamer but at the moment it's broken.

It seems that livestream.com has depreciated new.livestream.com so livestreamer incorrectly assumes that the right plugin is oldlivestream.

Cheers,
Jordan.

**Comment by d3rped** [comment]
I can confirm this issue.

Just changing the 
"/usr/lib/python3.4/site-packages/livestreamer/plugins/livestream.py"
plugin file so that it recognizes the new URL scheme sadly doesn't solve the problem.

**Comment by bonacker** [comment]
I can confirm as well.

As a temporary workaround, I was able to watch and record a stream with Livestreamer by playing the video in the browser and sniffing. I found a URL that looked like this. (This was not the stream in question.) http://api.new.livestream.com/accounts/506572/events/3880965/broadcasts/83486369.smil

I put the "506572" and the "3880965" into this template that had worked before:

http://new.livestream.com/accounts/1249127/events/3936641 and it played.

However on another stream, this did not work.

**Comment by jordandalley** [comment]
I found an even easier workaround. Copy the url eg http://livestream.com/somestream and add the new. in front so the url becomes http://new.livestream.com/somestream. There's a redirector on the livestream site that catches any of the depreciated "new" url's. This seems enough to trick livestreamer into using the livestream plugin instead of the oldlivestream plugin.

**Comment by jordandalley** [comment]
I've done a bit of a workaround for everyone until the devs fix it in a new release. Here's what you do. In your plugins directory, rename oldlivestream.pyc to oldlivestream.pyc.old and livestream.pyc to livestream.pyc.old or something.

Download this new livestream.pyc and place it into the same plugins directory.

https://drive.google.com/file/d/0B-D78F7kekqzd1Z1cFF4ZGdFNkE/view?usp=sharing

**Comment by bonacker** [comment]
Both the workaround and the new plugin work. Thanks!!!
