### ISSUE TITLE
Trouble with Twitch OAuth token

### ISSUE THREAD

**Issue by thejaydot** [chrippa/livestreamer#855]
I can only assume that I'm missing something super obvious, but when I try to use --twitch-oauth-token TOKEN, it just shows the help message and doesn't seem to authenticate with Twitch (at least, I still can't access any subscriber-only content via Livestreamer for channels that I'm subscribed to). Any help would be greatly appreciated!

**Comment by chrippa** [comment]
You have to use it as command line option when starting the stream like `livestreamer --twitch-oauth-token token twitch.tv/... best` or preferably, put it in your [config file](http://docs.livestreamer.io/cli.html#configuration-file).

**Comment by thejaydot** [comment]
D'oh, works perfectly – thank you!

**Comment by 7ylxr9** [comment]
Thanks, works perfectly and I don't need anymore headache trying to get a config file to work.
