### ISSUE TITLE
Video doesn't work in MPC-HC for some twitch streams unless --player-passthrough is used

### ISSUE THREAD

**Issue by VerGreeneyes** [chrippa/livestreamer#858]
With some streams I consistently only get audio in MPC-HC unless I use --player-passthrough hls,http,rtmp (I didn't check which of the three is required). Going to the video properties in MPC-HC shows that there's no video at all when this happens. I've had this since forever, but never with anyone who streams regularly, so I wasn't sure whether to report it. However, I get this on www.twitch.tv/furiouspaul, and he streams fairly often, so I figured now was the time.

I don't know whether this is related to certain codecs or certain settings. I've also noticed that video doesn't always start on some other streams, but it usually works when I try again, so there may be some race condition that some streams consistently lose. Or that may be a different bug.

I'm using the latest nightly of livestreamer and MPC-HC, but this is not a recent regression. Let me know if there's any logging I can enable to help debug.

**Comment by chrippa** [comment]
This is a [known issue](http://docs.livestreamer.io/players.html#mpc-hc-only-plays-sound-on-twitch-streams) (#346), it seems to be caused by badly muxed streams from Twitch, but since only MPC-HC is affected I don't consider it a Livestreamer bug.

**Comment by VerGreeneyes** [comment]
Ah, thank you.
