### ISSUE TITLE
[HELP] Twitch with Livestreamer

### ISSUE THREAD

**Issue by tonykuwabara** [chrippa/livestreamer#859]
I installed the livestreamer, the twitch plugin that a friend sent me and the VLC but the error is happening: http://puu.sh/hjV7J/892673c503.png

**Comment by skulblakka** [comment]
Looks like you are using [twitch-livestreamer-gui](https://github.com/bastimeyer/livestreamer-twitch-gui) and it has some kind of connection error. Make sure to check your Firewall and internet connection. If the problem persists you could consider opening a new issue over there.
