### ISSUE TITLE
stream from connected devices

### ISSUE THREAD

**Issue by navaneetharaopy** [chrippa/livestreamer#867]
I have a easy-cap video capturing device connected to USB port. The device gets identified with name  /dev/video0 . Can  i stream the signal received from the device connected at USB port? 

If I try following command  `livestreamer /dev/video0 best --player omxplayer --fifo` i get error. So is there any other solution for this problem.

Board : Raspberry pi 2
OS : Raspbian wheezy
video player : omxplayer

**Comment by chrippa** [comment]
Reading video from capture cards is out of scope for this project. I believe you can use ffmpeg or a video player with support for v4l to accomplish this instead.
