### ISSUE TITLE
Crunchyroll authentication not working on windows nightly build version

### ISSUE THREAD

**Issue by BenKettlewell** [chrippa/livestreamer#871]
I was affected by bug #864 
As soon as it was fixed I downloaded the nightly build and now I can't authenticate my crunchyroll account.
If I change the url to non-restricted content it works fine;however, even though I give it credential info it doesn't show up in the "My Devices" section on crunchyroll.

![tmpbug](https://cloud.githubusercontent.com/assets/7477112/7363611/824affce-ed31-11e4-8b04-5bab83159f58.PNG)

Thanks all, love your work :+1:

**Comment by chrippa** [comment]
I'm not able to reproduce this here. Does [--crunchyroll-purge-credentials](http://docs.livestreamer.io/cli.html#cmdoption--crunchyroll-purge-credentials) help?

**Comment by BenKettlewell** [comment]
It does not. I've fiddled with a bunch of different command orders and options, re installing, purging, etc and they all work except on restricted content (I've also tried several restricted content url's, none of them work). I deauthorized the ps3 accounts from crunchyroll's site to see if it would fix #864 and haven't been able to add them back. 
If there's more info I can get that might help let me know.

**Comment by BenKettlewell** [comment]
Tried the new version 1.12.2 that is now up as an installer (as opposed to the nightly build I was using before) still with no luck.

**Comment by stormagnet** [comment]
Same issue here- both in Win7 and Ubuntu 15.04.

**Comment by BenKettlewell** [comment]
Update that the issue seems to have resolved itself. Since my last post 14 days ago I have changed absolutely nothing for my setup. I'm still using 1.12.2 with the windows installer and haven't modified anything to do with livestreamer's setup. Just tried it again today and it registered a new device as a Iphone/Ipod Touch. If I can figure out what changed or if the problem comes back I'll be sure to let you know.
