### ISSUE TITLE
Cant play rtmp link

### ISSUE THREAD

**Issue by expandables2** [chrippa/livestreamer#874]
Hi i am tryin to play this rtmp link livestreamer  rtmp://89.248.172.159:443/liverepeater playpath=49 swfUrl=http://popeoftheplayers.eu/atdedead.swf live=1 pageUrl=http://popeoftheplayers.eu/crichd.php?id=49&width=530&height=370 token=#atd%#$ZH best  --player vlc --fifo --player-args "--vol 300 --win \"0 0 1920 1080\" {filename}"
 

But it doesn't work. I'm i doing it wrong?

**Comment by 0880** [comment]
````
livestreamer "rtmp://89.248.172.159:443/liverepeater playpath=49 swfUrl=http://popeoftheplayers.eu/atdedead.swf live=1 pageUrl=http://popeoftheplayers.eu/crichd.php?id=49&width=530&height=370 token=#atd%#$ZH" best
[cli][info] Found matching plugin stream for URL rtmp://89.248.172.159:443/liverepeater playpath=49swfUrl=http://popeoftheplayers.eu/atdedead.swf live=1 pageUrl=http://popeoftheplayers.eu/crichd.php?id=49&width=530&height=370 token=#atd%#$ZH
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
````

**Comment by biezom** [comment]
on linux change " >>>' 
<pre>livestreamer 'rtmp://89.248.172.159:443/liverepeater playpath=49 swfUrl=http://popeoftheplayers.eu/atdedead.swf live=1 pageUrl=http://popeoftheplayers.eu/crichd.php?id=49&width=530&height=370 token=#atd%#$ZH' best</pre>
