### ISSUE TITLE
Download entire /v/ VoD from Twitch while broadcast is still ongoing.

### ISSUE THREAD

**Issue by MorningLightMountain** [chrippa/livestreamer#876]
It is currently not possible to download a /v/ VoD while the livestream which "writes" to this VoD is still ongoing. Is this a bug? Is this a consequence of twitch using the new VoD system? 

Thanks

**Comment by chrippa** [comment]
It's because they are DVR-like streams - live but with the ability to jump backwards. You can use [--hls-live-edge](http://docs.livestreamer.io/cli.html#cmdoption--hls-live-edge) to jump backwards, e.g. `--hls-live-edge 99999` would probably start at the beginning.

**Comment by Nicholi** [comment]
Solution works great :)
