### ISSUE TITLE
Not work on Douyutv.com.

### ISSUE THREAD

**Issue by thelastfantasy** [chrippa/livestreamer#886]
>livestreamer http://www.douyutv.com/50016

[cli][info] Found matching plugin douyutv for URL http://www.douyutv.com/50016
error: Unable to validate JSON: Unable to validate key 'data': {u'owner_weight':
 u'118.75t', u'rtmp_url': u'', u'show_time': u'1430651866', u'show_details': u'\
u4e3b\u64ad17\u5c81 \u4f1a\u73a9\u4e00\u5207AP \u5e05\u5230\u6389\u6e23\u559c\u6
b22\u7684\u8ba2\u9605\u8c22\u8c22\u5566 \u96f6\u98df\u5e97http://chiqiangge.niup
u.com/\u8c22\u8c22\u5566', u'servers': [{u'ip': u'182.18.47.18', u'port': u'8058
'}, {u'ip': u'182.18.47.10', u'port': u'8012'}, {u'ip': u'182.18.47.23', u'port'
: u'8023'}, {u'ip': u'182.18.47.18', u'port': u'8054'}, {u'ip': u'182.18.47.23',
 u'port': u'8026'}, {u'ip': u'182.18.47.17', u'port': u'8049'}, {u'ip': u'182.18
.47.23', u'port': u'8029'}, {u'ip': u'182.18.47.22', u'port': u'8019'}, {u'ip':
u'182.18.47.17', u'port': u'8047'}, {u'ip': u'182.18.47.23', u'port': u'8034'}],
 u'rtmp_cdn': u'', u'room_src': u'http://staticlive.douyutv.com/upload/web_pic/6
/50016_1505040133_thumb.jpg', u'subject': u'', u'fans': u'664156', u'room_id': u
'50016', u'online': 535888, u'specific_status': u'1', u'tags': u'', u'room_name'
: u'\u5927\u5e08\u5f3a\u51b2\u738b\u8005', u'use_p2p': u'0', u'vod_quality': u'0
', u'rtmp_multi_bitrate': u'', u'owner_avatar': u'http://uc.douyutv.com/avatar.p
hp?uid=976810&size=big', u'game_url': u'/directory/game/LOL', u'nickname': u'\u6
211\u64e6\u4f60', u'rtmp_live': u'', u'owner_uid': u'976810', u'specific_catalog
': u'', u'url': u'/50016', u'cate_id': u'1', u'game_name': u'\u82f1\u96c4\u8054\
u76df', u'show_status': u'1'} does not equal None or Unable to validate key 'rtm
p_multi_bitrate': Type of u'' should be 'list' but is 'unicode' or Type of u'' s
hould be 'dict' but is 'unicode'

**Comment by chrippa** [comment]
Unfortunately the douyutv plugin is currently broken. The API now requires a special token to be generated, but noone has reverse engineered how this is done yet. See #809 for more information.
