### ISSUE TITLE
livestreamer incorrectly insists I need python-librtmp?

### ISSUE THREAD

**Issue by dnslocombe** [chrippa/livestreamer#892]
I installed livestreamer on my Fedora 21 system. When I tried to
access NASA TV's ustream live coverage, livestreamer said
I needed the python-librtmp package for ustreamtv to work.

There is no such package in Fedora. (BTW, yum tells me I have
librtmp (.so) library installed already. Also librtmp-devel. But
"yum search librtmp" says they are all that is available.
I.e. there is no python-librtmp package available for Fedora 21.
Indeed, there is nothing by that name in rpmfind for *any* Fedora.)

So I tried to install it using pip, but pip says that it is already
installed in the python2.7 tree. Indeed I can see a librtmp
directory there, well-populated:

      /usr/lib64/python2.7/site-packages/librtmp/

Looks like livestreamer is testing for a python-librtmp RPM package
which Fedora is not going to have because the s/w is included
in its base RPM package for python... at least that is what it looks like.

I also updated livestreamer to 1.17.2-1.fc21 from updates-testing
without any improvement in the situation.

**Comment by chrippa** [comment]
I think this may be because the Fedora package of Livestreamer is based on Python 3. Try `pip3 install python-librtmp`.

**Comment by dnslocombe** [comment]
Yes, that was the problem. I did:

   # pip3 install cffi    (which installed both cffi and pycparser for python3)
   # pip3 install python-librtmp

and then

$ livestreamer http://www.ustream.tv/channel/6540154 best

just worked.  There was a pause after 3 seconds, presumably a buffering issue,
but it got past that. I assume if I now do the config things needed for better
buttering, and perhaps threads, I'll be a happy camper.

The documentation could mention the python3 dependency and the use of "pip3" to
do the updates, not just "pip", and that might help others.
(i.e. on this page: https://github.com/chrippa/python-librtmp  where it tells us to use "pip".
I didn't know about pip3, nor that python3 was the issue -- I don't know python. Or is
this a "Fedora thing", because Fedora still uses python 2 for stuff so supports both?)

Otherwise I think you can close this bug.

**Comment by dnslocombe** [comment]
On 2015-05-06 13:47, Christopher Rosell wrote:
> I think this may be because the Fedora package of Livestreamer is based on Python 3. Try |pip3 install python-librtmp|.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/chrippa/livestreamer/issues/892#issuecomment-99550933>.
>

BTW, thanks for the quick response. I'm sure I'll find lots of uses for livestreamer in future.
