### ISSUE TITLE
Question about streams.

### ISSUE THREAD

**Issue by expandables2** [chrippa/livestreamer#893]
Can livestreamer play like  streamlive playlist from here http://www.kerman.hr/forum/index.php?topic=17946.0
Is it anyway livestreamer can play and read the m3u file that has something like this (Action Movies 2014 (HD)
8t7yzaodzxwqguu)

**Comment by chrippa** [comment]
I don't think playing playlists (with more than one stream in) really fits the Livestreamer CLI usage, you'll have to enter the URL of the stream you want watch instead. Though the streamlive plugin is currently broken (see #739), so that will not work etiher currently.
