### ISSUE TITLE
error on vaughnlive

### ISSUE THREAD

**Issue by fadster** [chrippa/livestreamer#899]
Hello,

As of this evening, I'm getting this error on vaughnlive:

C:\Program Files (x86)\Livestreamer>livestreamer.exe "http://vaughnlive.tv/lmshows_mws" live
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/lmshows_mws
error: Unable to validate response text: Minimum length is 2 but value is 1

It was working fine this morning.

- fadster

**Comment by fadster** [comment]
Nevermind, just noticed a fix was checked-in 6 hours ago.

Thanks!

- fadster

**Comment by Xan-5131** [comment]
I still have this issue, even after a reinstall.

**Comment by fadster** [comment]
The installer hasn't been updated.
