### ISSUE TITLE
vaughnlive changes cause new problem

### ISSUE THREAD

**Issue by potentate** [chrippa/livestreamer#904]
livestreamer http://vaughnlive.tv/newzviewz
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/newzviewz
error: Unable to validate response text: Minimum length is 2 but value is 1

**Comment by betagan** [comment]
duplicate of #897 ?

should be fixed in 24805585ed0303a9ef84106e1919b1c396370119#diff-42b41f48ea37ae1e70234cbeea2675f1

**Comment by potentate** [comment]
Yes, it works. Thanks!

**Comment by cloud90** [comment]
how to make change in the file?

**Comment by potentate** [comment]
see 
https://github.com/chrippa/livestreamer/commit/24805585ed0303a9ef84106e1919b1c396370119

**Comment by fadster** [comment]
when can we expect an updated installer?

**Comment by skulblakka** [comment]
Have you tried using the [nightly build](http://docs.livestreamer.io/install.html#nightly-build)?

**Comment by fadster** [comment]
Thank you, I wasn't aware of them. It works! :)
