### ISSUE TITLE
TVPlayer.com broken

### ISSUE THREAD

**Issue by RedPenguin2** [chrippa/livestreamer#909]
It seems that TVPlayer.com has broken something a few days ago.

I had a Windows bat script that recorded them just fine and now I get "404 Not Found" for the m3u8 files any more. Same with the TVPlayer Kodi/XBMC addon.

I noticed that livestreamer is experiencing the exact same error.

[cli][info] Found matching plugin tvplayer for URL http://tvplayer.com/watch/trutv
error: Unable to open URL: http://live.cdn.tvplayer.com/8C16FNV3Z9J3DAWSFY6T/playlist.m3u8?e=1431699854&h=fbdf8409006f0cd7d632cba860b79b89 (404 Client Error: Not Found)

I ran Wireshark on each method and while it works playing in the browser, the only thing I can see differently that the browser is doing is it's using the SWF file in the "Referrer" in the HTTP headers.

Also it could be the cookie also but this just seems less likely.

**Comment by biezom** [comment]
hi
need user agent

livestreamer --http-header "User-Agent=Mozilla/5.0 (Windows NT 5.1; rv:37.0) Gecko/20100101 Firefox/37.0"  "http://tvplayer.com/watch/trutv" best
[cli][info] Found matching plugin tvplayer for URL http://tvplayer.com/watch/trutv
[cli][info] Available streams: 1416k, 2029k, 2745k (best), 395k, 64k (worst), 803k
[cli][info] Opening stream: 2745k (hls)
[cli][info] Starting player: /usr/bin/vlc

**Comment by RedPenguin2** [comment]
Oh ok that worked. Thank you!

I could have swore I tried User-Agent before in my script, but I may have
accidentally coded it wrong.

Either way, using livestreamer is so much easier and cross platform :)

**Comment by chrippa** [comment]
Fixed by #929.
