### ISSUE TITLE
Handling files bigger than 2 gb on 64-bit systems

### ISSUE THREAD

**Issue by luizpdlh** [chrippa/livestreamer#910]
Hello,

Is there a way to handle files bigger than 2GB? E.g. when it reaches 2gb, start a new file? I'm trying to save big streams and I always bump into the 2GB file size limit.

Thank you.

**Comment by VackerSimon** [comment]
2GB limit? I left it on over the night and:
`[download][kimjye.mp4] Written 4.70 GB (10h31m9s @ 2.0 KB/s)`

**Comment by luizpdlh** [comment]
@VackerSimon That's weird :( I've tried on my Macbook Pro, on Ubuntu 14.04 64 bit and Debian 7 64 bit and I can only write out 2GB (2ˆ32 bits) as if it was running on 32 bits. I've only saved streams from livestream. Any tips?

**Comment by VackerSimon** [comment]
@luizpdlh I forgot to mention that this was on Windows 8.1, maybe the problem doesn't occur on Windows? I can try it on one of my servers to see if it occurs.

That stream I tried above was from AfreecaTV (Korean) btw.

**Comment by luizpdlh** [comment]
@VackerSimon That would help a lot, thanks! I'll give it a try on Windows 7 but I'm running it over Parallels on my Mac

**Comment by chrippa** [comment]
Are you writing to a file system that only supports 2GB files, such as FAT32 or HFS?

Are you getting any error?

**Comment by VackerSimon** [comment]
@chrippa The limit for FAT32 is 4GB but you're correct that the limit for HFS (not Plus) is 2GB.

**Comment by luizpdlh** [comment]
Ubuntu is on a VPS running ReiserFS, so that could be it, but on Mac I'm trying to write to an ext3 partition and Debian is on extFAT. I do not get any errors, it simply terminates when the file size reaches 2GB. I'm always attempting to fetch live streams from news.livestream.com. I'll try again on Monday with another stream on all systems and post the entire output.

Thanks a lot for the quick replies!

**Comment by chrippa** [comment]
I think I know why this happens, the HTTP streams from livestream.com sends a `Content-Length` header with the value 2GB. The server is probably closing the connection after that amount of data has been read. You can try using the HLS streams (use `--stream-types hls` to filter out the other ones) instead.

**Comment by luizpdlh** [comment]
@chrippa That makes a lot of sense. If I attempt to download the stream on the browser it creates a 2GB file as well. Thanks a lot for that catch, I tried using hls other times with livestreamer but it didn't work out. I'll try it out on monday with the latest version!

**Comment by luizpdlh** [comment]
It worked with the `--stream-types hls` option, thanks! Maybe it's something to clarify on livestream.
