### ISSUE TITLE
Suddenly cannot watch streams in source quality on twitch

### ISSUE THREAD

**Issue by ignarteaga** [chrippa/livestreamer#911]
I was watching a stream on twitch at source quality (with ~6 mb of download speed) and now i cant even watch a stream in medium quality without lag.

Has anybody suddenly had this same issue today?

Thank you,

**Comment by ignarteaga** [comment]
PS: i was able to watch streams at source quality before today, in case i did not make that clear...

**Comment by ignarteaga** [comment]
here is a paste of the dump of what happens when i try to access the stream on cmd:

Microsoft Windows [Versión 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Reservados todos los derechos.

C:\Users\Ignacio>livestreamer twitch.tv/gfinitytv source
[cli][info] Found matching plugin twitch for URL twitch.tv/gfinitytv
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source (best
)
[cli][info] Opening stream: source (hls)
[stream.hls][error] Failed to open segment 8841: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
1-SDXr.ts (timed out)
[stream.hls][error] Failed to open segment 8850: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
0-rE6Z.ts (timed out)
[stream.hls][error] Failed to open segment 8844: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
4-ZiJn.ts (timed out)
[stream.hls][error] Failed to open segment 8842: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
2-sYVs.ts (timed out)
[stream.hls][error] Failed to open segment 8845: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
5-sAEm.ts (timed out)
[cli][error] Failed to read data from stream: Read timeout
[stream.hls][error] Failed to open segment 8850: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
0-rE6Z.ts (timed out)
[stream.hls][error] Failed to open segment 8845: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
5-sAEm.ts (timed out)
[stream.hls][error] Failed to open segment 8845: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
5-sAEm.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8843: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
3-HqoC.ts (timed out)
[stream.hls][error] Failed to open segment 8844: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
4-ZiJn.ts (timed out)
[stream.hls][error] Failed to open segment 8844: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000884
4-ZiJn.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8852: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
2-2dpm.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8852: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
2-2dpm.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8852: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
2-2dpm.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8853: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
3-5GqN.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8853: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
3-5GqN.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8853: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
3-5GqN.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8854: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
4-XR9f.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8854: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
4-XR9f.ts (404 Client Error: Not Found)
[stream.hls][error] Failed to open segment 8854: Unable to open URL: http://video22.d
fw01.hls.ttvnw.net/hls-6dbde4/gfinitytv_14425273600_243834820/chunked/index-000000885
4-XR9f.ts (404 Client Error: Not Found)

**Comment by ignarteaga** [comment]
edit 2: here is my livestreamerrc config

player="C:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=10000 --network-caching=10000
hls-segment-threads=10
http-ignore-env

with this config, i was able to watch source stream with minimal issues for the last 4 months...

**Comment by chrippa** [comment]
This looks like a connection issue between your ISP and Twitch.

**Comment by fragtion** [comment]
Try the  hls-segment-threads and hds-segment-threads options. Worked for me
