### ISSUE TITLE
--retry-streams tries forever for Twitch

### ISSUE THREAD

**Issue by Nicholi** [chrippa/livestreamer#913]
For some reason as soon as I specify the --retry-streams parameter with any valid value (greater than 0), livestreamer will attempt to pull that stream forever when the stream is not available. I'm using this with the twitch.tv plugin, so maybe it is specific to that? If I set --retry-streams 60 --retry-open 2, livestreamer should attempt to get the stream a total of 2 times, retrying every 60 seconds for a total of 120 seconds (2 minutes) right, and then exit if it can't get the stream?

Example without:
> $ livestreamer -l debug -o ~/test.ts twitch.tv/kaceytron
> [cli][info] Found matching plugin twitch for URL twitch.tv/kaceytron
> [plugin.twitch][info] Attempting to authenticate using OAuth token
> [plugin.twitch][info] Successfully logged in as ****
> error: No streams found on this URL: twitch.tv/kaceytron

Immediately exits as expected when streamer is not streaming. As soon as I add the --retry-streams parameter (without even using --retry-open, which should default to 1 anyways), it will sit forever waiting for stream. Presumably until the next day when the streamer starts their stream again. I have this running in a crontab daily and I let the process from a previous day last until the next day and sure enough it started writing the stream to file. Which is sort of the problematic part because the process from the current day is also outputting the file.

Example with:
> $ livestreamer -l debug -o ~/test.ts --retry-streams 1 twitch.tv/kaceytron
> [cli][info] Found matching plugin twitch for URL twitch.tv/kaceytron
> [plugin.twitch][info] Attempting to authenticate using OAuth token
> [plugin.twitch][info] Successfully logged in as ****
> [cli][info] Waiting for streams, retrying every 1.0 second(s)

This will not promptly exit after 1 second...or 10 seconds, or hours. Even setting --retry-open to be sure it isn't randomly being set to some insane value it will not stop attempting to pull stream. I added the debug loglevel in the hopes it would print something useful, it doesn't. My config file only has some additional values for http timeouts/threads/edge settings, nothing for stream retry though. If you think it may be some other setting I have I'll supply the full file.

> $ python --version
> Python 2.7.3
> $ livestreamer --version
> livestreamer 1.12.2

**Comment by betagan** [comment]
You are misinterpreting the commandline parameters.

The behavior is described in the [http://docs.livestreamer.io/cli.html#stream-options|Docs].

This means:

if `--retry-streams` is specified and **no streams are found by the plugin** for the given url, livestreamer will wait for the given amount of seconds and retry again. This will loop infinitely until streams are found or the process is killed by the user. 

`--retry-open` on the other hand handles the retry **once a stream has been found**. This is the number of times livestreamer will try to open a stream found by the plugin.


A parameter for exiting after a certain number of retries during stream fetching stage is not currently implemented.

**Comment by Nicholi** [comment]
Ah HA! Ok that makes more sense. I'll rework the script with that in mind then. Though if you did have a retry then exit parameter that may be useful to others even.
