### ISSUE TITLE
streamlive.to how to get the token

### ISSUE THREAD

**Issue by expandables2** [chrippa/livestreamer#915]
Hi how i am trying to get streamlive to work for me but i just need the token so how  do i find streamlive token?

**Comment by expandables2** [comment]
anyone?

**Comment by expandables2** [comment]
How to obtain the token what do i need to am looking at sports devil and it says this.

#item_info_name=title
#item_info_from=@PARAM1@
#item_info_build=iLive - %s

item_info_name=pageUrl
item_info_from=@PARAM1@
item_info_build=http://www.streamlive.to/embedplayer.php?width=640&height=400&channel=%s&autoplay=true

item_info_name=req
item_info_from=pageUrl
item_info_convert=getInfo('%s','.*getJSON\("([^'"]+)".*streamer[:,]\s*['"]([^'"]+)['"].*file[:,]\s*['"]([^'"]+).flv['"]','@REFERER@','server|rtmp.tmp|file')
item_info_build=%s

item_info_name=token
item_info_from=http:' + server
item_info_convert=getInfo('%s','.*?token":"([^'"]+).*','http://www.streamlive.to/embedplayer.php')
item_info_build=%s

item_info_name=rtmp
item_info_from=rtmp.tmp
item_info_convert=replace('%s','\','')
#item_info_convert=replace('%s','watch1','watch3')
item_info_build=%s

item_info_name=app
item_info_from=rtmp
item_info_convert=parseText('%s','.*.*rtmp://[\.\w:]*/([^\s]+)')
item_info_build=%s

item_info_name=url
item_info_from=rtmp + ' app=' + app + ' playpath=' + file + ' swfUrl=http://www.streamlive.to/player/player_ilive_embed.swf live=1 timeout=15 token=' + token + ' swfVfy=1 pageUrl=http://www.streamlive.to
item_info_build=%s

**Comment by chrippa** [comment]
I can't answer your question, but if you figure it out, please submit a patch to fix the plugin.

I'll close this issue in favor of a single issue regarding streamlive, which is #739.
