### ISSUE TITLE
UDP stream auto ended

### ISSUE THREAD

**Issue by sonnvl** [chrippa/livestreamer#917]
livestreamer "httpstream://http://203.162.235.124:5555/udp/225.2.100.46:5000" best -o filename.ts
[cli][info] Found matching plugin stream for URL httpstream://http://203.162.235.124:5555/udp/225.2.100.46:5000
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
[download][filename.ts] Written 5.1 MB (29s @ 99.9 KB/s)
[cli][info] Stream ended

I tried many times any the longest duration of video I obtain only 2-3 mins.
Link stream: http://203.162.235.124:5555/udp/225.2.100.46:5000

**Comment by chrippa** [comment]
Can you confirm that this stream works on the original source or via a player capable of HTTP streams such as VLC? If not, then it is probably not a normal HTTP stream and requires special support to be added.
