### ISSUE TITLE
Plugin douyutv crash.

### ISSUE THREAD

**Issue by kexul** [chrippa/livestreamer#925]
Thanks for the great job you guys have done!
There is the output of the terminal when watching the live stream in douyutv.

livestreamer douyutv.com/cold
[cli][info] Found matching plugin douyutv for URL douyutv.com/cold
error: Unable to validate JSON: Unable to validate key 'data': {u'owner_weight': u'92.75t', u'rtmp_url': u'', u'show_time': u'1432518835', u'show_details': u'QQ\u7fa4\uff1a195079867\n\u725b\u94fa\u5168\u573a8\u6298\uff1aniupu.com/cold\n\u65b0\u6d6a\u5fae\u535a\uff1a\u51b7\u4e86\u4e2a\u51b7\n\u817e\u8baf\u5fae\u535a\uff1apc\u51b7\u51b7', u'servers': [{u'ip': u'182.18.47.17', u'port': u'8042'}, {u'ip': u'182.18.47.17', u'port': u'8043'}, {u'ip': u'182.18.47.17', u'port': u'8049'}, {u'ip': u'182.18.47.23', u'port': u'8032'}, {u'ip': u'182.18.47.23', u'port': u'8023'}, {u'ip': u'182.18.47.22', u'port': u'8020'}, {u'ip': u'182.18.47.23', u'port': u'8036'}, {u'ip': u'182.18.47.18', u'port': u'8055'}, {u'ip': u'182.18.47.22', u'port': u'8039'}, {u'ip': u'182.18.47.10', u'port': u'8005'}], u'rtmp_cdn': u'', u'room_src': u'http://staticlive.douyutv.com/upload/web_pic/0/20360_1505252327_thumb.jpg', u'subject': u'', u'fans': u'277746', u'room_id': u'20360', u'online': 442537, u'specific_status': u'1', u'tags': u'', u'room_name': u'\u51b7\u51b7\u76f4\u64ad\u95f4 TI5\u4e2d\u56fd\u533a\u9884\u9009\u8d5b', u'use_p2p': u'0', u'vod_quality': u'0', u'rtmp_multi_bitrate': u'', u'owner_avatar': u'http://uc.douyutv.com/avatar.php?uid=498062&size=big', u'game_url': u'/directory/game/DOTA2', u'nickname': u'Pc\u51b7\u51b7', u'rtmp_live': u'', u'owner_uid': u'498062', u'specific_catalog': u'cold', u'url': u'/cold', u'cate_id': u'3', u'game_name': u'DOTA2', u'show_status': u'1'} does not equal None or Unable to validate key 'rtmp_multi_bitrate': Type of u'' should be 'list' but is 'unicode' or Type of u'' should be 'dict' but is 'unicode'

environment:Ubuntu 15.04 and livestreamer 1.12.2

**Comment by 0880** [comment]
[#886] (https://github.com/chrippa/livestreamer/issues/886) 
[#809] (https://github.com/chrippa/livestreamer/issues/809)

**Comment by kexul** [comment]
Thanks for that :+1:
