### ISSUE TITLE
Chaturbate plugin periodically broken

### ISSUE THREAD

**Issue by furrydad** [chrippa/livestreamer#927]
in some instances, the chaturbate plugin cannot find a playable stream, even though one is clearly playing from the http location.  The only difference I can find between streams that livestreamer can find and those it cannot from the play url is the difference of one number.  Specifically,  livestreamer can play:

rtmp://origin7.stream.highwebmedia.com/live-origin/hung_london_lad-sd-fd87c37b4225dcc51ea551670eaba890baa65cdcd0715266dbb68757995fb1f7'

but cannot play

rtmp://origin1.stream.highwebmedia.com/live-origin/allyours129-sd-f25f66b9b5dd69c68bce6a74a89ee8a67c9b9c10e2e8212b4813357089c04d3d'

the only difference I can see is the "origin1" instead of the "origin7"

Tried to look at the plugin in notepad, but could understand nothing, so I thought I'd leave it for you guys.

**Comment by 0880** [comment]
Livestreamers chaturbate plugin picks the HLS stream. The reason why Livestreamer cannot play the second stream, may be some kind of restriction. The second stream is not even accessible through their website.

````
https://chaturbate.com/allyours129
````
````
Access Denied. This room is not available to your region or gender.
````
