### ISSUE TITLE
[Feature-Request] Pass-through fallback if no plugin available?

### ISSUE THREAD

**Issue by hpmueller1971** [chrippa/livestreamer#930]
Hi,

would it be possible to add a pass-through option, so that if no plugin can handle a url, it would pass it to the appropriate handler (http:// links like *.m3u directly, rtmp:// to rtmpdump)...? It would allow to use livestreamer for all streaming-urls, not just the explicitly supported...

Regards

/hp

**Comment by skulblakka** [comment]
Do you mean something like [this](http://docs.livestreamer.io/cli.html#playing-built-in-streaming-protocols-directly)?

**Comment by hpmueller1971** [comment]
Ahhh, damn, i've searched for something like that for an hour, but i looked more for something like "pass" or http://, so didn't get the idea hls:// could be a valid url. Many thanks :smiley:
