### ISSUE TITLE
Can Livestreamer play FFmpeg ?

### ISSUE THREAD

**Issue by ian10951** [chrippa/livestreamer#931]
Hi 
Im trying to open a stream using Livestreamersrv and Livestreamer on an enigma2 box which I believe is FFmpeg

When the connection is made i get the 200 ok response,but then Livestreamersrv throws an exception of 

exception no data when using httpstream

other times i get

exception read timeout when using hls

This is how I'm connecting

http://127.0.0.1:88/hls://http://iptv.wssiptv.com:80/live/VIPWSS/OUEIjhuawoijasd/101.ts

any insight please ?

**Comment by ian10951** [comment]
This is from my telnet window when using the debug livestreamersrv manualstart

localhost.localdomain - - [27/May/2015 12:24:10] "GET /hls://http://iptv.wssiptv
.com:80/live/VIPWSS/OUEIjhuawoijasd/101.t HTTP/1.1" 200 -
localhost.localdomain - - [27/May/2015 12:24:10] URL: hls://http://iptv.wssiptv.
com:80/live/VIPWSS/OUEIjhuawoijasd/101.t Quality: best
Streams: ['live', 'worst', 'best']
<HLSStream('http://iptv.wssiptv.com:80/live/VIPWSS/OUEIjhuawoijasd/101.t')>
Got Exception:  Read timeout

**Comment by 10mins** [comment]
That is not a HLS stream.

**Comment by ian10951** [comment]
Well Ive tried http and hlsvariant but using those cause a segfault,only using hls allows connection.
So what stream type do you think it is ?

**Comment by 10mins** [comment]
It's a normal 'transport stream' stream. VLC can play it just fine. I no idea why httpstream:// does not work with it.

**Comment by ian10951** [comment]
Yes this is why I asked about FFmpeg.

I believe it may need that,but as you say its fine with VLC and Enigma2 Gstreamer.
I just cannot get it to play using Livestreamer.

**Comment by chrippa** [comment]
The problem is that the server seems to have banned the User-Agent for the library (requests) we use to do HTTP connections. A workaround is to use another User-Agent (or even empty).

Via the CLI:

    livestreamer --http-header "User-Agent=" httpstream://http://iptv.wssiptv.com:80/live/VIPWSS/OUEIjhuawoijasd/101.ts

Via applications using the library (e.g. livestreamersrv) use this URL:

    httpstream://http://iptv.wssiptv.com:80/live/VIPWSS/OUEIjhuawoijasd.ts headers={'User-Agent': ''}

**Comment by ian10951** [comment]
Many thanks chrippa.

As usual your a star and provider excellent support for us simpletons.

All links to that server now working through Livestreamer,so everything now remains in sync during playback (a major problem when using gstreamer)

Again thank you.

Ian.

**Comment by ian10951** [comment]
Hi

Sorry to reopen this issue but can you tell me how to add player continuous http to this livestreamersrv line ?
[code]httpstream://http://iptv.wssiptv.com:80/live/VIPWSS/OUEIjhuawoijasd.ts headers={'User-Agent': ''}[/code]

**Comment by chrippa** [comment]
Continuous HTTP is a feature in the commandline interface, it's not possible to use via the library. If you want such functionality you will have to add it to livestreamersrv.

**Comment by ian10951** [comment]
ok thank you
