### ISSUE TITLE
Is there a way to force livestreamer NOT to use a proxy?

### ISSUE THREAD

**Issue by jayceelock** [chrippa/livestreamer#933]
Hi, I use two browsers, Firefox and Chromium, on a University network. Chromium uses a http proxy to connect to the www, but cannot access some sites, such as locally hosted University sites or Youtube, which are blocked by the proxy. My Firefox is configured NOT to use a proxy and can access the sites that Chromium cannot, but I have to pay to access the rest of the www. Its a weird setup, I know.

The problem is that when I use livestreamer for a Youtube video (e.g. https://www.youtube.com/watch?v=EwTZ2xpQwpA), I get the following error: error: Unable to open URL: http://youtube.com/get_video_info (407 Client Error: Proxy Authentication Required), even though I did not specify it to use a proxy. Also, notice the different URL's, not sure if this is what's supposed to happen?

I went through the source code and couldn't figure out why it's trying to go through a proxy. Is there some setting I have to specify to force it NOT to use a proxy, like what my Firefox is set to do? Or am I being stupid?

**Comment by 10mins** [comment]
Why won't you just disable system proxy?

**Comment by jayceelock** [comment]
I tried that. Same result

**Comment by chrippa** [comment]
[--http-ignore-env](http://docs.livestreamer.io/cli.html#cmdoption--http-ignore-env) should tell Python not to use the system proxy. But if you already tried to disable it yourself it may not work.

**Comment by jayceelock** [comment]
Hmmm I've been looking for something like that. Normally, programs like wget won't work unless I specify the --no-proxy flag, so something like this should maybe work. Anyways, I'll try on Monday and report back

**Comment by jayceelock** [comment]
Yay, it works! Dunno why this would work, but disabling the system proxy doesn't. Anyways, closing the issue now.
