### ISSUE TITLE
douyu.tv not working.

### ISSUE THREAD

**Issue by xili7** [chrippa/livestreamer#938]
http://www.douyutv.com/AZW test link

Here's the results after typing 
livestreamer http://www.douyutv.com/AZW

![8 ozxaw dp m5 jeuiuk](https://cloud.githubusercontent.com/assets/8334742/7892649/e92f3e7a-060a-11e5-998b-02992fa49751.jpg)

**Comment by diegogarciaa** [comment]
Not working for me too. Same error.

**Comment by 0880** [comment]
This is a known issue: #886 #809
