### ISSUE TITLE
http://vaughnlive.tv/ 

### ISSUE THREAD

**Issue by expandables2** [chrippa/livestreamer#939]
Hi http://vaughnlive.tv/ same to be down

**Comment by 0880** [comment]
Works for me.

````
livestreamer "http://vaughnlive.tv/randallfrompolk" best
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/randallfrompolk
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
````

**Comment by Ordval** [comment]
While “Gilligan's Island” in Vaughnlive itself open in the browser 
I come as far as : [cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/mdufres2] then it turns off, with Livestreamer.

Is there a log file somewhere we can present here ?

**Comment by 0880** [comment]
I'm testing it right now.

````
livestreamer "http://vaughnlive.tv/mdufres2" best
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/mdufres2
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
````
Vaughnlive plugin seems to work correctly. Make sure you have rtmpdump installed. 
Log options [[1]] (http://docs.livestreamer.io/cli.html#cmdoption-l) [[2]] (http://docs.livestreamer.io/cli.html#cmdoption--subprocess-errorlog):

`--loglevel debug`
`--subprocess-errorlog`

**Comment by Ordval** [comment]
Thank You.
With CMD:
C:\Users\ORDVAL>livestreamer.exe "vaughnlive.tv/mdufres2" best
[cli][info] Found matching plugin vaughnlive for URL vaughnlive.tv/mdufres2
error: Unable to validate response text: Minimum length is 2 but value is 1

Isn’t it enough having RTMPDumpHelper 32 and 64 installed ? 
I have rtmpdump a bit all around the computer, but just in case I unzipped “rtmpdump-2.4-2013-12-22.zip” to [C:\Program Files (x86)\Rtmpdump 2.4 -13-12-22] and then put its directory in PATH. 

Is this where the log would end up :
C:\Users\ORDVAL\AppData\Local\Temp ? 
And how should it look ? like this: ~DFD879715EE7D08B3C.TMP ?

I’m on Win. 7

**Comment by 0880** [comment]
Are you using the latest [version] (http://livestreamer-builds.s3.amazonaws.com/livestreamer-latest-win32.zip)?
You can specify the location of rtmpdump with this option: `--rtmp-rtmpdump`

````
livestreamer.exe "http://vaughnlive.tv/mdufres2" best --rtmp-rtmpdump "X:\XX\rtmpdump.exe"
````

Or by editing the [configuration file] (http://docs.livestreamer.io/cli.html#configuration-file).

**Comment by Ordval** [comment]
If we're talking about 1.12.2 , yes. 
My installation date is May 16th and on the Release page it’s the 2nd, 
so no reason to update, but apparently should so.

Well,  a Big Thanks to You ! 
I unzipped “livestreamer-latest-win32”, pasted the vaughnlive.pyc in [C:\Program Files\VLC\Livestreamer\livestreamer-1.12.2-py2.7.egg\livestreamer\plugins]

But for future reference, where should vaughnlive.py go ?
It doesn’t seem to matter if it’s either in:
[C:\Users\ORDVAL\AppData\Roaming\livestreamer]   or
[C:\Users\ORDVAL\AppData\Roaming\livestreamer\plugins]. 

I’ll make a total reinstall later.

**Comment by 0880** [comment]
Since latest [release] (https://github.com/chrippa/livestreamer/releases) ([v1.12.2] (https://github.com/chrippa/livestreamer/releases/tag/v1.12.2)) [51 new commits] (https://github.com/chrippa/livestreamer/compare/v1.12.2...develop) were pushed to develop branch. Vaughnlive plugin was broken (#897) so  a [commit] (https://github.com/chrippa/livestreamer/commit/24805585ed0303a9ef84106e1919b1c396370119) was made to fix the issue. For Windows there are so called [nightly builds] (http://docs.livestreamer.io/install.html#nightly-build) which contain the latest development code.

**Comment by Ordval** [comment]
As this thread is closing I retract the install thing. I don’t know how....from a zip.
I tried manually putting everything in its place and the.exe did open but also with a lot of 
“Couldn’t find….” plugin-messages.
