### ISSUE TITLE
No streams found on this URL [Azubu]

### ISSUE THREAD

**Issue by karlww** [chrippa/livestreamer#943]
Livestreamer is unable to find a stream for any Azubu channel I give it, eg. http://www.azubu.tv/MarsTVMDLen which I am watching in browser right now.

livestreamer 1.12.2 on windows 8.1 x64

**Comment by the-mrd** [comment]
Same here, on Gentoo Linux amd64, with livestreamer 1.12.2.

**Comment by diegogarciaa** [comment]
Same here, windows 8.1, livestreamer 1.12.2

I was going to watch Mars TV Dota 2 League : (

**Comment by wolftankk** [comment]
#942 has resolved.

**Comment by diegogarciaa** [comment]
when he will release ?

**Comment by skulblakka** [comment]
If you don't want to wait for the new release just install from source or install the latest nightly build if you are on windows.

**Comment by diegogarciaa** [comment]
Thanks.
