### ISSUE TITLE
network caching

### ISSUE THREAD

**Issue by expandables2** [chrippa/livestreamer#950]
Hi how to set network caching to 5000?
I did --player  'vlc network-caching 5000'
Is that right?

**Comment by LinuxNewb27** [comment]
Best thing would be to add it to your config file

If windows, edit [code]%appdata%\livestreamer\livestreamerrc[/code] (with WordPad or Notepad) and add the code to the path you use for VLC (should be x86)

![image](https://cloud.githubusercontent.com/assets/4732566/8022801/c7cdcfa0-0ca7-11e5-9862-f588d037abd6.png)

Save the file and exit out of it.

Start livestreamer with just the url and source and you should see that it automatically loads the --network-caching

![image](https://cloud.githubusercontent.com/assets/4732566/8022804/06533a4e-0ca8-11e5-90fd-899107065c97.png)

**Comment by expandables2** [comment]
I am using linux not windows

**Comment by LinuxNewb27** [comment]
I'll have to boot up my Linux machine later today and try it out.

**Comment by chrippa** [comment]
It looks like you're editing `/usr/loca/bin/livestreamer` instead of the [config file](http://docs.livestreamer.io/cli.html#configuration-file).

**Comment by expandables2** [comment]
I just want vlc to cache the video stream before it plays. How do i do that on Linux?

**Comment by chrippa** [comment]
`livestreamer --player "vlc --file-caching=6000 --network-caching=6000"`.
