### ISSUE TITLE
'$' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by jawzz** [chrippa/livestreamer#953]
So I type
*$ livestreamer twitch.tv/faceittv source*
into the command line, and it gives me
*'$' is not recognized as an internal or external command, operable program or batch file*

**Comment by VackerSimon** [comment]
"$" is not part of what you should type. It's usually used (or at least interpreted by me) to mean that it's a line of commands/arguments to enter into a command prompt/terminal http://ubuntuforums.org/showthread.php?t=1852263&p=11297940#post11297940

**Comment by jawzz** [comment]
Oh thanks man, I feel stupid now.
