### ISSUE TITLE
Protected stream & --http-cookie

### ISSUE THREAD

**Issue by tp0** [chrippa/livestreamer#954]
Assuming the syntax is right, what is the problem?

    $ livestreamer --http-cookie "Cookie=_alid_=/TgBhTX2JPtZnWFZVjBYBA==; hdntl=exp=1434148711~acl=%2f*~data=hdntl~hmac=adec5aae7219181185084dd1868685093c966254d2dc25b22caff1b1d9bab475" "hls://nnnnnnn-lh.akamaihd.net/i/nnnnnn/nnnnnn@315603/master.m3u8" best --loglevel debug
    [cli][info] Found matching plugin stream for URL hls://nnnnnnn-lh.akamaihd.net/i/nnnnnn/nnnnnn@315603/master.m3u8
    [cli][info] Available streams: live (worst, best)
    [cli][info] Opening stream: live (hls)
    [stream.hls][debug] Reloading playlist
    [cli][error] Could not open stream: Unable to open URL: http://nnnnnnn-lh.akamaihd.net/i/nnnnnn/nnnnnn@315603/master.m3u8 (403 Client Error: Forbidden)

I tried this with --http-header too, with a user agent directly from the request headers.

What is the "hdntl" part in the cookie? I noticed that when I look at the page source and refresh it that the token attached to the embed link changes on every refresh. Does it simply expire so quickly that I can not copy-paste it quickly enough? (It may be that I don't know what I'm talking about.) It also opens in a browser Flash Player only when opened really quickly - a matter of couple of seconds:

    http://backvideo.ampi.tv/embed/z6m4vl?token=exp=1433953483~acl=/*~hmac=78264f89ca571c87cf56f2823840ebb4eecd971b717e405f4053684f74ee77e7

**Comment by chrippa** [comment]
If the token expires you'll probably have to write a plugin for the site in question, so the stream can be opened right after getting the URL.

**Comment by joejones14** [comment]
Hello tpo,

Thanks for your recommendation here: https://github.com/chrippa/livestreamer/issues/1037#issuecomment-133562265

Were you able to test a plugin to see if the token is expiring too fast?

**Comment by tp0** [comment]
Nope, such plugin does not exist and I'm not skilled.

**Comment by tp0** [comment]
Turns out I was trying this with the overly complicated way... just directly grabbing this from dev tools network traffic:

    livestreamer "hlsvariant://https://nnnnnnn-lh.akamaihd.net/i/nnnn_Live_BC2/nnn_nnnnn@nnnnn/master.m3u8?hdnts=exp=1442719240~acl=/*~hmac=353f8e7c291532162227d0224410400a4558a8aae88014df7316a40e50f7256d" best

```
livestreamer "hlsvariant://https://nnnnnnn-lh.akamaihd.net/i/nnnn_Live_BC2/nnn_nnnnn@nnnnn/master.m3u8?hdnts=exp=1442719240~acl=/*~hmac=353f8e7c291532162227d0224410400a4558a8aae88014df7316a40e50f7256d" best
[cli][info] Found matching plugin stream for URL hlsvariant://https://nnnnnnn-lh.akamaihd.net/i/nnnn_Live_BC2/nnn_nnnnn@nnnnn/master.m3u8?hdnts=exp=1442719240~acl=/*~hmac=353f8e7c291532162227d0224410400a4558a8aae88014df7316a40e50f7256d
[cli][info] Available streams: 270p (worst), 360p, 540p, 720p (best)
[cli][info] Starting player: mpv --osc=no --loop=inf --cache 8192
[cli][info] Got HTTP request from mpv 0.10.0
[cli][info] Opening stream: 720p (hls)
```
