### ISSUE TITLE
Youtube Live not working while normal youtube videos work fine

### ISSUE THREAD

**Issue by Flux3PO** [chrippa/livestreamer#955]
Hi, 
I was just trying to get a youtube livestream like this one:
https://www.youtube.com/watch?v=sw4hmqVPe0E
But I always get : 

[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=sw4hmqVPe0E
error: No streams found on this URL: https://www.youtube.com/watch?v=sw4hmqVPe0E

Any other Video e.g.:https://www.youtube.com/watch?v=K7zQGQlSdWU works fine.

I'm on 
[cli][info] Your Livestreamer version (1.12.2) is up to date!

**Comment by 0880** [comment]
````
livestreamer "https://www.youtube.com/watch?v=sw4hmqVPe0E" best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=sw4hmqVPe0E
[cli][info] Available streams: 1080p (best), 240p, 360p, 480p, 720p, 72p (worst)
[cli][info] Opening stream: 1080p (hls)
````

Seems that you can't access the stream due to some geographic restrictions.

**Comment by Flux3PO** [comment]
Doh !

I got 2 networks, one with an blocked ip and one with an working ip. I'm surfing using the working IP and streaming using the blocked ip :(

Thanks for your quick help
