### ISSUE TITLE
Livestream.com/nrl

### ISSUE THREAD

**Issue by MaveDodger** [chrippa/livestreamer#958]
I am having problems opening streams from livestream.com/nrl

I have not been able to open anything from that channel. I'm new to all this so please be gentle

Cheers,
Mave

**Comment by chrippa** [comment]
Works fine here, make sure the URL you're using is pointing directly to a live event e.g. `http://livestream.com/nrl/seaeaglesvtigers` and not `http://livestream.com/nrl`.

**Comment by 0880** [comment]
I have the same problem. Whatever I try, I always get this error message:

````
livestreamer "http://livestream.com/nrl/seaeaglesvtigers" best
[cli][info] Found matching plugin livestream for URL http://livestream.com/nrl/seaeaglesvtigers
error: No streams found on this URL: http://livestream.com/nrl/seaeaglesvtigers
````
````
livestreamer "http://livestream.com/WorldScienceFestival/ToInfinityandBeyond" best
[cli][info] Found matching plugin livestream for URL http://livestream.com/WorldScienceFestival/ToInfinityandBeyond
error: No streams found on this URL: http://livestream.com/WorldScienceFestival/ToInfinityandBeyond
````

**Comment by 0880** [comment]
Only live streams are supported. Archived events are currently not supported.

http://docs.livestreamer.io/plugin_matrix.html
