### ISSUE TITLE
Arte.tv live plugin does not work in current version

### ISSUE THREAD

**Issue by m0r0n** [chrippa/livestreamer#960]
Hi,

I just wanted to record that live stream from arte:
http://concert.arte.tv/de/hurricane-2015-livestream-vom-2006

I noticed, that the current version does that:

[cli][info] Found matching plugin artetv for URL http://concert.arte.tv/de/hurricane-2015-livestream-vom-2006
error: No streams found on this URL: http://concert.arte.tv/de/hurricane-2015-livestream-vom-2006

While version 1.10.2 does that:

[cli][warning] The option --best-stream-default is deprecated since version 1.9.0, use '--default-stream best' instead.
[cli][info] Found matching plugin artetv for URL http://concert.arte.tv/de/hurricane-2015-livestream-vom-2006
[cli][info] Available streams: 142k, 300k, 64k (worst), 700k (best)
[cli][info] Opening stream: 700k (hls)
[download][live.mp4] Written 203.5 MB (39m46s @ 95.2 KB/s)   

So in the older version of the plugin it works. Would be great if whatever has changed could also be changed in the recent version.

Thanks and cheers!

**Comment by chrippa** [comment]
Fixed by #961.
