### ISSUE TITLE
YouTube 60fps live streams compatibility with livestreamer

### ISSUE THREAD

**Issue by MorningLightMountain** [chrippa/livestreamer#963]
Win8.1 livestreamer 1.12.2

YouTube recently implemented 60fps live streaming. Is it possible to record those streams with livestreamer? 

livestreamer https://www.youtube.com/watch?v=PVckSlOYdZ8
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=PVckSlOYdZ8
Available streams: 240p, 360p, 480p, **720p (best)**, 72p (worst)

(best) being 720p, but 30fps, see below

[info] Available formats for PVckSlOYdZ8:
format    code         extension  resolution note
140          m4a        audio only DASH audio  144k , m4a_dash container, aac  @ 128k (48000Hz)
141          m4a        audio only DASH audio  272k , m4a_dash container, aac  @ 256k (48000Hz)
160          mp4        256x144    DASH video  124k , 15fps, video only
133          mp4        426x240    DASH video  258k , 30fps, video only
134          mp4        640x360    DASH video  616k , 30fps, video only
135          mp4        854x480    DASH video 1116k , 30fps, video only
**298          mp4        1280x720   DASH video 3316k , h264, 60fps, video only**
151          mp4        72p        HLS
132          mp4        240p       HLS
92           mp4        240p       HLS
93           mp4        360p       HLS
94           mp4        480p       HLS
**95           mp4        720p       HLS  (best)**

YouTube is apparently not serving the 60fps stream over HLS...
Does this make playback/file output of YouTube live 60fps impossible? 

Thank you all who made livestreamer possible.

**Comment by chrippa** [comment]
DASH playback is currently not supported. We'll use #223 to track the issue.
