### ISSUE TITLE
multitwitch.tv support?

### ISSUE THREAD

**Issue by StojanovicMilos** [chrippa/livestreamer#973]
Hi!

I love the program, I think it's awesome.

I'm here to make a suggestion/question: I don't know if you've heard about multitwitch. Long story short, you can watch as many streams as you want in one window. Are there any similar plans for livestreamer? It would be awesome if I could watch all international streams via livestreamer.

Now, I know that I can do it manually, but I was hoping you could code something similar to multitwitch.

Thanks, and again: love your program, keep up with good work :)

**Comment by hannespetur** [comment]
Hello!

I just wanted to share my thoughts on this.

I like the idea, so much I'm considering if I should try to work on this myself, but I think creating a portable implementation for this is easier said than done. What I would propose is a script that spawns multiple livestreamer sessions and then automatically interact with the window manager to reposition and resize the media player windows. If you're using VLC you can open it interface-less mode to get even more space to work with. This wouldn't be a one window solution like you asked for but it might still be the way to go.

Cheers

**Comment by donsrbin** [comment]
I like your idea, but unfortunately, it doesn't work in my situation cause I'm using multiple monitors setup, and I want all streams on secondary monitor. That means, in your case, that I have to manually move streams on other monitor and re-resize them (since monitors are not the same resolution).

If it's possible, one window is a way to go imo :)

Thanks again

**Comment by chrippa** [comment]
The Livestreamer CLI is designed to handle one stream at a time and it is not something that is easily changed and probably not worth it when you can use a simple wrapper ([such as this](https://gist.github.com/chrippa/11353159)) to launch multiple instances instead.

**Comment by LostInInaka** [comment]
@donsrbin 

1. copy that gist to a file and save it (you can save it as multitwitch.sh)
2. make sure to make it executable (chmod +X multitwitch.sh)
3. copy your multitwitch stream address
4. run `./multiwitch.sh <multitwitch stream address>` (omit the < > of course
5) the gist will scan through the address and extract the individual stream names and open individual instances for each

Again, this won't embed them all in to one stream, but instead will open one new window for each stream (using the "best" stream according to the gist), so each one will open up in a fairly large window (which you will then have to individually resize - although with some additional scripting you could probably have the open in a favorable position and size)

**Comment by donsrbin** [comment]
Well the problem is that I'm using windows, not linux... ;)

Is it usable on windows 7 and 10? :)
