### ISSUE TITLE
Problem with filmon

### ISSUE THREAD

**Issue by expandables2** [chrippa/livestreamer#975]
Hi i am experiencing a problem with Filmon channels. 
Flimon channels plays and then a few minutes it exits 
I am using vlc player

**Comment by karlo2105** [comment]
No problems here.

**Comment by expandables2** [comment]
ivestreamer 'http://www.filmon.com/tv/itv1' best

After playing for about 5 minutes it exits

**Comment by karlo2105** [comment]
Yeah you are right to me it even drops after 4 minutes. I figure out it's related to HQ time limit which is 3 minutes for free preview. LQ works fine.

**Comment by expandables2** [comment]
Yea i figured livestreamer 'http://www.filmon.com/tv/itv1'  low 
would work but is there any way to watch in hq without it exiting?

**Comment by karlo2105** [comment]
I didn't watch much Filmon so far but all I know in the past HQ worked without interruption. 
Unless you subscribe to their service you will not have any interruptions. But Filmon plugin doesn't support pay service so far. 
Their so called HD is only 480p so in my opinion it's not worthy to pay.

**Comment by biezom** [comment]
livestreamer "http://www.filmon.com/tv/itv1" high_hls
