### ISSUE TITLE
Capturing HLS stream frames

### ISSUE THREAD

**Issue by mattste** [chrippa/livestreamer#976]
Hi there,

I'm working on an image recognition project where I'd like to take a screen shot of a Twitch stream ~1 second. One approach I've been working on is capturing the binary data from the Livestreamer hls stream and then hopefully save a segment as an image with Pillow. However, I'm running into issues with this method, such as non-ASCII characters from the request content.

1) Is there an alternative method that anyone thinks would work well? I'll be running this on a headless remote server.
2) Right now I'm trying to capture the data in this part Livestreamer:
```python
# livestreamer/stream/hls.py
def write(self, sequence, res, chunk_size=8192):
    ...
    b_data = binascii.unhexlify(res.content)
    stream = StringIO.StringIO(b_data)
    img = Image.open(stream)
```

**Comment by intact** [comment]
For saving screenshot every second you can use ffmpeg and something like:
```shell
livestreamer --player "ffmpeg -i" --player-args "{filename} -vf fps=1 out%04d.png" http://www.twitch.tv/channel best
```

**Comment by mattste** [comment]
This works perfectly. Thanks for the help!
