### ISSUE TITLE
can't play twitch/ustream

### ISSUE THREAD

**Issue by panachay** [chrippa/livestreamer#977]
i'm running debian 8 jessie, and when i try to play ustream or twitch stream i get : 
error: No streams found on this URL: (url of the stream)
it is working with others stream like youtube

**Comment by 0880** [comment]
Seems that both plugins are working correctly. Which stream are you trying to watch?

**Comment by panachay** [comment]
ISS live stream : http://www.ustream.tv/channel/iss-hdev-payload

**Comment by 0880** [comment]
Are you using the latest version?

````
livestreamer "http://www.ustream.tv/channel/iss-hdev-payload" best
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/iss-hdev-payload
[cli][info] Available streams: 240p, 240p_alt_fstl, 240p_alt_highwinds, 240p_alt_llnw, 360p, 360p_alt_fstl, 360p_alt_highwinds, 360p_alt_llnw, 480p, 480p_alt_fstl, 480p_alt_highwinds, 480p_alt_llnw, 720p+ (best), 720p+_alt_fstl, 720p+_alt_highwinds, 720p+_alt_llnw, mobile_240p (worst), mobile_360p,mobile_480p
[cli][info] Opening stream: 720p+ (uhs)
````

**Comment by panachay** [comment]
```
$ livestreamer -V
livestreamer 1.10.2
```
is it the lastest ? i tried to install livestreamer with pip but it can only run on root

**Comment by skulblakka** [comment]
No. The current version is 1.12.2

**Comment by panachay** [comment]
well it seems that the debian package is outdated ?

**Comment by 0880** [comment]
You are using an outdated version. More informations are available here: #835

**Comment by chrippa** [comment]
Once a Debian version is released it usually only receive security updates. The latest version of Livestreamer is available in Debian [testing](https://packages.debian.org/stretch/livestreamer) and [unstable](https://packages.debian.org/sid/livestreamer), or you can [install from source](http://docs.livestreamer.io/install.html#source-code).

**Comment by panachay** [comment]
I installed the lastest version with pip and it's working ! thanks
