### ISSUE TITLE
Crunchyroll Without Subtitiles?

### ISSUE THREAD

**Issue by fb39ca4** [chrippa/livestreamer#985]
Is it possible for livestreamer to get videos from Crunchyroll without the baked-in subtitles? In the browser, CR has soft-subs, so they definitely serve those videos.

**Comment by StarWolf3000** [comment]
See #364 
The player of the website uses a different internal API, which provides a "raw" video with switchable soft-subs, while livestreamer connects to a HLS (HTTP Live Stream) which is (mostly) english hard-subbed.
