### ISSUE TITLE
Twitch.tv error

### ISSUE THREAD

**Issue by MonstercatUK** [chrippa/livestreamer#994]
C:\Users\Juan>livestreamer --hls-segment-threads 4 twitch.tv/cohhcarnage source
[cli][info] Found matching plugin twitch for URL twitch.tv/cohhcarnage
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source
(best)
[cli][info] Opening stream: source (hls)
[stream.hls][error] Failed to open segment 7007: Unable to open URL: http://vide
o8.dfw01.hls.ttvnw.net/hls-80eb8c/cohhcarnage_15220336800_268645043/chunked/inde
x-0000007007-BnGe.ts (timed out)
[cli][error] Failed to read data from stream: Read timeout

Getting this error every time i try to use livestreamer, with any stream. Uninstalled and re-installed in case there was any update/bug and it's still happening

**Comment by skulblakka** [comment]
Works fine here. What version are you using?

**Comment by MonstercatUK** [comment]
Latest version, re-installed if from the page in case there was a bug in my already installed and updated version. Not using the nightly build or anything of sorts

**Comment by MonstercatUK** [comment]
Edit: Kept trying over and over until it worked, but it went to freezing every 5 seconds like it used to in issue #918 which I posted before. Added "--player="C:\Program Files\VideoLAN\VLC\vlc.exe --file-caching=10000" --hls-segment-threads 5 --hls-live-edge 3" like you suggested to in said issue and it didn't fix the stutter. Playing with the values doesn't fix it either.

**Comment by 0880** [comment]
>[cli][error] Failed to read data from stream: Read timeout

Looks more like a connection problem between server and client (caused by a slow or unstable internet connection). Does the problem persist if you try to switch to a lower quality (mobile / low / medium)?

**Comment by MonstercatUK** [comment]
I did try with lower qualities and still had the same issues. My internet connection was stable and isn't slow. The problem seems to have fixed on it's own now apparently. This is what I use to launch it now livestreamer --player="C:\Program Files\VideoLAN\VLC\vlc.exe --file-caching=60000" --hls-segment-threads 10 --hls-live-edge 10

**Comment by 0880** [comment]
I still think it was a (temporary) connection problem (maybe only in relation to some Twitch servers).

**Comment by direwolfie** [comment]
> This is what I use to launch it now livestreamer --player="C:\Program Files\VideoLAN\VLC\vlc.exe --file-caching=60000" --hls-segment-threads 10 --hls-live-edge 10

@MonstercatUK  Thanks! Adding `--hls-segment-threads 10` made the stream watchable, but it would skip a bit sometimes (which is still pretty annoying).
And occasionally it would stop completely giving the following error - `[stream.hls][error] Failed to open segment 4413 ... (timed out)`.
Before this solution I was having the same "stutter" problem with "404 Client Error", but not always - only at some times in the day, usually evenings (probably something to do with twitch servers' load?).
