### ISSUE TITLE
m3u8 not working!!

### ISSUE THREAD

**Issue by kobisiva** [chrippa/livestreamer#999]
livestreamer  ""  best

When I trying play it  not working any solution pls??

**Comment by 0880** [comment]
````
Access Denied

You don't have permission to access "http://hlsengextra-lh.akamaihd.net/i/hls24_rajtvuk8@4887/index_1000_av.m3u8" on this server.
````

Some additional parameters are required.

**Comment by kobisiva** [comment]
this stream play on gom player and mx player but not working in vlc

**Comment by 0880** [comment]
Did you read my message above?

````
livestreamer --http-header "User-Agent=HttpGetFile" "hls://http://hlsengextra-lh.akamaihd.net/i/hls24_rajtvuk8@4887/index_1000_av.m3u8" best
````
````
[cli][info] Found matching plugin stream for URL hls://http://hlsengextra-lh.akamaihd.net/i/hls24_rajtvuk8@4887/index_1000_av.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
````

**Comment by kobisiva** [comment]
ok thanks .

**Comment by kobisiva** [comment]
one more help when I push to ffmpeg the sound not working why??

**Comment by sokr** [comment]
I am unable to play "http://live.nwk5.yupptv.tv/nwk5/smil:captainnews.smil/playlist.m3u8" on VLC or GOM player. This link still works in IPTV boxes. Can any one please tell me which player could play this stream. This is the message I get.
![image](https://cloud.githubusercontent.com/assets/7405703/10860344/0cfafb90-7f3d-11e5-898c-edd7a34d4a37.png)
